"""Write the hand-drawn Devanagari letters as KanjiVG-style XML for the app's
bake (fude/study/chars/bake.c, fude_bake_kanjivg; fude/lang/hi/bake.c reads
data/raw/hi/devanagarivg.xml).

    python3 apps/hindi/tools/strokes/compose.py [out.xml]

writes data/raw/hi/devanagarivg.xml (git-ignored) by default: the app's 90
letters (fude/lang/hi/lang.c), in code point order. The output is
deterministic.

Each character is one <kanji>; its strokes are <path>s numbered in writing
order. A letter with a nukta (क़ ... य़, ऩ ऱ ऴ) holds its base letter and the
nukta as two groups, so the bake records them as its parts.
"""

import os
import sys

sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import letters as L                                          # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", "..", "..", ".."))
OUT = os.path.join(ROOT, "data", "raw", "hi", "devanagarivg.xml")

NUKTA = 0x093C

HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!--
Devanagari stroke order data in KanjiVG's format, for the Hindi app's bake.
Generated by apps/hindi/tools/strokes/compose.py from the hand-drawn letters in
apps/hindi/tools/strokes/letters.py. Do not edit: regenerate.
Our own work; licence to be decided (see apps/hindi/tools/strokes/README.md).
Centrelines in a 109 x 109 box, Y down: the headline at y 28, the baseline at
y 84. Strokes numbered in writing order. No kvg:type: Devanagari strokes are
not CJK stroke types. A letter with a nukta holds its base letter and the
nukta as groups.
-->
<kanjivg xmlns:kvg='http://kanjivg.tagaini.net'>
"""


def character_xml(cp):
    """One <kanji> element and its stroke count."""
    strokes, n_base = L.final(cp)
    hexid = "%05x" % cp
    out = ['<kanji id="kvg:kanji_%s">' % hexid,
           '<g id="kvg:%s" kvg:element="%s">' % (hexid, chr(cp))]

    def path(k, s, tab):
        out.append('%s<path id="kvg:%s-s%d" d="%s"/>' % (tab, hexid, k, s.d()))

    base = L.LETTERS[cp].base
    if base is None:
        for k, s in enumerate(strokes, 1):
            path(k, s, "\t")
    else:
        out.append('\t<g id="kvg:%s-g1" kvg:element="%s">' % (hexid, chr(base)))
        for k, s in enumerate(strokes[:n_base], 1):
            path(k, s, "\t\t")
        out.append("\t</g>")
        out.append('\t<g id="kvg:%s-g2" kvg:element="%s">' % (hexid, chr(NUKTA)))
        for k, s in enumerate(strokes[n_base:], n_base + 1):
            path(k, s, "\t\t")
        out.append("\t</g>")
    out.append("</g>")
    out.append("</kanji>")
    return "\n".join(out) + "\n", len(strokes)


def main(argv):
    out = argv[1] if len(argv) > 1 else OUT
    os.makedirs(os.path.dirname(out), exist_ok=True)
    n = strokes = 0
    tmp = out + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER)
        for cp in L.CHARACTERS:
            xml, k = character_xml(cp)
            f.write(xml)
            n += 1
            strokes += k
        f.write("</kanjivg>\n")
    os.replace(tmp, out)
    print("compose: %d characters, %d strokes -> %s" % (n, strokes, out))


if __name__ == "__main__":
    main(sys.argv)
