# Simplified Chinese for Hanzi's own strings (apps/hanzi/tools/strings.py; the
# fourth language of Hanzi Learn!): x(id, text) rows, read by
# tools/strings/build.py fourth().
x('DATA_OFFLINE', '{APP} 可离线使用。你的页面、标记、测验、词语和练习都保存在此设备上：{APP} 不会把它们发送到任何地方。（Google ML Kit 开启时，只需下载一次模型，之后识别和翻译也都在设备上完成。）')
x('SEARCH_HINT', '释义（英文）或读音：tree、mu')
x('HANZI', '汉字')
x('LICENCE_LECTURES', '教材')
x('CREDITS', '笔顺来自 Make Me a Hanzi（Arphic Public License）；读音和释义来自 Unihan 和 CC-CEDICT，西班牙语、葡萄牙语和法语版本来自 KANJIDIC2（EDRDG）；例句来自 Tatoeba（tatoeba.org，CC BY 2.0 FR）；等级来自 HSK 2025 考试大纲。手写和文字识别由 Google ML Kit 提供，开启期间会向 Google 发送匿名使用数据。所有许可协议全文：许可协议。')
x('WELCOME', '欢迎')
x('WELCOME_SKIP', '跳过')
x('WELCOME_START', '开始书写')
x('WELCOME_1_TITLE', '欢迎使用 {APP}')
x('WELCOME_1', '按中文本来的写法，亲手书写中文：{APP} 按顺序展示每个字的笔画，识别你写的字，并告诉你写得怎么样。它可离线使用，所有内容都保存在此设备上。')
x('WELCOME_PHONE', '{APP} 专为平板电脑设计。它也能在手机上使用，只是书写空间较小。')
x('WELCOME_2_TITLE', 'Pencil 或手指')
x('WELCOME_2_TITLE_ANDROID', '触控笔或手指')
x('WELCOME_2', '用 Apple Pencil 书写——此时手指用来移动页面——或者点工具栏上的手形按钮，用一根手指书写，用两根手指移动页面。用 Pencil 书写时，{APP} 会自动切换。工具都在一个可以拖到任意位置的工具栏上；双击它的把手即可将其收起。')
x('WELCOME_2_ANDROID', '用触控笔书写——此时手指用来移动页面——或者点工具栏上的手形按钮，用一根手指书写，用两根手指移动页面。用触控笔书写时，{APP} 会自动切换。工具都在一个可以拖到任意位置的工具栏上；双击它的把手即可将其收起。')
x('WELCOME_3_TITLE', '用相机读取')
x('WELCOME_3', '轻点工具栏上的相机，或长按页面选择“照片文字”，然后对准中文文字：一本书、一块招牌、一份菜单。{APP} 会实时识别并框出每一行：“定格”可保留它们，“写下”会把它们以手写形式写到页面上供你描摹，“用 Google 翻译”则会用你的语言显示它们。也可以使用照片。')
x('WELCOME_4_TITLE', '复制、粘贴、检查')
x('WELCOME_4', '用套索圈住所写的内容：可以复制，用“复制为文本”在任何应用中使用，“检查”它写的是什么，或“保存词语”。长按页面即可粘贴：“粘贴文本”会把在任何地方复制的文字一笔一画地以手写形式写出来。')
x('WELCOME_5_TITLE', '翻译')
x('WELCOME_5', '用套索圈住你写的内容，选择“用 Google 翻译”，即可用你的语言阅读。在“生词本”中，“用 Google 翻译”的方向相反：用你的语言输入，得到中文译文，并可保存、练习或书写其中的词语。翻译模型只需下载一次，之后即可离线使用。')
x('WELCOME_6_TITLE', '学习')
x('WELCOME_6', '左上角的菜单里有学习所需的一切：带笔顺的汉字，简体和繁体，按 HSK 等级排列；可以阅读和收听的词语、练习、复习和测验。“教材”中有免费课程，以及你导入的 PDF、照片和扫描的页面，可以阅读并在上面书写。')
x('WELCOME_7_TITLE', '你的进度')
x('WELCOME_7', '“统计”会显示你的连续天数、书写的日子、每周的分数、测验，以及需要多加练习的字；“作品集”保存你练习过的每个字及每次尝试。所有内容都保存在此设备上：可在“设置 › 你的数据”中备份。')
x('LECTURE_PHRASEBOOK', '中文会话手册')
x('LECTURE_PHRASEBOOK_ABOUT', '发音、声调、一点语法，以及旅行所需的普通话常用语（问候、数字、时间、出行、饮食、购物），附拼音。来自 Wikivoyage（维基导游）。')
