# Copyright (c) 2026 Borja Vazquez Cuesta. All rights reserved.

# Arabic for the drawing core's strings (the fourth language of Arabic Learn!):
# x(id, text) rows, read by tools/strings/build.py fourth().
x('FINISH', 'إنهاء')
x('CLOSE', 'إغلاق')
x('MORE_MENU', 'المزيد')
x('READ_CLOSE_IN', 'إغلاق ({0})')
x('CANCEL', 'إلغاء')
x('DELETE', 'حذف')
x('SAVE', 'حفظ')
x('RENAME', 'إعادة تسمية')
x('UNDO', 'تراجع')
x('REDO', 'إعادة')
x('OF_N', '{0} من {1}')
x('TOOL_FINGER', 'الإصبع')
x('FINGER_ON', 'إصبعك يكتب: والصفحة تتحرك بإصبعين')
x('FINGER_OFF', 'قلم Apple Pencil يكتب: وأصابعك تحرّك الصفحة')
x('FINGER_OFF_ANDROID', 'قلم اللمس يكتب: وأصابعك تحرّك الصفحة')
x('TOOL_DRAW', 'القلم')
x('TOOL_MARK', 'قلم التظليل')
x('TOOL_ERASE', 'الممحاة')
x('TOOL_LASSO', 'أداة التحديد')
x('TOOL_CLEAR', 'محو الصفحة')
x('TOOL_COLOR', 'اللون')
x('TOOL_PAGE', 'الصفحة')
x('TOOL_SCREEN', 'الشاشة')
x('TOOL_PAPER', 'الورق')
x('TOOL_ROTATE', 'تدوير')
x('TOOL_RESET', 'إعادة ضبط العرض')
x('MENU', 'القائمة')
x('PAPER_DOTS', 'نقاط')
x('PAPER_SQUARES', 'مربعات')
x('PAPER_LINES', 'أسطر')
x('PAPER_NONE', 'فارغ')
x('SEL_CUT', 'قص')
x('SEL_COPY', 'نسخ')
x('SEL_COPIED', 'تم النسخ')
x('SEL_DUPLICATE', 'تكرار')
x('CTX_PASTE', 'لصق')
x('CTX_SELECT_ALL', 'تحديد الكل')
x('SIDE_NOTES', 'الملاحظات')
x('FOLDER', 'مجلد')
x('CANVAS', 'لوحة')
x('SETTINGS', 'الإعدادات')
x('SETTINGS_THEME', 'المظهر')
x('SETTINGS_LANGUAGE', 'اللغة')
x('SETTINGS_PEN_WIDTH', 'سُمك القلم')
x('SETTINGS_EVEN', 'منتظم')
x('SETTINGS_PRESSURE', 'الضغط')
x('SETTINGS_PAPER', 'الأسطر والمربعات')
x('SETTINGS_UI_SIZE', 'حجم الواجهة')
x('SIZE_SMALL', 'صغير')
x('SIZE_MEDIUM', 'متوسط')
x('SIZE_LARGE', 'كبير')
x('SETTINGS_ABOUT', 'حول التطبيق')
x('ABOUT_BUILT', '{APP} {0}، بُني في {1}.')
x('RATE', 'قيّم {APP}')
x('TUTORIAL', 'الشرح التعليمي')
x('FAQ_CONTACT', 'الأسئلة الشائعة والتواصل')
x('FAQ_OPEN', 'الأسئلة الشائعة')
x('CONTACT_WRITE', 'لديك سؤال أو فكرة أو مشكلة؟ راسلنا على:')
x('DATA', 'بياناتك')
x('DATA_BACKUP_IOS', 'وهي مشمولة أيضًا في النسخ الاحتياطي على iCloud لهذا الجهاز عند تفعيله (الإعدادات › اسمك › iCloud › النسخ الاحتياطي على iCloud): استعادة الجهاز، أو إعداد جهاز جديد، من تلك النسخة تعيدها إليك.')
x('DATA_BACKUP_ANDROID', 'وهي مشمولة أيضًا في نسخة Google الاحتياطية لهذا الجهاز عند تفعيلها (الإعدادات › Google › الاحتفاظ بنسخة احتياطية): تعود إلى أي جهاز جديد أو مُعاد ضبطه يُستعاد من تلك النسخة.')
x('DATA_BACKUP_DESKTOP', 'وهي محفوظة في مجلد {APP} على هذا الكمبيوتر.')
x('DATA_HOW', 'لتحتفظ بنسختك الخاصة، أو لتنتقل إلى جهاز آخر: «تصدير» يضع كل شيء في ملف واحد تحفظه حيث تشاء (خدمة تخزين سحابي، أو الجهاز، أو رسالة)؛ و«استيراد»، على أي جهاز، يعيده كما كان، مستبدلًا ما هو موجود.')
x('DATA_EXPORT', 'تصدير')
x('DATA_IMPORT', 'استيراد')
x('DATA_EXPORT_READY', 'نسختك الاحتياطية جاهزة (عدد الملفات: {0}): اختر مكان حفظها.')
x('DATA_EXPORT_SAVED', 'تم الحفظ (عدد الملفات: {0}): {1}')
x('DATA_EXPORT_FAILED', 'تعذّر إنشاء النسخة الاحتياطية.')
x('DATA_NOT_BACKUP', 'هذا الملف ليس نسخة احتياطية من {APP}، أو أنه تالف.')
x('DATA_CANT_OPEN', 'تعذّر فتح الملف.')
x('DATA_CONFIRM', 'هل تريد استبدال كل ما في {APP} على هذا الجهاز بهذه النسخة الاحتياطية المؤرخة في {0} ({1,plural, zero{# صفحة} one{صفحة واحدة} two{صفحتان} few{# صفحات} many{# صفحة} other{# صفحة}})؟ سيزول كل ما هو موجود الآن: صدّره أولًا إن أردت الاحتفاظ به.')
x('DATA_REPLACE', 'استبدال')
x('DATA_IMPORTED', 'تم الاستيراد: كل شيء كما كان في {0}.')
x('DATA_IMPORT_FAILED', 'تعذّر استيراد النسخة الاحتياطية: لم يتغيّر شيء.')
x('LICENCES', 'التراخيص')
x('LICENCE_FONTS', 'الخطوط')
x('LICENCE_LIBRARIES', 'المكتبات البرمجية')
x('LICENCE_MISSING', 'هذا الترخيص غير موجود في التطبيق.')
x('THEME_PAPER', 'ورق')
x('THEME_WASHI', 'واشي')
x('THEME_NIGHT', 'ليل')
x('THEME_MATCHA', 'ماتشا')
x('THEME_SAKURA', 'ساكورا')
x('NOTE_FOLDER_BODY', 'مجلد، {0,plural, zero{# لوحة} one{لوحة واحدة} two{لوحتان} few{# لوحات} many{# لوحة} other{# لوحة}}')
x('NOTE_RENAME_FOLDER', 'إعادة تسمية المجلد')
x('NOTE_RENAME_CANVAS', 'إعادة تسمية اللوحة')
x('NOTE_DELETE_TITLE', 'حذف «{0}»؟')
x('NOTE_DELETE_FOLDER', 'سيُحذف معه ما فيه: {0,plural, zero{# لوحة} one{لوحة واحدة} two{لوحتان} few{# لوحات} many{# لوحة} other{# لوحة}} (وأي مجلدات). لا يمكن التراجع عن ذلك.')
x('NOTE_UNDONE', 'لا يمكن التراجع عن ذلك.')
x('NOTE_PAGE', 'صفحة')
x('BACK', 'رجوع')
x('LIBRARY_TITLE', 'الدروس')
x('LIBRARY_CAPTION', 'اقرأها، وكبّرها، واكتب عليها: تبقى ملاحظاتك على الصفحة.')
x('LIBRARY_BOOKS', 'دروس مجانية')
x('LIBRARY_YOURS', 'مستنداتك')
x('LIBRARY_YOURS_EMPTY', 'ملفات PDF والصور التي تضيفها، والصفحات التي تمسحها ضوئيًا، تظهر هنا وفي ملاحظاتك، لتقرأها وتكتب عليها.')
x('LIBRARY_FILES', 'من الملفات')
x('LIBRARY_PHOTOS', 'من الصور')
x('LIBRARY_SCAN', 'مسح ضوئي')
x('LIBRARY_FOLDER', 'الدروس')
x('DOC_CANT_PICK', 'تعذّر عرض الملفات.')
x('DOC_CANT_OPEN', 'تعذّر فتحه كملف PDF أو كصورة.')
x('DOC_NOT_HERE', 'تُفتح ملفات PDF حاليًا على iPad وMac فقط.')
x('DOC_IMPORTED', 'أُضيف «{0}» إلى ملاحظاتك')
x('DOC_SCAN_NAME', 'مسح ضوئي {0}')
x('DOC_PHOTOS_NAME', 'صور {0}')
x('DOC_SEARCH', 'بحث')
x('DOC_SEARCH_HINT', 'كلمات للبحث عنها')
x('DOC_SEARCHING', 'جارٍ البحث…')
x('DOC_NO_MATCHES', 'لا توجد نتائج')
x('DOC_BEFORE', 'السابق')
x('DOC_NEXT', 'التالي')
x('DOC_PAGE', 'الصفحة')
x('DOC_TURN', 'تدوير الصفحة')
x('DOC_TURN_FULL', 'لا يمكن تدوير المزيد من الصفحات في هذا المستند.')
x('DOC_EXPORT', 'مشاركة كملف PDF')
x('DOC_EXPORT_FAILED', 'تعذّر إنشاء ملف PDF.')
x('DOC_EXPORTED', 'تم الحفظ: {0}')
x('DAY_MON', 'الاثنين')
x('DAY_TUE', 'الثلاثاء')
x('DAY_WED', 'الأربعاء')
x('DAY_THU', 'الخميس')
x('DAY_FRI', 'الجمعة')
x('DAY_SAT', 'السبت')
x('DAY_SUN', 'الأحد')
x('DATE', '{0} {1} {2}')
x('DATE_TIME', '{0}، {1}')
x('MONTH_1', 'يناير')
x('MONTH_2', 'فبراير')
x('MONTH_3', 'مارس')
x('MONTH_4', 'أبريل')
x('MONTH_5', 'مايو')
x('MONTH_6', 'يونيو')
x('MONTH_7', 'يوليو')
x('MONTH_8', 'أغسطس')
x('MONTH_9', 'سبتمبر')
x('MONTH_10', 'أكتوبر')
x('MONTH_11', 'نوفمبر')
x('MONTH_12', 'ديسمبر')
