# Korean for the drawing core's strings (the fourth language of Hangul Learn!):
# x(id, text) rows, read by tools/strings/build.py fourth().
x('FINISH', '마치기')
x('CLOSE', '닫기')
x('MORE_MENU', '더 보기')
x('READ_CLOSE_IN', '닫기({0})')
x('CANCEL', '취소')
x('DELETE', '삭제')
x('SAVE', '저장')
x('RENAME', '이름 바꾸기')
x('UNDO', '실행 취소')
x('REDO', '다시 실행')
x('OF_N', '{0} / {1}')
x('TOOL_FINGER', '손가락')
x('FINGER_ON', '손가락으로 씁니다. 페이지는 두 손가락으로 움직입니다')
x('FINGER_OFF', 'Apple Pencil로 씁니다. 페이지는 손가락으로 움직입니다')
x('FINGER_OFF_ANDROID', '펜으로 씁니다. 페이지는 손가락으로 움직입니다')
x('TOOL_DRAW', '쓰기')
x('TOOL_MARK', '마커')
x('TOOL_ERASE', '지우개')
x('TOOL_LASSO', '올가미')
x('TOOL_CLEAR', '페이지 지우기')
x('TOOL_COLOR', '색상')
x('TOOL_PAGE', '페이지')
x('TOOL_SCREEN', '화면')
x('TOOL_PAPER', '용지')
x('TOOL_ROTATE', '회전')
x('TOOL_RESET', '보기 초기화')
x('MENU', '메뉴')
x('PAPER_DOTS', '점')
x('PAPER_SQUARES', '모눈')
x('PAPER_LINES', '줄')
x('PAPER_NONE', '무지')
x('SEL_CUT', '잘라내기')
x('SEL_COPY', '복사')
x('SEL_COPIED', '복사됨')
x('SEL_DUPLICATE', '복제')
x('CTX_PASTE', '붙여넣기')
x('CTX_SELECT_ALL', '모두 선택')
x('SIDE_NOTES', '노트')
x('FOLDER', '폴더')
x('CANVAS', '캔버스')
x('SETTINGS', '설정')
x('SETTINGS_THEME', '테마')
x('SETTINGS_LANGUAGE', '언어')
x('SETTINGS_PEN_WIDTH', '펜 굵기')
x('SETTINGS_EVEN', '균일')
x('SETTINGS_PRESSURE', '필압')
x('SETTINGS_PAPER', '줄과 모눈')
x('SETTINGS_UI_SIZE', '인터페이스 크기')
x('SIZE_SMALL', '작게')
x('SIZE_MEDIUM', '보통')
x('SIZE_LARGE', '크게')
x('SETTINGS_ABOUT', '정보')
x('ABOUT_BUILT', '{APP} {0}, {1} 빌드.')
x('RATE', '{APP} 평가하기')
x('TUTORIAL', '튜토리얼')
x('DATA', '내 데이터')
x('DATA_BACKUP_IOS', '이 기기의 iCloud 백업이 켜져 있으면(설정 › 사용자 이름 › iCloud › iCloud 백업) 데이터도 함께 백업됩니다. 이 백업으로 기기를 복원하거나 새 기기를 설정하면 데이터가 돌아옵니다.')
x('DATA_BACKUP_ANDROID', '이 기기의 Google 백업이 켜져 있으면(설정 › Google › 백업) 데이터도 함께 백업됩니다. 이 백업에서 복원하는 새 기기나 초기화한 기기로 데이터가 돌아옵니다.')
x('DATA_BACKUP_DESKTOP', '이 컴퓨터의 {APP} 폴더에 보관됩니다.')
x('DATA_HOW', '직접 사본을 보관하거나 다른 기기로 옮기려면: ‘내보내기’는 모든 것을 파일 하나에 담아 원하는 곳(클라우드 드라이브, 기기, 메시지)에 보관할 수 있게 하고, ‘가져오기’는 어느 기기에서든 이를 되돌려 놓습니다. 지금 있는 것은 대체됩니다.')
x('DATA_EXPORT', '내보내기')
x('DATA_IMPORT', '가져오기')
x('DATA_EXPORT_READY', '백업이 준비되었습니다(파일 {0}개). 보관할 곳을 선택하세요.')
x('DATA_EXPORT_SAVED', '저장했습니다(파일 {0}개): {1}')
x('DATA_EXPORT_FAILED', '백업을 만들지 못했습니다.')
x('DATA_NOT_BACKUP', '이 파일은 {APP} 백업이 아니거나 손상되었습니다.')
x('DATA_CANT_OPEN', '파일을 열지 못했습니다.')
x('DATA_CONFIRM', '이 기기의 {APP}에 있는 모든 것을 {0}에 만든 이 백업({1}페이지)으로 대체할까요? 지금 있는 것은 사라집니다. 보관하려면 먼저 내보내세요.')
x('DATA_REPLACE', '대체')
x('DATA_IMPORTED', '가져왔습니다. 모든 것이 {0}의 상태로 돌아왔습니다.')
x('DATA_IMPORT_FAILED', '백업을 가져오지 못했습니다. 아무것도 바뀌지 않았습니다.')
x('LICENCES', '라이선스')
x('LICENCE_FONTS', '글꼴')
x('LICENCE_LIBRARIES', '라이브러리')
x('LICENCE_MISSING', '이 라이선스가 앱에 없습니다.')
x('THEME_PAPER', '종이')
x('THEME_WASHI', '와시')
x('THEME_NIGHT', '밤')
x('THEME_MATCHA', '말차')
x('THEME_SAKURA', '벚꽃')
x('NOTE_FOLDER_BODY', '폴더 · 캔버스 {0}개')
x('NOTE_RENAME_FOLDER', '폴더 이름 바꾸기')
x('NOTE_RENAME_CANVAS', '캔버스 이름 바꾸기')
x('NOTE_DELETE_TITLE', '‘{0}’을(를) 삭제할까요?')
x('NOTE_DELETE_FOLDER', '안에 있는 캔버스 {0}개(및 폴더)도 함께 삭제됩니다. 되돌릴 수 없습니다.')
x('NOTE_UNDONE', '되돌릴 수 없습니다.')
x('NOTE_PAGE', '페이지')
x('BACK', '뒤로')
x('LIBRARY_TITLE', '교재')
x('LIBRARY_CAPTION', '읽고, 확대하고, 그 위에 쓰세요. 메모는 페이지에 남습니다.')
x('LIBRARY_BOOKS', '무료 교재')
x('LIBRARY_YOURS', '내 문서')
x('LIBRARY_YOURS_EMPTY', '가져온 PDF와 이미지, 스캔한 페이지는 여기와 노트에 표시되며, 읽고 그 위에 쓸 수 있습니다.')
x('LIBRARY_FILES', '파일에서')
x('LIBRARY_PHOTOS', '사진에서')
x('LIBRARY_SCAN', '페이지 스캔')
x('LIBRARY_FOLDER', '교재')
x('DOC_CANT_PICK', '파일을 표시하지 못했습니다.')
x('DOC_CANT_OPEN', 'PDF나 이미지로 열지 못했습니다.')
x('DOC_NOT_HERE', 'PDF는 아직 iPad와 Mac에서만 열립니다.')
x('DOC_IMPORTED', '‘{0}’ 문서를 노트에 추가했습니다')
x('DOC_SCAN_NAME', '스캔 {0}')
x('DOC_PHOTOS_NAME', '사진 {0}')
x('DOC_SEARCH', '검색')
x('DOC_SEARCH_HINT', '찾을 단어')
x('DOC_SEARCHING', '검색 중…')
x('DOC_NO_MATCHES', '결과 없음')
x('DOC_BEFORE', '이전')
x('DOC_NEXT', '다음')
x('DOC_PAGE', '페이지')
x('DOC_TURN', '페이지 회전')
x('DOC_TURN_FULL', '이 문서에서는 더 이상 페이지를 회전할 수 없습니다.')
x('DOC_EXPORT', 'PDF로 공유')
x('DOC_EXPORT_FAILED', 'PDF를 만들지 못했습니다.')
x('DOC_EXPORTED', '저장했습니다: {0}')
x('DAY_MON', '월')
x('DAY_TUE', '화')
x('DAY_WED', '수')
x('DAY_THU', '목')
x('DAY_FRI', '금')
x('DAY_SAT', '토')
x('DAY_SUN', '일')
x('DATE', '{2}년 {1} {0}일')
x('DATE_TIME', '{0} {1}')
x('MONTH_1', '1월')
x('MONTH_2', '2월')
x('MONTH_3', '3월')
x('MONTH_4', '4월')
x('MONTH_5', '5월')
x('MONTH_6', '6월')
x('MONTH_7', '7월')
x('MONTH_8', '8월')
x('MONTH_9', '9월')
x('MONTH_10', '10월')
x('MONTH_11', '11월')
x('MONTH_12', '12월')
