# Copyright (c) 2026 Borja Vazquez Cuesta. All rights reserved.

# Hindi for the drawing core's strings (the fourth language of Hindi Learn!):
# x(id, text) rows, read by tools/strings/build.py fourth().
x('FINISH', 'पूरा करें')
x('CLOSE', 'बंद करें')
x('MORE_MENU', 'ज़्यादा')
x('READ_CLOSE_IN', 'बंद करें ({0})')
x('CANCEL', 'रद्द करें')
x('DELETE', 'मिटाएँ')
x('SAVE', 'सेव करें')
x('RENAME', 'नाम बदलें')
x('UNDO', 'पहले जैसा करें')
x('REDO', 'फिर से करें')
x('OF_N', '{1} में से {0}')
x('TOOL_FINGER', 'उंगली')
x('FINGER_ON', 'उंगली से लिखें: पेज दो उंगलियों से खिसकाएँ')
x('FINGER_OFF', 'Apple Pencil से लिखें: पेज उंगलियों से खिसकाएँ')
x('FINGER_OFF_ANDROID', 'स्टाइलस से लिखें: पेज उंगलियों से खिसकाएँ')
x('TOOL_DRAW', 'पेन')
x('TOOL_MARK', 'मार्कर')
x('TOOL_ERASE', 'इरेज़र')
x('TOOL_LASSO', 'लैसो')
x('TOOL_CLEAR', 'पेज साफ़ करें')
x('TOOL_COLOR', 'रंग')
x('TOOL_PAGE', 'पेज')
x('TOOL_SCREEN', 'स्क्रीन')
x('TOOL_PAPER', 'कागज़')
x('TOOL_ROTATE', 'घुमाएँ')
x('TOOL_RESET', 'व्यू रीसेट करें')
x('MENU', 'मेन्यू')
x('PAPER_DOTS', 'बिंदु')
x('PAPER_SQUARES', 'चौखाने')
x('PAPER_LINES', 'लाइनें')
x('PAPER_NONE', 'सादा')
x('SEL_CUT', 'काटें')
x('SEL_COPY', 'कॉपी करें')
x('SEL_COPIED', 'कॉपी हो गया')
x('SEL_DUPLICATE', 'डुप्लिकेट बनाएँ')
x('CTX_PASTE', 'चिपकाएँ')
x('CTX_SELECT_ALL', 'सभी चुनें')
x('SIDE_NOTES', 'नोट्स')
x('FOLDER', 'फ़ोल्डर')
x('CANVAS', 'कैनवस')
x('SETTINGS', 'सेटिंग्स')
x('SETTINGS_THEME', 'थीम')
x('SETTINGS_LANGUAGE', 'भाषा')
x('SETTINGS_PEN_WIDTH', 'पेन की मोटाई')
x('SETTINGS_EVEN', 'एकसमान')
x('SETTINGS_PRESSURE', 'दबाव')
x('SETTINGS_PAPER', 'लाइनें और चौखाने')
x('SETTINGS_UI_SIZE', 'इंटरफ़ेस का आकार')
x('SIZE_SMALL', 'छोटा')
x('SIZE_MEDIUM', 'मध्यम')
x('SIZE_LARGE', 'बड़ा')
x('SETTINGS_ABOUT', 'ऐप के बारे में')
x('ABOUT_BUILT', '{APP} {0}, {1} को बिल्ड किया गया।')
x('RATE', '{APP} को रेटिंग दें')
x('TUTORIAL', 'ट्यूटोरियल')
x('FAQ_CONTACT', 'सवाल और संपर्क')
x('FAQ_OPEN', 'अक्सर पूछे जाने वाले सवाल')
x('CONTACT_WRITE', 'कोई सवाल, सुझाव या समस्या? हमें लिखें:')
x('DATA', 'आपका डेटा')
x('DATA_BACKUP_IOS', 'iCloud बैकअप चालू होने पर (सेटिंग्स › आपका नाम › iCloud › iCloud बैकअप) ये इस डिवाइस के बैकअप में भी शामिल होते हैं: उस बैकअप से डिवाइस को रीस्टोर करने या नया डिवाइस सेट अप करने पर ये वापस आ जाते हैं।')
x('DATA_BACKUP_ANDROID', 'Google बैकअप चालू होने पर (सेटिंग्स › Google › बैकअप) ये इस डिवाइस के बैकअप में भी शामिल होते हैं: जो नया या रीसेट किया गया डिवाइस उस बैकअप से रीस्टोर होता है, उसमें ये वापस आ जाते हैं।')
x('DATA_BACKUP_DESKTOP', 'ये इस कंप्यूटर पर {APP} के फ़ोल्डर में रखे जाते हैं।')
x('DATA_HOW', 'अपनी खुद की कॉपी रखने या किसी दूसरे डिवाइस पर जाने के लिए: “एक्सपोर्ट करें” से सब कुछ एक फ़ाइल में आ जाता है, जिसे आप जहाँ चाहें रख सकते हैं (क्लाउड ड्राइव, यह डिवाइस, कोई मैसेज); किसी भी डिवाइस पर “इंपोर्ट करें” से सब कुछ वापस आ जाता है — वहाँ पहले से मौजूद चीज़ों की जगह।')
x('DATA_EXPORT', 'एक्सपोर्ट करें')
x('DATA_IMPORT', 'इंपोर्ट करें')
x('DATA_EXPORT_READY', 'आपका बैकअप तैयार है ({0} फ़ाइलें): चुनें कि इसे कहाँ रखना है।')
x('DATA_EXPORT_SAVED', 'सेव हो गया ({0} फ़ाइलें): {1}')
x('DATA_EXPORT_FAILED', 'बैकअप नहीं बन सका।')
x('DATA_NOT_BACKUP', 'यह फ़ाइल {APP} का बैकअप नहीं है, या खराब हो गई है।')
x('DATA_CANT_OPEN', 'फ़ाइल नहीं खुल सकी।')
x('DATA_CONFIRM', 'इस डिवाइस पर {APP} में जो कुछ है, क्या उसे {0} के इस बैकअप ({1,plural, one{# पेज} other{# पेज}}) से बदल दें? अभी यहाँ जो है, वह मिट जाएगा: अगर उसे रखना है, तो पहले एक्सपोर्ट कर लें।')
x('DATA_REPLACE', 'बदलें')
x('DATA_IMPORTED', 'इंपोर्ट हो गया: सब कुछ वैसा ही है जैसा {0} को था।')
x('DATA_IMPORT_FAILED', 'बैकअप इंपोर्ट नहीं हो सका: कुछ भी नहीं बदला।')
x('LICENCES', 'लाइसेंस')
x('LICENCE_FONTS', 'फ़ॉन्ट')
x('LICENCE_LIBRARIES', 'लाइब्रेरी')
x('LICENCE_MISSING', 'यह लाइसेंस ऐप में नहीं है।')
x('THEME_PAPER', 'कागज़')
x('THEME_WASHI', 'वाशी')
x('THEME_NIGHT', 'रात')
x('THEME_MATCHA', 'माचा')
x('THEME_SAKURA', 'साकुरा')
x('NOTE_FOLDER_BODY', 'फ़ोल्डर, {0,plural, one{# कैनवस} other{# कैनवस}}')
x('NOTE_RENAME_FOLDER', 'फ़ोल्डर का नाम बदलें')
x('NOTE_RENAME_CANVAS', 'कैनवस का नाम बदलें')
x('NOTE_DELETE_TITLE', '“{0}” मिटाएँ?')
x('NOTE_DELETE_FOLDER', 'इसमें मौजूद {0,plural, one{# कैनवस} other{# कैनवस}} (और सभी फ़ोल्डर) भी मिट जाएँगे। इसे पहले जैसा नहीं किया जा सकता।')
x('NOTE_UNDONE', 'इसे पहले जैसा नहीं किया जा सकता।')
x('NOTE_PAGE', 'पेज')
x('BACK', 'वापस')
x('LIBRARY_TITLE', 'पाठ')
x('LIBRARY_CAPTION', 'इन्हें पढ़ें, ज़ूम करें, इन पर लिखें: आपके नोट्स पेज पर ही रहते हैं।')
x('LIBRARY_BOOKS', 'मुफ़्त पाठ')
x('LIBRARY_YOURS', 'आपके दस्तावेज़')
x('LIBRARY_YOURS_EMPTY', 'आप जो PDF और तस्वीरें लाते हैं, और जो पेज स्कैन करते हैं, वे यहाँ और आपके नोट्स में दिखते हैं, ताकि आप उन्हें पढ़ सकें और उन पर लिख सकें।')
x('LIBRARY_FILES', 'फ़ाइलों से')
x('LIBRARY_PHOTOS', 'फ़ोटो से')
x('LIBRARY_SCAN', 'पेज स्कैन करें')
x('LIBRARY_FOLDER', 'पाठ')
x('DOC_CANT_PICK', 'फ़ाइलें नहीं दिखाई जा सकीं।')
x('DOC_CANT_OPEN', 'इसे PDF या तस्वीर के रूप में नहीं खोला जा सका।')
x('DOC_NOT_HERE', 'फ़िलहाल PDF सिर्फ़ iPad और Mac पर खुलती हैं।')
x('DOC_IMPORTED', '“{0}” आपके नोट्स में है')
x('DOC_SCAN_NAME', 'स्कैन {0}')
x('DOC_PHOTOS_NAME', 'फ़ोटो {0}')
x('DOC_SEARCH', 'खोजें')
x('DOC_SEARCH_HINT', 'खोजने के लिए शब्द')
x('DOC_SEARCHING', 'खोजा जा रहा है…')
x('DOC_NO_MATCHES', 'नहीं मिला')
x('DOC_BEFORE', 'पिछला')
x('DOC_NEXT', 'अगला')
x('DOC_PAGE', 'पेज')
x('DOC_TURN', 'पेज घुमाएँ')
x('DOC_TURN_FULL', 'इस दस्तावेज़ में अब और पेज नहीं घुमाए जा सकते।')
x('DOC_EXPORT', 'PDF के रूप में शेयर करें')
x('DOC_EXPORT_FAILED', 'PDF नहीं बन सकी।')
x('DOC_EXPORTED', 'सेव हो गया: {0}')
x('DAY_MON', 'सो')
x('DAY_TUE', 'मं')
x('DAY_WED', 'बु')
x('DAY_THU', 'गु')
x('DAY_FRI', 'शु')
x('DAY_SAT', 'श')
x('DAY_SUN', 'र')
x('DATE', '{0} {1} {2}')
x('DATE_TIME', '{0}, {1}')
x('MONTH_1', 'जन॰')
x('MONTH_2', 'फ़र॰')
x('MONTH_3', 'मार्च')
x('MONTH_4', 'अप्रैल')
x('MONTH_5', 'मई')
x('MONTH_6', 'जून')
x('MONTH_7', 'जुल॰')
x('MONTH_8', 'अग॰')
x('MONTH_9', 'सित॰')
x('MONTH_10', 'अक्तू॰')
x('MONTH_11', 'नव॰')
x('MONTH_12', 'दिस॰')
