# Copyright (c) 2026 Borja Vazquez Cuesta. All rights reserved.

# Thai for the drawing core's strings (the fourth language of Thai Learn!):
# x(id, text) rows, read by tools/strings/build.py fourth().
x('FINISH', 'เสร็จสิ้น')
x('CLOSE', 'ปิด')
x('MORE_MENU', 'เพิ่มเติม')
x('READ_CLOSE_IN', 'ปิด ({0})')
x('CANCEL', 'ยกเลิก')
x('DELETE', 'ลบ')
x('SAVE', 'บันทึก')
x('RENAME', 'เปลี่ยนชื่อ')
x('UNDO', 'เลิกทำ')
x('REDO', 'ทำซ้ำ')
x('OF_N', '{0} จาก {1}')
x('TOOL_FINGER', 'นิ้ว')
x('FINGER_ON', 'เขียนด้วยนิ้ว: ใช้สองนิ้วเลื่อนหน้า')
x('FINGER_OFF', 'เขียนด้วย Apple Pencil: ใช้นิ้วเลื่อนหน้า')
x('FINGER_OFF_ANDROID', 'เขียนด้วยปากกาสไตลัส: ใช้นิ้วเลื่อนหน้า')
x('TOOL_DRAW', 'เขียน')
x('TOOL_MARK', 'ปากกาเน้นข้อความ')
x('TOOL_ERASE', 'ยางลบ')
x('TOOL_LASSO', 'บ่วงบาศ')
x('TOOL_CLEAR', 'ลบทั้งหน้า')
x('TOOL_COLOR', 'สี')
x('TOOL_PAGE', 'หน้า')
x('TOOL_SCREEN', 'หน้าจอ')
x('TOOL_PAPER', 'กระดาษ')
x('TOOL_ROTATE', 'หมุน')
x('TOOL_RESET', 'รีเซ็ตมุมมอง')
x('MENU', 'เมนู')
x('PAPER_DOTS', 'จุด')
x('PAPER_SQUARES', 'ตาราง')
x('PAPER_LINES', 'เส้นบรรทัด')
x('PAPER_NONE', 'เปล่า')
x('SEL_CUT', 'ตัด')
x('SEL_COPY', 'คัดลอก')
x('SEL_COPIED', 'คัดลอกแล้ว')
x('SEL_DUPLICATE', 'ทำสำเนา')
x('CTX_PASTE', 'วาง')
x('CTX_SELECT_ALL', 'เลือกทั้งหมด')
x('SIDE_NOTES', 'โน้ต')
x('FOLDER', 'โฟลเดอร์')
x('CANVAS', 'แคนวาส')
x('SETTINGS', 'การตั้งค่า')
x('SETTINGS_THEME', 'ธีม')
x('SETTINGS_LANGUAGE', 'ภาษา')
x('SETTINGS_PEN_WIDTH', 'ความหนาของเส้น')
x('SETTINGS_EVEN', 'สม่ำเสมอ')
x('SETTINGS_PRESSURE', 'ตามแรงกด')
x('SETTINGS_PAPER', 'เส้นบรรทัดและตาราง')
x('SETTINGS_UI_SIZE', 'ขนาดอินเทอร์เฟซ')
x('SIZE_SMALL', 'เล็ก')
x('SIZE_MEDIUM', 'กลาง')
x('SIZE_LARGE', 'ใหญ่')
x('SETTINGS_ABOUT', 'เกี่ยวกับ')
x('ABOUT_BUILT', '{APP} {0} สร้างเมื่อ {1}')
x('RATE', 'ให้คะแนน {APP}')
x('TUTORIAL', 'บทแนะนำ')
x('FAQ_CONTACT', 'คำถามที่พบบ่อยและติดต่อ')
x('FAQ_OPEN', 'คำถามที่พบบ่อย')
x('CONTACT_WRITE', 'มีคำถาม ไอเดีย หรือพบปัญหา เขียนถึงเราได้ที่:')
x('DATA', 'ข้อมูลของคุณ')
x('DATA_BACKUP_IOS', 'ข้อมูลเหล่านี้ยังรวมอยู่ในข้อมูลสำรอง iCloud ของอุปกรณ์นี้เมื่อเปิดใช้ (การตั้งค่า › ชื่อของคุณ › iCloud › ข้อมูลสำรอง iCloud): เมื่อกู้คืนอุปกรณ์ หรือตั้งค่าอุปกรณ์เครื่องใหม่จากข้อมูลสำรองนั้น ข้อมูลก็จะกลับมา')
x('DATA_BACKUP_ANDROID', 'ข้อมูลเหล่านี้ยังรวมอยู่ในข้อมูลสำรองของ Google ในอุปกรณ์นี้เมื่อเปิดใช้ (การตั้งค่า › Google › ข้อมูลสำรอง): อุปกรณ์เครื่องใหม่หรือเครื่องที่รีเซ็ตแล้วซึ่งกู้คืนจากข้อมูลสำรองนั้นจะได้ข้อมูลกลับมา')
x('DATA_BACKUP_DESKTOP', 'ข้อมูลเหล่านี้เก็บอยู่ในโฟลเดอร์ของ {APP} ในคอมพิวเตอร์เครื่องนี้')
x('DATA_HOW', 'หากต้องการเก็บสำเนาไว้เอง หรือย้ายไปใช้อุปกรณ์อื่น: “ส่งออก” จะรวมทุกอย่างไว้ในไฟล์เดียว เพื่อเก็บไว้ที่ใดก็ได้ตามต้องการ (คลาวด์ ตัวอุปกรณ์ หรือในข้อความ) ส่วน “นำเข้า” บนอุปกรณ์เครื่องใดก็ได้ จะนำทุกอย่างกลับมา โดยแทนที่ข้อมูลที่มีอยู่')
x('DATA_EXPORT', 'ส่งออก')
x('DATA_IMPORT', 'นำเข้า')
x('DATA_EXPORT_READY', 'ข้อมูลสำรองพร้อมแล้ว ({0} ไฟล์): เลือกที่ที่จะเก็บไว้')
x('DATA_EXPORT_SAVED', 'บันทึกแล้ว ({0} ไฟล์): {1}')
x('DATA_EXPORT_FAILED', 'ไม่สามารถสร้างข้อมูลสำรองได้')
x('DATA_NOT_BACKUP', 'ไฟล์นี้ไม่ใช่ข้อมูลสำรองของ {APP} หรือไฟล์เสียหาย')
x('DATA_CANT_OPEN', 'ไม่สามารถเปิดไฟล์ได้')
x('DATA_CONFIRM', 'แทนที่ทุกอย่างใน {APP} บนอุปกรณ์นี้ด้วยข้อมูลสำรองจากวันที่ {0} ({1,plural, other{# หน้า}}) หรือไม่ ข้อมูลที่มีอยู่ตอนนี้จะหายไป: หากต้องการเก็บไว้ ให้ส่งออกก่อน')
x('DATA_REPLACE', 'แทนที่')
x('DATA_IMPORTED', 'นำเข้าแล้ว: ทุกอย่างกลับเป็นเหมือนวันที่ {0}')
x('DATA_IMPORT_FAILED', 'ไม่สามารถนำเข้าข้อมูลสำรองได้: ไม่มีอะไรถูกเปลี่ยนแปลง')
x('LICENCES', 'สัญญาอนุญาต')
x('LICENCE_FONTS', 'ฟอนต์')
x('LICENCE_LIBRARIES', 'ไลบรารี')
x('LICENCE_MISSING', 'ไม่มีสัญญาอนุญาตนี้ในแอป')
x('THEME_PAPER', 'กระดาษ')
x('THEME_WASHI', 'วาชิ')
x('THEME_NIGHT', 'กลางคืน')
x('THEME_MATCHA', 'มัทฉะ')
x('THEME_SAKURA', 'ซากุระ')
x('NOTE_FOLDER_BODY', 'โฟลเดอร์ · {0,plural, other{# แคนวาส}}')
x('NOTE_RENAME_FOLDER', 'เปลี่ยนชื่อโฟลเดอร์')
x('NOTE_RENAME_CANVAS', 'เปลี่ยนชื่อแคนวาส')
x('NOTE_DELETE_TITLE', 'ลบ “{0}” หรือไม่')
x('NOTE_DELETE_FOLDER', '{0,plural, other{แคนวาส # อัน}}ในโฟลเดอร์นี้ (รวมถึงโฟลเดอร์ย่อย) จะถูกลบไปด้วย การกระทำนี้เลิกทำไม่ได้')
x('NOTE_UNDONE', 'การกระทำนี้เลิกทำไม่ได้')
x('NOTE_PAGE', 'หน้า')
x('BACK', 'กลับ')
x('LIBRARY_TITLE', 'บทเรียน')
x('LIBRARY_CAPTION', 'อ่าน ซูม และเขียนลงไปได้: โน้ตของคุณจะอยู่บนหน้านั้น')
x('LIBRARY_BOOKS', 'บทเรียนฟรี')
x('LIBRARY_YOURS', 'เอกสารของคุณ')
x('LIBRARY_YOURS_EMPTY', 'PDF และรูปภาพที่คุณนำเข้ามา รวมถึงหน้าที่คุณสแกน จะแสดงที่นี่และในโน้ตของคุณ ให้อ่านและเขียนลงไปได้')
x('LIBRARY_FILES', 'จากไฟล์')
x('LIBRARY_PHOTOS', 'จากรูปภาพ')
x('LIBRARY_SCAN', 'สแกนหน้า')
x('LIBRARY_FOLDER', 'บทเรียน')
x('DOC_CANT_PICK', 'ไม่สามารถแสดงไฟล์ได้')
x('DOC_CANT_OPEN', 'ไม่สามารถเปิดเป็น PDF หรือรูปภาพได้')
x('DOC_NOT_HERE', 'ตอนนี้ PDF เปิดได้บน iPad และ Mac เท่านั้น')
x('DOC_IMPORTED', '“{0}” อยู่ในโน้ตของคุณแล้ว')
x('DOC_SCAN_NAME', 'สแกน {0}')
x('DOC_PHOTOS_NAME', 'รูปภาพ {0}')
x('DOC_SEARCH', 'ค้นหา')
x('DOC_SEARCH_HINT', 'คำที่ต้องการค้นหา')
x('DOC_SEARCHING', 'กำลังค้นหา…')
x('DOC_NO_MATCHES', 'ไม่พบ')
x('DOC_BEFORE', 'ก่อนหน้า')
x('DOC_NEXT', 'ถัดไป')
x('DOC_PAGE', 'หน้า')
x('DOC_TURN', 'หมุนหน้า')
x('DOC_TURN_FULL', 'หมุนหน้าในเอกสารนี้เพิ่มอีกไม่ได้แล้ว')
x('DOC_EXPORT', 'แชร์เป็น PDF')
x('DOC_EXPORT_FAILED', 'ไม่สามารถสร้าง PDF ได้')
x('DOC_EXPORTED', 'บันทึกแล้ว: {0}')
x('DAY_MON', 'จ')
x('DAY_TUE', 'อ')
x('DAY_WED', 'พ')
x('DAY_THU', 'พฤ')
x('DAY_FRI', 'ศ')
x('DAY_SAT', 'ส')
x('DAY_SUN', 'อา')
x('DATE', '{0} {1} {2}')
x('DATE_TIME', '{0} {1}')
x('MONTH_1', 'ม.ค.')
x('MONTH_2', 'ก.พ.')
x('MONTH_3', 'มี.ค.')
x('MONTH_4', 'เม.ย.')
x('MONTH_5', 'พ.ค.')
x('MONTH_6', 'มิ.ย.')
x('MONTH_7', 'ก.ค.')
x('MONTH_8', 'ส.ค.')
x('MONTH_9', 'ก.ย.')
x('MONTH_10', 'ต.ค.')
x('MONTH_11', 'พ.ย.')
x('MONTH_12', 'ธ.ค.')
