# Copyright (c) 2026 Borja Vazquez Cuesta. All rights reserved.

# Simplified Chinese for the drawing core's strings (the fourth language of
# Hanzi Learn!): x(id, text) rows, read by tools/strings/build.py fourth().
x('FINISH', '结束')
x('CLOSE', '关闭')
x('MORE_MENU', '更多')
x('READ_CLOSE_IN', '关闭（{0}）')
x('CANCEL', '取消')
x('DELETE', '删除')
x('SAVE', '保存')
x('RENAME', '重命名')
x('UNDO', '撤销')
x('REDO', '重做')
x('OF_N', '{0} / {1}')
x('TOOL_FINGER', '手指')
x('FINGER_ON', '用手指书写：双指移动页面')
x('FINGER_OFF', '用 Apple Pencil 书写：手指移动页面')
x('FINGER_OFF_ANDROID', '用触控笔书写：手指移动页面')
x('TOOL_DRAW', '画笔')
x('TOOL_MARK', '荧光笔')
x('TOOL_ERASE', '橡皮擦')
x('TOOL_LASSO', '套索')
x('TOOL_CLEAR', '清空页面')
x('TOOL_COLOR', '颜色')
x('TOOL_PAGE', '页面')
x('TOOL_SCREEN', '屏幕')
x('TOOL_PAPER', '纸张')
x('TOOL_ROTATE', '旋转')
x('TOOL_RESET', '重置视图')
x('MENU', '菜单')
x('PAPER_DOTS', '点阵')
x('PAPER_SQUARES', '方格')
x('PAPER_LINES', '横线')
x('PAPER_NONE', '空白')
x('SEL_CUT', '剪切')
x('SEL_COPY', '复制')
x('SEL_COPIED', '已复制')
x('SEL_DUPLICATE', '创建副本')
x('CTX_PASTE', '粘贴')
x('CTX_SELECT_ALL', '全选')
x('SIDE_NOTES', '笔记')
x('FOLDER', '文件夹')
x('CANVAS', '画布')
x('SETTINGS', '设置')
x('SETTINGS_THEME', '主题')
x('SETTINGS_LANGUAGE', '语言')
x('SETTINGS_PEN_WIDTH', '线条粗细')
x('SETTINGS_EVEN', '均匀')
x('SETTINGS_PRESSURE', '压感')
x('SETTINGS_PAPER', '横线与方格')
x('SETTINGS_UI_SIZE', '界面大小')
x('SIZE_SMALL', '小')
x('SIZE_MEDIUM', '中')
x('SIZE_LARGE', '大')
x('SETTINGS_ABOUT', '关于')
x('ABOUT_BUILT', '{APP} {0}，构建于{1}。')
x('RATE', '为 {APP} 评分')
x('TUTORIAL', '教程')
x('FAQ_CONTACT', '常见问题与联系')
x('FAQ_OPEN', '常见问题')
x('CONTACT_WRITE', '有疑问、想法或遇到问题？请写信给我们：')
x('DATA', '你的数据')
x('DATA_BACKUP_IOS', '开启 iCloud 云备份后（设置 › 你的名字 › iCloud › iCloud 云备份），这些数据也会包含在此设备的备份中：用该备份恢复此设备或设置新设备时，数据会随之恢复。')
x('DATA_BACKUP_ANDROID', '开启 Google 备份后（设置 › Google › 备份），这些数据也会包含在此设备的备份中：新设备或重置后的设备从该备份恢复时，即可找回这些数据。')
x('DATA_BACKUP_DESKTOP', '这些数据保存在此电脑上 {APP} 的文件夹中。')
x('DATA_HOW', '如需自己保留一份副本，或迁移到其他设备：“导出”会把所有内容存为一个文件，可保存在任何你喜欢的地方（云盘、本设备、一条消息）；在任意设备上“导入”即可恢复——并替换该设备上现有的内容。')
x('DATA_EXPORT', '导出')
x('DATA_IMPORT', '导入')
x('DATA_EXPORT_READY', '备份已准备好（{0}个文件）：请选择保存位置。')
x('DATA_EXPORT_SAVED', '已保存（{0}个文件）：{1}')
x('DATA_EXPORT_FAILED', '无法创建备份。')
x('DATA_NOT_BACKUP', '该文件不是 {APP} 的备份，或已损坏。')
x('DATA_CANT_OPEN', '无法打开该文件。')
x('DATA_CONFIRM', '要用这份来自{0}的备份（{1}页）替换此设备上 {APP} 中的全部内容吗？现有内容将会丢失：如需保留，请先导出。')
x('DATA_REPLACE', '替换')
x('DATA_IMPORTED', '已导入：一切已恢复到{0}时的状态。')
x('DATA_IMPORT_FAILED', '无法导入备份：未做任何更改。')
x('LICENCES', '许可协议')
x('LICENCE_FONTS', '字体')
x('LICENCE_LIBRARIES', '程序库')
x('LICENCE_MISSING', '应用中缺少此许可协议。')
x('THEME_PAPER', '纸')
x('THEME_WASHI', '和纸')
x('THEME_NIGHT', '夜间')
x('THEME_MATCHA', '抹茶')
x('THEME_SAKURA', '樱花')
x('NOTE_FOLDER_BODY', '文件夹，{0}个画布')
x('NOTE_RENAME_FOLDER', '重命名文件夹')
x('NOTE_RENAME_CANVAS', '重命名画布')
x('NOTE_DELETE_TITLE', '删除“{0}”？')
x('NOTE_DELETE_FOLDER', '其中的{0}个画布（以及所有文件夹）也会一并删除。此操作无法撤销。')
x('NOTE_UNDONE', '此操作无法撤销。')
x('NOTE_PAGE', '页面')
x('BACK', '返回')
x('LIBRARY_TITLE', '教材')
x('LIBRARY_CAPTION', '阅读、放大、在上面书写：你的笔记会留在页面上。')
x('LIBRARY_BOOKS', '免费课程')
x('LIBRARY_YOURS', '你的文档')
x('LIBRARY_YOURS_EMPTY', '你导入的 PDF 和图片，以及扫描的页面，会显示在这里和你的笔记中，供你阅读和书写。')
x('LIBRARY_FILES', '从文件导入')
x('LIBRARY_PHOTOS', '从照片导入')
x('LIBRARY_SCAN', '扫描页面')
x('LIBRARY_FOLDER', '教材')
x('DOC_CANT_PICK', '无法显示这些文件。')
x('DOC_CANT_OPEN', '无法以 PDF 或图片格式打开。')
x('DOC_NOT_HERE', '目前 PDF 只能在 iPad 和 Mac 上打开。')
x('DOC_IMPORTED', '“{0}”已加入你的笔记')
x('DOC_SCAN_NAME', '扫描 {0}')
x('DOC_PHOTOS_NAME', '照片 {0}')
x('DOC_SEARCH', '搜索')
x('DOC_SEARCH_HINT', '要查找的文字')
x('DOC_SEARCHING', '正在搜索…')
x('DOC_NO_MATCHES', '未找到')
x('DOC_BEFORE', '上一个')
x('DOC_NEXT', '下一个')
x('DOC_PAGE', '页码')
x('DOC_TURN', '旋转页面')
x('DOC_TURN_FULL', '此文档中无法再旋转更多页面。')
x('DOC_EXPORT', '以 PDF 分享')
x('DOC_EXPORT_FAILED', '无法生成 PDF。')
x('DOC_EXPORTED', '已保存：{0}')
x('DAY_MON', '一')
x('DAY_TUE', '二')
x('DAY_WED', '三')
x('DAY_THU', '四')
x('DAY_FRI', '五')
x('DAY_SAT', '六')
x('DAY_SUN', '日')
x('DATE', '{2}年{1}{0}日')
x('DATE_TIME', '{0} {1}')
x('MONTH_1', '1月')
x('MONTH_2', '2月')
x('MONTH_3', '3月')
x('MONTH_4', '4月')
x('MONTH_5', '5月')
x('MONTH_6', '6月')
x('MONTH_7', '7月')
x('MONTH_8', '8月')
x('MONTH_9', '9月')
x('MONTH_10', '10月')
x('MONTH_11', '11月')
x('MONTH_12', '12月')
