"""Write the hand-drawn Thai letters (letters.py) as KanjiVG-style XML for
Kana's bake (fude/study/chars/bake.c, fude_bake_kanjivg).

    python3 apps/thai/tools/strokes/compose.py [out.xml]

writes data/raw/th/thaivg.xml (git-ignored) by default: the app's 85 letters
(fude/lang/th/lang.c: the consonants, the vowels, the tone marks and signs, the
digits), in code point order, each one <kanji> with one <g> holding its
strokes in writing order. No kvg:type: Thai strokes are not CJK stroke types.
The output is deterministic.
"""

import os
import sys

sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import letters as L                                          # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", "..", "..", ".."))
OUT = os.path.join(ROOT, "data", "raw", "th", "thaivg.xml")

HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!--
Thai stroke order data in KanjiVG's format, for Kana's bake.
Generated by apps/thai/tools/strokes/compose.py from the hand-drawn letters in
apps/thai/tools/strokes/letters.py. Do not edit: regenerate.
Our own work; licence to be decided (see apps/thai/tools/strokes/README.md).
Centrelines in a 109 x 109 box, Y down; strokes numbered in writing order.
The school hand (round heads): a letter starts at its head.
-->
<kanjivg xmlns:kvg='http://kanjivg.tagaini.net'>
"""


def characters():
    """The letters in code point order."""
    return sorted(L.STROKES, key=ord)


def character_xml(ch, strokes):
    hexid = "%05x" % ord(ch)
    out = ['<kanji id="kvg:kanji_%s">' % hexid,
           '<g id="kvg:%s" kvg:element="%s">' % (hexid, ch)]
    for i, s in enumerate(strokes, 1):
        out.append('\t<path id="kvg:%s-s%d" d="%s"/>' % (hexid, i, s.d()))
    out.append("</g>")
    out.append("</kanji>")
    return "\n".join(out) + "\n"


def main(argv):
    out = argv[1] if len(argv) > 1 else OUT
    os.makedirs(os.path.dirname(out), exist_ok=True)
    n = total = 0
    tmp = out + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER)
        for ch in characters():
            strokes = L.strokes_of(ch)
            f.write(character_xml(ch, strokes))
            n += 1
            total += len(strokes)
        f.write("</kanjivg>\n")
    os.replace(tmp, out)
    print("compose: %d characters, %d strokes -> %s" % (n, total, out))


if __name__ == "__main__":
    main(sys.argv)
