# Copyright (c) 2026 Borja Vazquez Cuesta. All rights reserved.

# Korean for the study layer's strings (the fourth language of Hangul Learn!):
# x(id, text) rows, read by tools/strings/build.py fourth().
x('PREV', '이전')
x('NEXT', '다음')
x('NEXT_N', '다음 {0}')
x('REPLAY', '다시 보기')
x('STUDY', '학습하기')
x('STUDYING', '학습 중')
x('KNOWN', '익힘')
x('PRACTICE', '연습')
x('PRACTICE_N', '연습 {0}')
x('DONE', '완료')
x('ADD', '추가')
x('SELECT', '선택')
x('ALL', '전체')
x('NONE', '선택 해제')
x('CLEAR', '지우기')
x('SCORE', '채점')
x('FEWER', '줄이기')
x('MORE', '늘리기')
x('GUIDED', '가이드')
x('QUIT', '그만두기')
x('START_N', '시작 {0}')
x('EXAM', '시험')
x('STROKE_ORDER', '획순')
x('ON', '켬')
x('OFF', '끔')
x('RETRY', '다시 시도')
x('DOWNLOAD', '다운로드')
x('NO_MEANING', '(뜻 없음)')
x('STROKES_N', '{0}획')
x('CHARACTERS_N', '{0}자')
x('SESSIONS_N', '{0}회')
x('SAVED', '저장됨')
x('NOT_SAVED', '저장하지 못함')
x('SEL_CHECK', '검사')
x('CTX_PASTE_TEXT', '텍스트 붙여넣기')
x('CTX_SCAN', '사진 속 텍스트')
x('SCAN_TITLE', '사진 속 텍스트')
x('SCAN_CAMERA', '카메라')
x('SCAN_PHOTOS', '사진')
x('SCAN_WRITE_N', '{0}줄 쓰기')
x('SCAN_WRITE', '쓰기')
x('SCAN_HOLD', '고정')
x('SCAN_LIVE', '{0}줄이 보입니다. ‘고정’을 누르면 남길 수 있습니다')
x('SCAN_FOUND', '{0}줄을 찾았습니다. 뺄 줄을 탭하세요')
x('SCAN_FAILED', '사진을 읽지 못했습니다.')
x('SCAN_NO_CAMERA', '카메라를 열지 못했습니다.')
x('SCAN_CAMERA_DENIED', '{APP}에서 카메라를 사용할 수 없습니다. 설정 › {APP}에서 허용하세요.')
x('SCAN_MLKIT_OFF', '사진 속 텍스트는 Google ML Kit을 사용합니다. 설정에서 켜세요.')
x('SCAN_TRANSLATE', 'Google로 번역')
x('SCAN_TRANSLATE_GETTING', 'Google 번역 모델을 다운로드하는 중(각 약 30 MB)…')
x('SCAN_TRANSLATE_FAILED', '번역을 다운로드하지 못했습니다. 기기가 인터넷에 연결되어 있나요?')
x('SCAN_TRANSLATING', '번역 중…')
x('SCAN_TRANSLATION_NONE', '이 줄은 번역하지 못했습니다.')
x('SEL_TRANSLATION_NONE', '번역하지 못했습니다.')
x('SEL_TRANSLATE_MLKIT_OFF', '번역에는 Google ML Kit을 사용합니다. 설정에서 켜세요.')
x('TRANSLATOR_HINT', '단어나 문장')
x('TRANSLATOR_NONE', '번역하지 못했습니다.')
x('TRANSLATOR_NOTHING', '연습할 글자가 없습니다')
x('SEL_COPY_TEXT', '텍스트로 복사')
x('SEL_READING', '인식 중…')
x('NOTICE_COPIED_TEXT', '복사했습니다: {0}')
x('NOTICE_COPIED_N', '{0}자를 텍스트로 복사했습니다')
x('NOTICE_NOTHING_READ', '인식한 글자가 없습니다')
x('NOTICE_NO_TEXT', '클립보드에 텍스트가 없습니다')
x('NOTICE_LEFT_OUT', '{0}자를 뺐습니다. {APP}에 없는 글자입니다')
x('RETRY_WRONG', '틀린 문제 다시')
x('PRACTICE_WRONG', '틀린 글자 연습')
x('TYPE_YOUR_OWN', '직접 입력')
x('ALBUM_WEAKEST', '취약순')
x('ALBUM_RECENT', '최신순')
x('ALBUM_MOST', '횟수순')
x('WEAKEST_AGAIN', '취약한 글자 다시')
x('CHECK_TITLE', '검사')
x('CHECK_READING', '인식 중…')
x('CHECK_NOTHING', '인식할 것이 없습니다.')
x('CHECK_MEANT_OK', '쓰려던 말로 검사했습니다.')
x('CHECK_CANDIDATES', '선택한 부분과 닮은 글자입니다(가까운 순). 쓰려던 글자를 탭하세요.')
x('CHECK_NO_MATCH', '닮은 글자가 없습니다(획수가 비슷한 글자와 비교합니다).')
x('CHECK_MLKIT_N', 'ML Kit 인식: {0}자, 평균 {1}점. 글자를 탭하면 자세히 볼 수 있습니다.')
x('CHECK_MEANT_N', '쓰려던 말로 검사: {0}자, 평균 {1}점. 글자를 탭하면 자세히 볼 수 있습니다.')
x('CHECK_READ_N', '{0}자로 인식, 평균 {1}점. 글자를 탭하면 자세히 볼 수 있습니다.')
x('CHECK_MLKIT_TOO_MANY', 'ML Kit이 획수보다 많은 글자를 인식해서 {APP}에서 대신 인식했습니다.')
x('CHECK_TOO_FEW', '쓰려던 글자보다 획이 적어서 자유롭게 인식했습니다.')
x('WORD_TITLE', '‘{0}’ 글자가 들어간 내 단어')
x('WORD_FIELD_WORD', '단어(‘{0}’ 포함)')
x('WORD_FIELD_MEANING', '뜻(선택 사항)')
x('WORD_ERR_KANJI', '단어에 ‘{0}’ 글자가 들어가야 합니다')
x('SEL_SAVE_WORD', '단어 저장')
x('VOCAB', '단어장')
x('VOCAB_WORDS_N', '단어 {0}개')
x('VOCAB_LISTS_N', '목록 {0}개')
x('VOCAB_EMPTY', '아직 단어가 없습니다. 글자의 예시 단어, 예문, 사진, 올가미(‘단어 저장’)에서 저장하거나, ‘+ 단어’로 직접 입력하세요.')
x('VOCAB_LIST_EMPTY', '이 목록에는 아직 단어가 없습니다. ‘+ 단어’로 추가하거나, 단어 카드에서 이 목록을 체크하세요.')
x('VOCAB_SEARCH_NONE', '‘{0}’에 맞는 단어가 없습니다.')
x('VOCAB_ADD_WORD', '단어')
x('VOCAB_REVIEW_N', '복습 {0}')
x('VOCAB_RENAME_LIST', '목록 이름 바꾸기')
x('VOCAB_DELETE_LIST', '목록 삭제')
x('VOCAB_LIST_NAME_EMPTY', '목록 이름을 입력하세요')
x('VOCAB_LISTS_FULL', '더 이상 목록을 만들 수 없습니다')
x('VOCAB_LIST_DELETED', '‘{0}’ 목록을 삭제했습니다. 단어는 단어장에 남아 있습니다')
x('REVIEW_NEW', '신규')
x('REVIEW_DUE', '오늘 복습')
x('REVIEW_IN_N', '{0}일 후')
x('WORDEXAM_TITLE_OF', '단어 시험 · {0}')
x('WORDEXAM_INTRO', '단어마다 통째로, 보지 않고 쓰기: 한 칸에 한 글자')
x('WORDEXAM_BY', '출제 방식')
x('WORDEXAM_BY_MEANING', '뜻과 발음')
x('WORDEXAM_BY_EAR', '듣고 쓰기')
x('WORDEXAM_NONE', '여기에는 출제할 단어가 없습니다. 먼저 단어를 저장하세요')
x('WORDEXAM_PLAN', '여기 있는 단어 {1}개 중 {0}개, 무작위 순서')
x('WORDEXAM_RULE', '단어의 모든 글자가 바르게 인식되면 정답입니다. 복습 일정도 그에 따라 정해집니다.')
x('WORDEXAM_HEAR_AGAIN', '탭하면 다시 들을 수 있습니다')
x('WORDEXAM_THEN_NEXT', '한 칸에 한 글자씩 쓰고 ‘다음’')
x('WORDEXAM_THEN_FINISH', '한 칸에 한 글자씩 쓰고 ‘마치기’')
x('SAVE_LIST', '목록 저장')
x('VOCAB_LIST_SAVED', '‘{1}’ 이름으로 저장했습니다: {0}자, 단어장에 있습니다')
x('NOTE', '메모')
x('NOTE_TITLE', '‘{0}’에 대한 메모')
x('NOTE_PLACEHOLDER', '외우기 위한 이야기나 요령, 헷갈리는 글자…')
x('NOTE_DELETE', '메모 삭제')
x('WORD_FIELD_WRITTEN', '단어')
x('WORD_SAVE_TITLE', '단어장에 저장')
x('WORD_SAVED_TITLE', '단어장에 있음')
x('WORD_FOUND', '들어 있는 단어: 탭해서 저장')
x('WORD_LISTS', '목록')
x('WORD_NEW_LIST', '새 목록')
x('WORD_LIST_NAME', '목록 이름(3과, 음식…)')
x('WORD_REMOVE', '삭제')
x('WORD_ERR_EMPTY', '먼저 단어를 입력하세요')
x('WORD_ERR_SAVED', '이미 단어장에 있는 단어입니다')
x('WORD_TRANSLATE_EMPTY', '먼저 뜻을 영어로 입력하세요')
x('WORD_SENTENCE', '출처 문장')
x('VOCAB_SAVED', '‘{0}’ 단어를 단어장에 저장했습니다')
x('VOCAB_SAVED_IN', '‘{0}’ 단어를 단어장의 ‘{1}’ 목록에 저장했습니다')
x('VOCAB_REMOVED', '‘{0}’ 단어를 단어장에서 삭제했습니다')
x('VIEWER_ADD_WORDS', '단어 추가')
x('VIEWER_YOURS_N', '내 단어 {0}개')
x('VIEWER_ADD_HELP', '단어를 탭하면 내 단어에 추가하거나 뺄 수 있습니다.')
x('VIEWER_ADD_OTHER', '다른 단어가 있나요? ‘직접 입력’하세요.')
x('VIEWER_NO_MORE_WORDS', '이 글자의 사전 단어는 더 없습니다. ‘직접 입력’하세요.')
x('GRADE_N', '{0}학년')
x('GRADE_SECONDARY', '중고등학교')
x('GRADE_NAMES', '진메이요(인명용)')
x('WORDS', '단어')
x('VOCAB_LIST_N', '목록 {0}')
x('SHEET', '연습지')
x('SHEET_TITLE', '쓰기 연습')
x('SHEET_FAILED', '연습지를 만들지 못했습니다.')
x('SHEET_SAVED', '연습지를 저장했습니다: {0}')
x('SHEET_FIRST_N', '연습지 한 장에는 {0}자까지 들어갑니다. 처음 {0}자를 넣었습니다.')
x('EXAMPLE', '예문')
x('WORDS_EXAMPLES', '예문 {0}개')
x('WORDS_YOURS', '내 단어 {0}개')
x('NO_WORDS', '아직 단어가 없습니다. 추가해 보세요.')
x('BROWSE_DRAW', '손글씨')
x('BROWSE_PARTS', '부분')
x('SORT_DEFAULT', '기본')
x('SORT_STROKES', '획수')
x('SORT_MEANING', '뜻')
x('BROWSE_BEST', '쓴 글씨와 가장 닮은 글자: {0}')
x('BROWSE_PARTS_ONE', '고른 부분이 있는 글자 {0}자')
x('BROWSE_PARTS_MANY', '고른 부분이 모두 있는 글자 {0}자')
x('BROWSE_PARTS_HINT', '부분을 탭하세요. 모두 가진 글자만 남습니다(흐린 부분: 남은 글자 중 가진 것이 없음)')
x('BROWSE_DRAW_HINT', '펜으로 상자 안에 글자를 쓰세요. 한 획마다 목록의 순서가 바뀝니다')
x('SIDE_STUDY', '학습')
x('ALBUM', '앨범')
x('EXAMS', '시험')
x('STATISTICS', '통계')
x('SETTINGS_HANDWRITING', '필기 인식')
x('SETTINGS_MLKIT', 'Google ML Kit으로 인식')
x('MLKIT_UNAVAILABLE', '이 기기에서는 사용할 수 없습니다. {APP}에서 직접 손글씨를 인식합니다.')
x('MLKIT_OFF', '꺼짐: {APP}에서 직접 손글씨를 인식하며, Google로 아무것도 보내지 않습니다.')
x('REVIEWS', '복습')
x('REVIEWS_N', '복습 · {0}')
x('REVIEWS_NONE', '오늘은 복습할 것이 없습니다. 내일 다시 오거나, 더 많은 글자를 ‘학습 중’으로 표시하세요.')
x('LICENCE_DATA', '데이터')
x('LICENCE_MLKIT', 'ML Kit')
x('EXAM_SELECTION', '선택한 글자')
x('EXAM_WHAT', '출제 범위')
x('EXAM_HOW_MANY', '문제 수')
x('EXAM_NOTHING_STUDYING', '아직 ‘학습 중’으로 표시한 글자가 없습니다')
x('EXAM_NOTHING', '여기에는 아직 출제할 글자가 없습니다')
x('EXAM_MARK_HINT', '글자 보기 화면의 ‘학습하기’나 글자 목록의 선택 모드에서 글자를 표시하세요.')
x('EXAM_PLAN', '{2} {1}자 중 {0}자, 무작위 순서')
x('EXAM_RULE', '그 글자로 인식되면(상위 후보 3개 안) 정답이고, 점수는 얼마나 잘 썼는지를 나타냅니다.')
x('EXAM_MAX', '시험 한 번에 최대 {0}문제까지 출제합니다.')
x('EXAM_TITLE_SOURCE', '시험 · {0}')
x('EXAM_TAP_TO_LEAVE', '탭하면 출제에서 뺍니다')
x('EXAM_ONCE_EACH', '한 번씩, 보지 않고')
x('EXAM_THEN_FINISH', '한 번 쓰고 ‘마치기’')
x('EXAM_THEN_NEXT', '한 번 쓰고 ‘다음’')
x('EXAM_READING_ANSWERS', '답안을 인식하는 중… {0} / {1}')
x('EXAM_RESULT', '{1}문제 중 {0}문제 정답 · {2}점')
x('EXAM_PASSED', '합격')
x('EXAM_NOT_PASSED', '아직 불합격')
x('EXAM_READ_AS', '인식 결과')
x('STATS_OVERVIEW', '개요')
x('STATS_ACTIVITY', '활동')
x('STATS_SCORES', '연습 점수')
x('STATS_LEVELS', '레벨')
x('STATS_MISTAKES', '실수')
x('STATS_CHARACTERS', '글자')
x('STATS_WHEN', '연습하는 시간대')
x('MISTAKE_ORDER', '획순')
x('MISTAKE_DIRECTION', '방향')
x('MISTAKE_MISSING', '빠진 획')
x('MISTAKE_EXTRA', '남는 획')
x('MISTAKE_SHAPE', '모양')
x('DURATION_HM', '{0}시간 {1}분')
x('DURATION_M', '{0}분')
x('DURATION_S', '{0}초')
x('TILE_SESSIONS', '연습 횟수')
x('TILE_CHARACTERS', '연습한 글자')
x('TILE_SQUARES', '쓴 칸')
x('TILE_TIME', '쓴 시간')
x('TILE_DAYS', '활동한 날')
x('TILE_STREAK', '연속 일수')
x('TILE_BEST_STREAK', '최장 연속')
x('TILE_EXAMS', '본 시험')
x('TILE_PASSED', '합격한 시험')
x('TILE_ACCURACY', '시험 정답률')
x('TILE_STUDYING', '학습 중')
x('TILE_KNOWN', '익힘')
x('TILE_WORDS', '추가한 단어')
x('DAY_INITIAL_MON', '월')
x('DAY_INITIAL_WED', '수')
x('DAY_INITIAL_FRI', '금')
x('DAY_INITIAL_SUN', '일')
x('STATS_ACTIVITY_CAPTION', '최근 {0}주: 날마다 연습한 칸과 시험 답안')
x('STATS_NO_SCORES', '아직 연습 기록이 없습니다. 점수가 주별로 여기에 표시됩니다.')
x('STATS_SCORES_TREND', '최근 {0}일 {1}(그 전 {3}일 대비 {2}) · 전체 {4}')
x('STATS_SCORES_RECENT', '최근 {0}일 {1} · 전체 {2}')
x('STATS_SCORES_ALL', '전체 {0}')
x('STATS_SCORES_CAPTION', '최근 {0}주의 주별 평균 점수')
x('STATS_NO_EXAMS', '아직 시험 기록이 없습니다. 사이드 패널의 ‘시험’에서 시작하세요.')
x('STATS_EXAMS_LINE', '{0}회 응시, {1}회 합격 · {3}문제 중 {2}문제 정답 · {4}점')
x('STATS_EXAMS_CAPTION', '최근 {0}회: 막대는 정답 비율({1}%부터 합격), 점은 점수')
x('STATS_LEVEL_LINE', '익힘 {0}, 연습 {1} / {2}')
x('STATS_LEGEND_KNOWN', '익힘')
x('STATS_LEGEND_STUDYING', '학습 중')
x('STATS_LEGEND_PRACTISED', '연습함')
x('STATS_NO_PRACTICE', '아직 연습 기록이 없습니다.')
x('STATS_MISTAKES_CAPTION', '실수별로 나온 칸: 전체(연하게), 최근 {0}일(진하게)')
x('STATS_WEAKEST', '취약한 글자(최근 연습 기준)')
x('STATS_IMPROVED', '가장 향상된 글자(첫 연습부터 최근까지)')
x('STATS_TWICE', '글자를 두 번 연습하면 여기에 표시됩니다.')
x('STATS_BY_HOUR', '시간대별')
x('STATS_BY_DAY', '요일별')
x('STATS_SINCE', '{0}부터')
x('STATS_MARKS', '익힌 글자 추이')
x('STATS_MARKS_NOW', '익힘 {0} · 학습 중 {1}')
x('STATS_MARKS_RECENT', '최근 {1}일 동안 익힘 {0}')
x('STATS_MARKS_CAPTION', '최근 {0}주, 매주 마지막 시점 기준')
x('STATS_NO_MARKS', '아직 표시한 글자가 없습니다.')
x('ALBUM_EXAMS_COUNTS', '시험 {0}회, 합격 {1}회')
x('EXAM_KEPT', '{0} · {1}')
x('ALBUM_COUNTS', '연습한 글자 {0} · {1}')
x('ALBUM_SINCE', '{1}부터 {0}')
x('ALBUM_FIRST_BEST_LAST', '처음 {0}, 최고 {1}, 최근 {2}')
x('ALBUM_NO_SESSIONS', '연습 기록 없음')
x('ALBUM_ATTEMPT', '{0}번째 시도: {1}점. {2}')
x('PRACTICE_NOTHING', '아직 아무것도 쓰지 않았습니다. 펜으로 칸에 쓰세요')
x('PRACTICE_ALREADY_SAVED', '평균 {0}  (이미 저장됨)')
x('PRACTICE_FROM_MEMORY', '보지 않고: {0} · {1}')
x('PRACTICE_AVERAGE', '{1} 평균 {0} · {2}')
x('SQUARES_N', '{0}칸')
x('SET_DONE', '세트 완료')
x('SET_SUMMARY', '{1}자 중 {0}자 연습, 평균 {2}')
x('SET_NOTHING', '이 세트에서는 아무것도 연습하지 않았습니다')
x('SET_WEAK', '{1}점 미만 {0}자: ‘취약한 글자 다시’로 취약한 순서대로 연습합니다')
x('SET_ALL_GOOD', '이번에는 모두 잘했습니다')
x('PRACTICE_HEADER', '{0}   {1}')
x('PRACTICE_HEADER_LEVEL', '{0}   {1}   {2}')
x('PRACTICE_HISTORY', '{0}   최고 {1}   최근 {2}   처음 {3}')
x('NOT_PRACTISED', '아직 연습하지 않음')
x('WRITE_AGAIN', '{0} · 다시 써서 한 번 더 도전하세요')
x('GUIDE_WRONG_STROKE', '{0}번째 획입니다. {1}번째 획을 먼저 씁니다.')
x('GUIDE_BACKWARDS', '반대 방향입니다. {0}번째 획은 점에서 시작합니다.')
x('GUIDE_FOLLOW', '조금 다릅니다. 점에서부터 {0}번째 획을 따라 쓰세요.')
x('GUIDE_WATCH', '조금 다릅니다. {0}번째 획을 보고 나서 점에서부터 쓰세요.')
x('GUIDE_STEP1_DONE', '3단계 중 1단계 완료. 다음: 각 획의 시작점만')
x('GUIDE_STEP1', '3단계 중 1단계 · {1}획 중 {0}번째 획 따라 쓰기: 점에서 화살표 방향으로')
x('GUIDE_STEP2_DONE', '3단계 중 2단계 완료. 다음: 보지 않고')
x('GUIDE_STEP2', '3단계 중 2단계 · {1}획 중 {0}번째 획은 점에서 시작합니다')
x('GUIDE_STEP3', '3단계 중 3단계 · 보지 않고: 글자 전체, {0}')
x('SCORE_EMPTY', '빈칸')
x('SCORE_NO_REFERENCE', '이 글자의 견본이 없습니다')
x('SCORE_COUNT', '{0}, 정답은 {1}획')
x('SCORE_ORDER_SWAP', '획순: {0}번째 획을 {1}번째보다 먼저')
x('SCORE_ORDER_MISPLACED', '획순: {0}의 순서가 틀림')
x('SCORE_BACKWARDS', '{0}번째 획을 반대로 씀')
x('SCORE_BACKWARDS_MORE', '{0}번째 획 등을 반대로 씀')
x('SCORE_SHAPE', '{0}번째 획의 모양이 어긋남')
x('SCORE_EXCELLENT', '훌륭합니다')
x('SCORE_GOOD', '좋습니다')
x('SCORE_OK', '괜찮습니다. 계속 연습하세요')
x('OFFLINE_TITLE', '{APP}: 오프라인으로 작동하는 이유')
x('OFFLINE', '{APP}의 모든 기능은 기기 안에서 작동하도록 만들어졌습니다. 만들어야 할 계정도, 뒤에서 돌아가는 서버도 없습니다. 쓰고, 연습하고, 저장한 것은 모두 여기에 남고, 앱은 인터넷 연결이 있든 없든 어디서나 작동합니다.\\n\\n이는 의도한 선택입니다. 계정, 기기 간 동기화, 클라우드 백업 같은 온라인 기능에는 서버가 필요하고, 서버에는 앱이 존재하는 한 매달 비용이 듭니다. 그 비용을 감당하려면 학습 중에 집중을 깨뜨리는 광고로 화면을 채우고, 그것도 모자라 모두에게 월 구독료를 요청해야 합니다.\\n\\n{APP}의 개발과 유지 관리는 개인 개발자 한 명이 맡고 있으며, 앱은 스스로 비용을 감당해야 합니다. 광고도 구독도 없는 한 번의 구매가 가장 공정한 방법입니다. 한 번 결제하면 앱은 여러분의 것입니다.\\n\\n알아 두실 두 가지:\\n• 필기 인식, 텍스트 인식, 번역에는 기기에서 작동하는 Google 모델을 사용합니다. 한 번 다운로드하면 그 후에는 오프라인에서도 작동합니다.\\n• 학습 기록은 이 기기에만 저장됩니다. 가끔 설정 › 내 데이터에서 백업을 만들어 안전한 곳에 보관하세요.\\n\\n독립 소프트웨어를 응원해 주셔서 감사합니다.')
x('VOICE_BUTTON', '음성 설정')
x('VOICE_TITLE', '아직 소리 내어 읽어 줄 음성이 없습니다')
x('VOICE_OPEN', '설정 열기')
