# Simplified Chinese for the study layer's strings (the fourth language of
# Hanzi Learn!): x(id, text) rows, read by tools/strings/build.py fourth().
x('PREV', '上一个')
x('NEXT', '下一个')
x('NEXT_N', '下一步 {0}')
x('REPLAY', '重播')
x('STUDY', '学习')
x('STUDYING', '学习中')
x('KNOWN', '已掌握')
x('PRACTICE', '练习')
x('PRACTICE_N', '练习 {0}')
x('DONE', '完成')
x('ADD', '添加')
x('SELECT', '选择')
x('ALL', '全部')
x('NONE', '无')
x('CLEAR', '清除')
x('SCORE', '评分')
x('FEWER', '减少')
x('MORE', '增加')
x('GUIDED', '引导')
x('QUIT', '退出')
x('START_N', '开始 {0}')
x('EXAM', '测验')
x('STROKE_ORDER', '笔顺')
x('ON', '开')
x('OFF', '关')
x('RETRY', '重试')
x('DOWNLOAD', '下载')
x('NO_MEANING', '（无释义）')
x('STROKES_N', '{0}画')
x('CHARACTERS_N', '{0}个字')
x('SESSIONS_N', '{0}次')
x('SAVED', '已保存')
x('NOT_SAVED', '无法保存')
x('SEL_CHECK', '检查')
x('CTX_PASTE_TEXT', '粘贴文本')
x('CTX_SCAN', '照片文字')
x('SCAN_TITLE', '照片中的文字')
x('SCAN_CAMERA', '相机')
x('SCAN_PHOTOS', '照片')
x('SCAN_WRITE_N', '写下{0}行')
x('SCAN_WRITE', '写下')
x('SCAN_HOLD', '定格')
x('SCAN_LIVE', '画面中有{0}行：点“定格”即可保留')
x('SCAN_FOUND', '找到{0}行：轻点某一行可将其排除')
x('SCAN_FAILED', '无法读取这张照片。')
x('SCAN_NO_CAMERA', '无法打开相机。')
x('SCAN_CAMERA_DENIED', '{APP} 无权使用相机：请在“设置 › {APP}”中允许。')
x('SCAN_MLKIT_OFF', '照片文字功能使用 Google ML Kit：请在设置中开启。')
x('SCAN_TRANSLATE', '用 Google 翻译')
x('SCAN_TRANSLATE_GETTING', '正在下载 Google 的翻译模型（每个约 30 MB）…')
x('SCAN_TRANSLATE_FAILED', '无法下载翻译模型。设备是否已联网？')
x('SCAN_TRANSLATING', '正在翻译…')
x('SCAN_TRANSLATION_NONE', '这一行无法翻译。')
x('SEL_TRANSLATION_NONE', '无法翻译。')
x('SEL_TRANSLATE_MLKIT_OFF', '翻译功能使用 Google ML Kit：请在设置中开启。')
x('TRANSLATOR_HINT', '一个词或一句话')
x('TRANSLATOR_NONE', '无法翻译。')
x('TRANSLATOR_NOTHING', '其中没有可练习的字')
x('SEL_COPY_TEXT', '复制为文本')
x('SEL_READING', '正在识别…')
x('NOTICE_COPIED_TEXT', '已复制：{0}')
x('NOTICE_COPIED_N', '已将{0}个字复制为文本')
x('NOTICE_NOTHING_READ', '那里没有识别出任何内容')
x('NOTICE_NO_TEXT', '剪贴板中没有文本')
x('NOTICE_LEFT_OUT', '已略过{0}个字：{APP} 中没有收录')
x('RETRY_WRONG', '重做错题')
x('PRACTICE_WRONG', '练习错题')
x('TYPE_YOUR_OWN', '自己输入')
x('ALBUM_WEAKEST', '最薄弱')
x('ALBUM_RECENT', '最近')
x('ALBUM_MOST', '练习最多')
x('WEAKEST_AGAIN', '再练薄弱字')
x('CHECK_TITLE', '检查')
x('CHECK_READING', '正在识别…')
x('CHECK_NOTHING', '这里没有可识别的内容。')
x('CHECK_MEANT_OK', '已按你想写的内容检查。')
x('CHECK_CANDIDATES', '所选内容看起来像这些字，最相似的排在前面。轻点你想写的那个。')
x('CHECK_NO_MATCH', '没有与之相似的字（只与笔画数相近的字进行比较）。')
x('CHECK_MLKIT_N', '由 ML Kit 识别：{0}个字，平均{1}分。轻点一个字可仔细查看。')
x('CHECK_MEANT_N', '已按你想写的内容检查：{0}个字，平均{1}分。轻点一个字可仔细查看。')
x('CHECK_READ_N', '识别为{0}个字，平均{1}分。轻点一个字可仔细查看。')
x('CHECK_MLKIT_TOO_MANY', 'ML Kit 识别出的字数多于笔画数：改由 {APP} 识别。')
x('CHECK_TOO_FEW', '笔画数少于你想写的字：改为自由识别。')
x('WORD_TITLE', '含“{0}”的词语')
x('WORD_FIELD_WORD', '词语（包含“{0}”）')
x('WORD_FIELD_MEANING', '释义（可选）')
x('WORD_ERR_KANJI', '词语中必须包含“{0}”')
x('SEL_SAVE_WORD', '保存词语')
x('VOCAB', '生词本')
x('VOCAB_WORDS_N', '{0}个词语')
x('VOCAB_LISTS_N', '{0}个列表')
x('VOCAB_EMPTY', '还没有词语。可以从汉字的例词、例句、照片或套索（保存词语）中保存，也可以用“+ 词语”自己输入。')
x('VOCAB_LIST_EMPTY', '这个列表还没有词语。用“+ 词语”添加，或在词语卡片上勾选这个列表。')
x('VOCAB_SEARCH_NONE', '没有与“{0}”匹配的词语。')
x('VOCAB_ADD_WORD', '词语')
x('VOCAB_REVIEW_N', '复习 {0}')
x('VOCAB_RENAME_LIST', '重命名列表')
x('VOCAB_DELETE_LIST', '删除列表')
x('VOCAB_LIST_NAME_EMPTY', '请为列表命名')
x('VOCAB_LISTS_FULL', '列表数量已达上限')
x('VOCAB_LIST_DELETED', '已删除“{0}”：其中的词语仍保留在你的生词本中')
x('REVIEW_NEW', '新')
x('REVIEW_DUE', '待复习')
x('REVIEW_IN_N', '{0}天后')
x('WORDEXAM_TITLE_OF', '词语测验 · {0}')
x('WORDEXAM_INTRO', '凭记忆写出完整的词语：一格一个字')
x('WORDEXAM_BY', '出题方式')
x('WORDEXAM_BY_MEANING', '释义和读音')
x('WORDEXAM_BY_EAR', '听音')
x('WORDEXAM_NONE', '这里没有可出题的词语：请先保存一些')
x('WORDEXAM_PLAN', '从这里的{1}个词语中随机抽取{0}个')
x('WORDEXAM_RULE', '词语中的每个字都识别正确才算对。复习计划会随之更新。')
x('WORDEXAM_HEAR_AGAIN', '轻点可再听一遍')
x('WORDEXAM_THEN_NEXT', '一格一个字，然后点“下一个”')
x('WORDEXAM_THEN_FINISH', '一格一个字，然后点“结束”')
x('SAVE_LIST', '存为列表')
x('VOCAB_LIST_SAVED', '已存为“{1}”：{0}个字，在你的生词本中')
x('NOTE', '备注')
x('NOTE_TITLE', '你对“{0}”的备注')
x('NOTE_PLACEHOLDER', '帮你记住它的故事或窍门、容易与它混淆的字…')
x('NOTE_DELETE', '删除备注')
x('WORD_FIELD_WRITTEN', '词语')
x('WORD_SAVE_TITLE', '保存到你的生词本')
x('WORD_SAVED_TITLE', '已在你的生词本中')
x('WORD_FOUND', '其中的词语：轻点即可保存')
x('WORD_LISTS', '列表')
x('WORD_NEW_LIST', '新建列表')
x('WORD_LIST_NAME', '列表名称（第3课、食物…）')
x('WORD_REMOVE', '移除')
x('WORD_ERR_EMPTY', '请先输入词语')
x('WORD_ERR_SAVED', '这个词语已在你的生词本中')
x('WORD_TRANSLATE_EMPTY', '请先用英文输入释义')
x('WORD_SENTENCE', '出自句子')
x('VOCAB_SAVED', '“{0}”已加入你的生词本')
x('VOCAB_SAVED_IN', '“{0}”已加入你的生词本，位于“{1}”')
x('VOCAB_REMOVED', '“{0}”已移出你的生词本')
x('VIEWER_ADD_WORDS', '添加词语')
x('VIEWER_YOURS_N', '你的词语：{0}')
x('VIEWER_ADD_HELP', '轻点词语可将其加入你的词语，或从中移除。')
x('VIEWER_ADD_OTHER', '想要别的词语？请“自己输入”。')
x('VIEWER_NO_MORE_WORDS', '词典中没有这个字的更多词语了：请“自己输入”。')
x('GRADE_N', '{0}年级')
x('GRADE_SECONDARY', '中学')
x('GRADE_NAMES', '人名用汉字')
x('WORDS', '词语')
x('VOCAB_LIST_N', '列表{0}')
x('SHEET', '字帖')
x('SHEET_TITLE', '书写练习')
x('SHEET_FAILED', '无法生成字帖。')
x('SHEET_SAVED', '字帖已保存：{0}')
x('SHEET_FIRST_N', '一张字帖最多可放{0}个字：已放入前{0}个。')
x('EXAMPLE', '例句')
x('WORDS_EXAMPLES', '例词{0}个')
x('WORDS_YOURS', '你的{0}个')
x('NO_WORDS', '还没有词语：点“添加”加一些吧。')
x('BROWSE_DRAW', '手写')
x('BROWSE_PARTS', '部件')
x('SORT_DEFAULT', '默认')
x('SORT_STROKES', '笔画')
x('SORT_MEANING', '释义')
x('BROWSE_BEST', '与你手写最接近的字：{0}')
x('BROWSE_PARTS_ONE', '含所选部件的字：{0}个')
x('BROWSE_PARTS_MANY', '含所选部件的字：{0}个')
x('BROWSE_PARTS_HINT', '轻点部件：只保留包含全部所选部件的字（变暗的部件：剩下的字都不含）')
x('BROWSE_DRAW_HINT', '用笔在框中写一个字：每写一画，列表都会重新排序')
x('SIDE_STUDY', '学习')
x('ALBUM', '作品集')
x('EXAMS', '测验')
x('STATISTICS', '统计')
x('SETTINGS_HANDWRITING', '手写识别')
x('SETTINGS_MLKIT', '用 Google ML Kit 识别')
x('MLKIT_UNAVAILABLE', '此设备不支持：{APP} 会自行识别手写。')
x('MLKIT_OFF', '已关闭：{APP} 自行识别手写，不会向 Google 发送任何内容。')
x('REVIEWS', '复习')
x('REVIEWS_N', '复习 · {0}')
x('REVIEWS_NONE', '今天没有要复习的内容：明天再来，或把更多字标记为“学习中”。')
x('LICENCE_DATA', '数据')
x('LICENCE_MLKIT', 'ML Kit')
x('EXAM_SELECTION', '所选的字')
x('EXAM_WHAT', '出题范围')
x('EXAM_HOW_MANY', '题数')
x('EXAM_NOTHING_STUDYING', '还没有标记为“学习中”的字')
x('EXAM_NOTHING', '这里还没有可出题的字')
x('EXAM_MARK_HINT', '可在查看汉字时点“学习”，或在汉字列表的“选择”模式中标记。')
x('EXAM_PLAN', '从{2}的{1}个字中随机抽取{0}个')
x('EXAM_RULE', '识别为该字（在前三个候选之内）即为正确；分数取决于书写质量。')
x('EXAM_MAX', '一次测验最多{0}题。')
x('EXAM_TITLE_SOURCE', '测验 · {0}')
x('EXAM_TAP_TO_LEAVE', '轻点某个字可将其排除')
x('EXAM_ONCE_EACH', '每个字写一次，凭记忆')
x('EXAM_THEN_FINISH', '写一次，然后点“结束”')
x('EXAM_THEN_NEXT', '写一次，然后点“下一个”')
x('EXAM_READING_ANSWERS', '正在识别你的答案… {0} / {1}')
x('EXAM_RESULT', '{1}题中答对{0}题 · {2}分')
x('EXAM_PASSED', '通过')
x('EXAM_NOT_PASSED', '尚未通过')
x('EXAM_READ_AS', '识别为')
x('STATS_OVERVIEW', '概览')
x('STATS_ACTIVITY', '活动')
x('STATS_SCORES', '练习分数')
x('STATS_LEVELS', '等级')
x('STATS_MISTAKES', '错误')
x('STATS_CHARACTERS', '汉字')
x('STATS_WHEN', '练习时段')
x('MISTAKE_ORDER', '笔顺')
x('MISTAKE_DIRECTION', '方向')
x('MISTAKE_MISSING', '缺少笔画')
x('MISTAKE_EXTRA', '多余笔画')
x('MISTAKE_SHAPE', '形状')
x('DURATION_HM', '{0}小时{1}分钟')
x('DURATION_M', '{0}分钟')
x('DURATION_S', '{0}秒')
x('TILE_SESSIONS', '练习次数')
x('TILE_CHARACTERS', '已练习的字')
x('TILE_SQUARES', '已写格数')
x('TILE_TIME', '书写时长')
x('TILE_DAYS', '活跃天数')
x('TILE_STREAK', '连续天数')
x('TILE_BEST_STREAK', '最长连续')
x('TILE_EXAMS', '参加的测验')
x('TILE_PASSED', '通过的测验')
x('TILE_ACCURACY', '测验正确率')
x('TILE_STUDYING', '学习中')
x('TILE_KNOWN', '已掌握')
x('TILE_WORDS', '添加的词语')
x('DAY_INITIAL_MON', '一')
x('DAY_INITIAL_WED', '三')
x('DAY_INITIAL_FRI', '五')
x('DAY_INITIAL_SUN', '日')
x('STATS_ACTIVITY_CAPTION', '最近{0}周：每天练习的格数和测验答题数')
x('STATS_NO_SCORES', '还没有练习：分数会按周显示在这里。')
x('STATS_SCORES_TREND', '最近{0}天 {1}（较之前{3}天 {2}）· 全部时间 {4}')
x('STATS_SCORES_RECENT', '最近{0}天 {1} · 全部时间 {2}')
x('STATS_SCORES_ALL', '全部时间 {0}')
x('STATS_SCORES_CAPTION', '最近{0}周每周的平均分')
x('STATS_NO_EXAMS', '还没有测验：在侧边栏的“测验”中开始。')
x('STATS_EXAMS_LINE', '参加{0}次，通过{1}次 · {3}题中答对{2}题 · {4}分')
x('STATS_EXAMS_CAPTION', '最近{0}次：柱为正确率（{1}% 即通过）；点为分数')
x('STATS_LEVEL_LINE', '已掌握{0}，已练习{1} / {2}')
x('STATS_LEGEND_KNOWN', '已掌握')
x('STATS_LEGEND_STUDYING', '学习中')
x('STATS_LEGEND_PRACTISED', '已练习')
x('STATS_NO_PRACTICE', '还没有练习。')
x('STATS_MISTAKES_CAPTION', '出现各类错误的格数：全部时间（浅色），最近{0}天（深色）')
x('STATS_WEAKEST', '最薄弱（最近一次练习）')
x('STATS_IMPROVED', '进步最大（从第一次到最近一次）')
x('STATS_TWICE', '一个字练习两次后会显示在这里。')
x('STATS_BY_HOUR', '按一天中的时段')
x('STATS_BY_DAY', '按星期几')
x('STATS_SINCE', '自{0}起')
x('STATS_MARKS', '已掌握的变化')
x('STATS_MARKS_NOW', '已掌握{0}，学习中{1}')
x('STATS_MARKS_RECENT', '最近{1}天掌握了{0}个')
x('STATS_MARKS_CAPTION', '最近{0}周，每周结束时')
x('STATS_NO_MARKS', '还没有任何标记。')
x('ALBUM_EXAMS_COUNTS', '测验{0}次，通过{1}次')
x('EXAM_KEPT', '{0} · {1}')
x('ALBUM_COUNTS', '练习了{0}，共{1}')
x('ALBUM_SINCE', '自{1}起共{0}')
x('ALBUM_FIRST_BEST_LAST', '首次 {0}，最佳 {1}，最近 {2}')
x('ALBUM_NO_SESSIONS', '没有练习记录')
x('ALBUM_ATTEMPT', '第{0}次：{1}分。{2}')
x('PRACTICE_NOTHING', '还没有写任何内容：用笔在格子里书写')
x('PRACTICE_ALREADY_SAVED', '平均 {0}（已保存）')
x('PRACTICE_FROM_MEMORY', '凭记忆：{0} · {1}')
x('PRACTICE_AVERAGE', '{1}平均 {0} · {2}')
x('SQUARES_N', '{0}格')
x('SET_DONE', '本组完成')
x('SET_SUMMARY', '{1}个中练习了{0}个，平均 {2}')
x('SET_NOTHING', '本组没有练习任何字')
x('SET_WEAK', '{0}个低于{1}分：“再练薄弱字”会从最薄弱的开始练习')
x('SET_ALL_GOOD', '这一轮都很好')
x('PRACTICE_HEADER', '{0}　{1}')
x('PRACTICE_HEADER_LEVEL', '{0}　{1}　{2}')
x('PRACTICE_HISTORY', '{0}　最佳 {1}　最近 {2}　首次 {3}')
x('NOT_PRACTISED', '尚未练习')
x('WRITE_AGAIN', '{0} · 再写一次可重新尝试')
x('GUIDE_WRONG_STROKE', '这是第{0}画。应先写第{1}画。')
x('GUIDE_BACKWARDS', '方向反了：第{0}画从圆点开始。')
x('GUIDE_FOLLOW', '差一点：从圆点开始描第{0}画。')
x('GUIDE_WATCH', '差一点：先看第{0}画怎么写，再从圆点开始写。')
x('GUIDE_STEP1_DONE', '第1/3步完成。接下来：只显示每一画的起点')
x('GUIDE_STEP1', '第1/3步 · 描第{0}画（共{1}画）：从圆点开始，沿箭头方向')
x('GUIDE_STEP2_DONE', '第2/3步完成。接下来：凭记忆书写')
x('GUIDE_STEP2', '第2/3步 · 第{0}画（共{1}画）从圆点开始')
x('GUIDE_STEP3', '第3/3步 · 凭记忆写出整个字（{0}）')
x('SCORE_EMPTY', '空白')
x('SCORE_NO_REFERENCE', '这个字没有参考字形')
x('SCORE_COUNT', '{0}，应为{1}画')
x('SCORE_ORDER_SWAP', '笔顺：第{0}画应在第{1}画之前')
x('SCORE_ORDER_MISPLACED', '笔顺：{0}位置不对')
x('SCORE_BACKWARDS', '第{0}画方向反了')
x('SCORE_BACKWARDS_MORE', '第{0}画等方向反了')
x('SCORE_SHAPE', '第{0}画形状不对')
x('SCORE_EXCELLENT', '优秀')
x('SCORE_GOOD', '良好')
x('SCORE_OK', '还行，继续练习')
x('OFFLINE_TITLE', '为什么 {APP} 可以离线使用')
x('OFFLINE', '{APP} 的设计初衷是完全在你的设备上运行。无需注册账户，背后也没有服务器：你书写、练习和保存的内容都留在这里，无论有没有网络，这款应用随处都能使用。\\n\\n这是有意为之的选择。账户、设备间同步、云备份等在线功能都需要服务器，而只要应用还在，服务器每个月都要花钱。要支付这些费用，就得在你的学习过程中塞满打断专注的广告，还要再向每个人收取月度订阅费。\\n\\n{APP} 由一位独立开发者独自开发和维护，必须自给自足。一次性购买、没有广告也没有订阅，是最公平的方式：只需付费一次，应用就归你所有。\\n\\n有两点需要注意：\\n• 手写识别、文字识别和翻译使用的是在你设备上运行的 Google 模型。它们只需下载一次，之后也能离线使用。\\n• 你的学习进度只保存在这台设备上。请不时在“设置 › 你的数据”中备份一下，并把备份存放在安全的地方。\\n\\n感谢你支持独立软件。')
x('VOICE_BUTTON', '设置语音')
x('VOICE_TITLE', '还没有可用于朗读的语音')
x('VOICE_OPEN', '打开设置')
