# A study app's UI strings: the study layer's (fude/study), read after the
# core's (tools/strings/build.py) and before the language's (fude/lang/<code>/
# strings.py, which has the ones that name the language). {APP} is the app's
# name (its src/version.h).
#
#   t('ID', English, Spanish, Portuguese (Brazil), Japanese, French)

# --- common words ---------------------------------------------------------------
t('PREV', 'Prev', 'Anterior', 'Anterior', '前へ', 'Précédent')
t('NEXT', 'Next', 'Siguiente', 'Próximo', '次へ', 'Suivant')
t('NEXT_N', 'Next {0}', 'Siguiente {0}', 'Próximo {0}', '次へ {0}', 'Suivant {0}')
t('REPLAY', 'Replay', 'Repetir', 'Repetir', 'もう一度', 'Rejouer')
t('STUDY', 'Study', 'Estudiar', 'Estudar', '学習する', 'Étudier')
t('STUDYING', 'Studying', 'Estudiando', 'Estudando', '学習中', 'En cours')
t('KNOWN', 'Known', 'Dominado', 'Dominado', '習得済み', 'Acquis')
t('PRACTICE', 'Practice', 'Practicar', 'Praticar', '練習', 'S’entraîner')
t('PRACTICE_N', 'Practice {0}', 'Practicar {0}', 'Praticar {0}', '練習 {0}', 'S’entraîner {0}')
t('DONE', 'Done', 'Listo', 'Pronto', '完了', 'Terminé')
t('ADD', 'Add', 'Añadir', 'Adicionar', '追加', 'Ajouter')
t('SELECT', 'Select', 'Seleccionar', 'Selecionar', '選択', 'Sélectionner')
t('ALL', 'All', 'Todos', 'Todos', 'すべて', 'Tous')
t('NONE', 'None', 'Ninguno', 'Nenhum', 'なし', 'Aucun')
t('CLEAR', 'Clear', 'Borrar', 'Limpar', '消去', 'Effacer')
t('SCORE', 'Score', 'Puntuar', 'Avaliar', '採点', 'Noter')
t('FEWER', 'Fewer', 'Menos', 'Menos', '減らす', 'Moins')
t('MORE', 'More', 'Más', 'Mais', '増やす', 'Plus')
t('GUIDED', 'Guided', 'Guiado', 'Guiado', 'ガイド', 'Guidé')
t('QUIT', 'Quit', 'Salir', 'Sair', 'やめる', 'Quitter')
t('START_N', 'Start {0}', 'Empezar {0}', 'Começar {0}', '開始 {0}', 'Commencer {0}')
t('EXAM', 'Exam', 'Examen', 'Teste', 'テスト', 'Examen')
t('STROKE_ORDER', 'Stroke order', 'Orden de trazos', 'Ordem dos traços', '書き順', 'Ordre des traits')
t('ON', 'On', 'Sí', 'Sim', 'オン', 'Oui')
t('OFF', 'Off', 'No', 'Não', 'オフ', 'Non')
t('RETRY', 'Retry', 'Reintentar', 'Tentar de novo', '再試行', 'Réessayer')
t('DOWNLOAD', 'Download', 'Descargar', 'Baixar', 'ダウンロード', 'Télécharger')
t('NO_MEANING', '(no meaning listed)', '(sin significado)', '(sem significado)', '（意味なし）', '(pas de sens)')
t('STROKES_N', P('# stroke', '# strokes'), P('# trazo', '# trazos'), P('# traço', '# traços'), '{0}画', P('# trait', '# traits'))
t('CHARACTERS_N', P('# character', '# characters'), P('# carácter', '# caracteres'), P('# caractere', '# caracteres'), '{0}字', P('# caractère', '# caractères'))
t('SESSIONS_N', P('# session', '# sessions'), P('# sesión', '# sesiones'), P('# sessão', '# sessões'), '{0}回', P('# séance', '# séances'))
t('SAVED', 'saved', 'guardado', 'salvo', '保存済み', 'enregistré')
t('NOT_SAVED', 'COULD NOT SAVE', 'NO SE PUDO GUARDAR', 'NÃO FOI POSSÍVEL SALVAR', '保存できませんでした', 'ENREGISTREMENT IMPOSSIBLE')

# --- the canvas's bar and panels (the tools' names are hidden behind icons) ---------------
t('SEL_CHECK', 'Check', 'Revisar', 'Verificar', 'チェック', 'Vérifier')
t('CTX_PASTE_TEXT', 'Paste text', 'Pegar texto', 'Colar texto', 'テキストを貼り付け', 'Coller le texte')
t('CTX_SCAN', 'Text from photo', 'Texto de foto', 'Texto de foto', '写真の文字', 'Texte d’une photo')
t('SCAN_TITLE', 'Text from a photo', 'Texto de una foto', 'Texto de uma foto', '写真の文字', 'Texte d’une photo')
t('SCAN_CAMERA', 'Camera', 'Cámara', 'Câmera', 'カメラ', 'Appareil photo')
t('SCAN_PHOTOS', 'Photos', 'Fotos', 'Fotos', '写真', 'Photos')
t('SCAN_WRITE_N', '{0,plural, one{Write # line} other{Write # lines}}', '{0,plural, one{Escribir # línea} other{Escribir # líneas}}', '{0,plural, one{Escrever # linha} other{Escrever # linhas}}', '{0}行を書く', '{0,plural, one{Écrire # ligne} other{Écrire # lignes}}')
t('SCAN_WRITE', 'Write', 'Escribir', 'Escrever', '書く', 'Écrire')
t('SCAN_HOLD', 'Hold', 'Congelar', 'Congelar', '固定', 'Figer')
t('SCAN_LIVE', '{0,plural, one{# line in view: Hold to keep it} other{# lines in view: Hold to keep them}}', '{0,plural, one{# línea a la vista: Congelar para quedártela} other{# líneas a la vista: Congelar para quedártelas}}', '{0,plural, one{# linha à vista: Congelar para mantê-la} other{# linhas à vista: Congelar para mantê-las}}', '{0}行が見えています。「固定」で残せます', '{0,plural, one{# ligne visible : Figer pour la garder} other{# lignes visibles : Figer pour les garder}}')
t('SCAN_FOUND', '{0,plural, one{# line found: tap it to leave it out} other{# lines found: tap one to leave it out}}', '{0,plural, one{# línea encontrada: tócala para dejarla fuera} other{# líneas encontradas: toca una para dejarla fuera}}', '{0,plural, one{# linha encontrada: toque nela para deixá-la de fora} other{# linhas encontradas: toque em uma para deixá-la de fora}}', '{0}行見つかりました。タップすると外せます', '{0,plural, one{# ligne trouvée : touchez-la pour l’exclure} other{# lignes trouvées : touchez-en une pour l’exclure}}')
t('SCAN_FAILED', 'The photo could not be read.', 'No se pudo leer la foto.', 'Não foi possível ler a foto.', '写真を読み取れませんでした。', 'La photo n’a pas pu être lue.')
t('SCAN_NO_CAMERA', 'The camera could not be opened.', 'No se pudo abrir la cámara.', 'Não foi possível abrir a câmera.', 'カメラを開けませんでした。', 'L’appareil photo n’a pas pu être ouvert.')
t('SCAN_CAMERA_DENIED', '{APP} may not use the camera: allow it in Settings › {APP}.', '{APP} no puede usar la cámara: permítelo en Ajustes › {APP}.', 'O {APP} não pode usar a câmera: permita em Ajustes › {APP}.', 'カメラが許可されていません。設定 › {APP} で許可してください。', '{APP} ne peut pas utiliser l’appareil photo : autorisez-le dans Réglages › {APP}.')
t('SCAN_MLKIT_OFF', 'Text from photos uses Google ML Kit: turn it on in Settings.', 'El texto de fotos usa Google ML Kit: actívalo en Ajustes.', 'O texto de fotos usa o Google ML Kit: ative-o em Ajustes.', '写真の文字はGoogle ML Kitを使います。設定でオンにしてください。', 'Le texte des photos utilise Google ML Kit : activez-le dans les Réglages.')

# Translate with Google (translate.h): Google asks for this label on the button.
t('SCAN_TRANSLATE', 'Translate with Google', 'Traducir con Google', 'Traduzir com o Google', 'Googleで翻訳', 'Traduire avec Google')
t('SCAN_TRANSLATE_GETTING', 'Downloading Google’s translation models (about 30 MB each)…', 'Descargando los modelos de traducción de Google (unos 30 MB cada uno)…', 'Baixando os modelos de tradução do Google (cerca de 30 MB cada)…', 'Googleの翻訳モデルをダウンロード中（各約30 MB）…', 'Téléchargement des modèles de traduction de Google (environ 30 Mo chacun)…')
t('SCAN_TRANSLATE_FAILED', 'The translation could not be downloaded. Is the device online?', 'No se pudo descargar la traducción. ¿Hay conexión?', 'Não foi possível baixar a tradução. O dispositivo está conectado?', '翻訳をダウンロードできませんでした。ネットに接続されていますか？', 'La traduction n’a pas pu être téléchargée. L’appareil est-il connecté ?')
t('SCAN_TRANSLATING', 'Translating…', 'Traduciendo…', 'Traduzindo…', '翻訳中…', 'Traduction…')
t('SCAN_TRANSLATION_NONE', 'This line could not be translated.', 'No se pudo traducir esta línea.', 'Não foi possível traduzir esta linha.', 'この行は翻訳できませんでした。', 'Cette ligne n’a pas pu être traduite.')
t('SEL_TRANSLATION_NONE', 'It could not be translated.', 'No se pudo traducir.', 'Não foi possível traduzir.', '翻訳できませんでした。', 'La traduction a échoué.')
t('SEL_TRANSLATE_MLKIT_OFF', 'Translating uses Google ML Kit: turn it on in Settings.', 'La traducción usa Google ML Kit: actívalo en Ajustes.', 'A tradução usa o Google ML Kit: ative-o em Ajustes.', '翻訳はGoogle ML Kitを使います。設定でオンにしてください。', 'La traduction utilise Google ML Kit : activez-le dans les Réglages.')

# Into the language taught (translator.h): the Vocabulary's Translate with Google, from the reader's language
# (its title and how-to: the language's strings).
t('TRANSLATOR_HINT', 'A word or a sentence', 'Una palabra o una frase', 'Uma palavra ou uma frase', '単語や文', 'Un mot ou une phrase')
t('TRANSLATOR_NONE', 'It could not be translated.', 'No se pudo traducir.', 'Não foi possível traduzir.', '翻訳できませんでした。', 'La traduction n’a pas pu se faire.')
t('TRANSLATOR_NOTHING', 'Nothing in it to practise', 'No hay nada que practicar', 'Não há nada para praticar', '練習できる字がありません', 'Rien à pratiquer')
t('SEL_COPY_TEXT', 'Copy as text', 'Copiar como texto', 'Copiar como texto', 'テキストでコピー', 'Copier en texte')
t('SEL_READING', 'Reading…', 'Leyendo…', 'Lendo…', '読み取り中…', 'Lecture…')
t('NOTICE_COPIED_TEXT', 'Copied: {0}', 'Copiado: {0}', 'Copiado: {0}', 'コピーしました：{0}', 'Copié : {0}')
t('NOTICE_COPIED_N', '{0,plural, one{Copied # character as text} other{Copied # characters as text}}', '{0,plural, one{# carácter copiado como texto} other{# caracteres copiados como texto}}', '{0,plural, one{# caractere copiado como texto} other{# caracteres copiados como texto}}', '{0}文字をテキストでコピーしました', '{0,plural, one{# caractère copié en texte} other{# caractères copiés en texte}}')
t('NOTICE_NOTHING_READ', 'Nothing could be read there', 'No se pudo leer nada ahí', 'Não foi possível ler nada aí', '読み取れませんでした', 'Rien n’a pu être lu')
t('NOTICE_NO_TEXT', 'The clipboard has no text', 'El portapapeles no tiene texto', 'A área de transferência não tem texto', 'クリップボードにテキストがありません', 'Le presse-papiers ne contient pas de texte')
t('NOTICE_LEFT_OUT', '{0,plural, one{# character left out: {APP} does not have it} other{# characters left out: {APP} does not have them}}', '{0,plural, one{Se omitió # carácter: {APP} no lo tiene} other{Se omitieron # caracteres: {APP} no los tiene}}', '{0,plural, one{# caractere omitido: o {APP} não o tem} other{# caracteres omitidos: o {APP} não os tem}}', '{APP}にない{0}文字は省きました', '{0,plural, one{# caractère omis : {APP} ne l’a pas} other{# caractères omis : {APP} ne les a pas}}')

# --- the screens' rows ------------------------------------------------------------------------
t('RETRY_WRONG', 'Retry wrong', 'Repetir fallos', 'Refazer erros', '間違いを再挑戦', 'Refaire les erreurs')
t('PRACTICE_WRONG', 'Practice wrong', 'Practicar fallos', 'Praticar erros', '間違いを練習', 'Revoir les erreurs')
t('TYPE_YOUR_OWN', 'Type your own', 'Escribir la tuya', 'Digitar a sua', '自分で入力', 'Saisir le vôtre')
t('ALBUM_WEAKEST', 'Weakest', 'Más flojos', 'Mais fracos', '苦手順', 'Plus faibles')
t('ALBUM_RECENT', 'Recent', 'Recientes', 'Recentes', '新しい順', 'Récents')
t('ALBUM_MOST', 'Most', 'Más practicados', 'Mais praticados', '回数順', 'Plus pratiqués')
t('WEAKEST_AGAIN', 'Weakest again', 'Repetir los flojos', 'Refazer os fracos', '苦手をもう一度', 'Revoir les faibles')

# --- Check ------------------------------------------------------------------------------------
t('CHECK_TITLE', 'Check', 'Revisar', 'Verificar', 'チェック', 'Vérifier')
t('CHECK_READING', 'Reading…', 'Leyendo…', 'Lendo…', '読み取り中…', 'Lecture…')
t('CHECK_NOTHING', 'Nothing to read here.', 'Aquí no hay nada que leer.', 'Não há nada para ler aqui.', '読み取れるものがありません。', 'Rien à lire ici.')
t('CHECK_MEANT_OK', 'Checked as what you meant.', 'Revisado como lo que querías decir.', 'Verificado como o que você quis dizer.', '書きたかった言葉としてチェックしました。', 'Vérifié selon ce que vous vouliez écrire.')
t('CHECK_CANDIDATES', 'What the selection looks like, best first. Tap the one you meant.', 'A qué se parece la selección, lo más parecido primero. Toca el que querías.', 'Com o que a seleção se parece, o mais parecido primeiro. Toque no que você quis.', '選択部分に似ている文字（似ている順）。書きたかった文字をタップしてください。', 'Ce à quoi ressemble la sélection, du plus proche au moins proche. Touchez celui que vous vouliez.')
t('CHECK_NO_MATCH', 'Nothing looks like this (it is compared with characters of about as many strokes).', 'Nada se parece a esto (se compara con caracteres de un número de trazos parecido).', 'Nada se parece com isto (a comparação é com caracteres de número de traços parecido).', '似ている文字がありません（画数の近い文字と比べています）。', 'Rien ne ressemble à ceci (la comparaison se fait avec des caractères d’un nombre de traits proche).')
t('CHECK_MLKIT_N', 'Read by ML Kit: {0} characters, {1} on average. Tap one to look closer.', 'Leído por ML Kit: {0} caracteres, {1} de media. Toca uno para verlo de cerca.', 'Lido pelo ML Kit: {0} caracteres, média {1}. Toque em um para ver de perto.', 'ML Kitで読み取り：{0}字、平均{1}点。タップすると詳しく見られます。', 'Lu par ML Kit : {0} caractères, {1} en moyenne. Touchez-en un pour le voir de près.')
t('CHECK_MEANT_N', 'Checked as what you meant: {0} characters, {1} on average. Tap one to look closer.', 'Revisado como lo que querías decir: {0} caracteres, {1} de media. Toca uno para verlo de cerca.', 'Verificado como o que você quis dizer: {0} caracteres, média {1}. Toque em um para ver de perto.', '書きたかった言葉としてチェック：{0}字、平均{1}点。タップすると詳しく見られます。', 'Vérifié selon ce que vous vouliez écrire : {0} caractères, {1} en moyenne. Touchez-en un pour le voir de près.')
t('CHECK_READ_N', 'Read as {0} characters, {1} on average. Tap one to look closer.', 'Leído como {0} caracteres, {1} de media. Toca uno para verlo de cerca.', 'Lido como {0} caracteres, média {1}. Toque em um para ver de perto.', '{0}字として読み取り、平均{1}点。タップすると詳しく見られます。', 'Lu comme {0} caractères, {1} en moyenne. Touchez-en un pour le voir de près.')
t('CHECK_MLKIT_TOO_MANY', 'ML Kit read more characters than there are strokes: read by {APP} instead.', 'ML Kit leyó más caracteres que trazos: lo lee {APP} en su lugar.', 'O ML Kit leu mais caracteres do que traços: o {APP} leu no lugar dele.', 'ML Kitが画数より多い文字を読み取ったため、{APP}が読み取りました。', 'ML Kit a lu plus de caractères qu’il n’y a de traits : lu par {APP} à la place.')
t('CHECK_TOO_FEW', 'Fewer strokes than the characters meant: read freely instead.', 'Menos trazos que los caracteres que querías: se lee libremente.', 'Menos traços do que os caracteres que você quis: lido livremente.', '書きたかった文字より画数が少ないため、自由に読み取りました。', 'Moins de traits que les caractères voulus : lu librement.')

# --- the viewer's Add and the word form ---------------------------------------------------------
t('WORD_TITLE', 'Your word with {0}', 'Tu palabra con {0}', 'Sua palavra com {0}', '「{0}」を使った言葉', 'Votre mot avec {0}')
t('WORD_FIELD_WORD', 'Word, with {0} in it', 'Palabra, con {0}', 'Palavra, com {0}', '言葉（「{0}」を含む）', 'Mot, avec {0}')
t('WORD_FIELD_MEANING', 'Meaning (optional)', 'Significado (opcional)', 'Significado (opcional)', '意味（任意）', 'Sens (facultatif)')
t('WORD_ERR_KANJI', 'The word has to have {0} in it', 'La palabra tiene que llevar {0}', 'A palavra precisa ter {0}', '言葉に「{0}」を含めてください', 'Le mot doit contenir {0}')
t('SEL_SAVE_WORD', 'Save word', 'Guardar palabra', 'Salvar palavra', '単語を保存', 'Enregistrer')
t('VOCAB', 'Vocabulary', 'Vocabulario', 'Vocabulário', '単語帳', 'Vocabulaire')
t('VOCAB_WORDS_N', P('# word', '# words'), P('# palabra', '# palabras'), P('# palavra', '# palavras'), '{0}語', P('# mot', '# mots'))
t('VOCAB_LISTS_N', P('# list', '# lists'), P('# lista', '# listas'), P('# lista', '# listas'), 'リスト{0}', P('# liste', '# listes'))
t('VOCAB_EMPTY', 'No words yet. Save them from a character’s examples, an example sentence, a photo or the lasso (Save word), or type one in with + Word.', 'Aún no hay palabras. Guárdalas desde los ejemplos de un carácter, una frase de ejemplo, una foto o el lazo (Guardar palabra), o escribe una con + Palabra.', 'Ainda não há palavras. Salve-as dos exemplos de um caractere, de uma frase de exemplo, de uma foto ou do laço (Salvar palavra), ou digite uma com + Palavra.', 'まだ言葉がありません。文字の例語、例文、写真、なげなわ（単語を保存）から保存するか、「＋言葉」で入力しましょう。', 'Pas encore de mots. Enregistrez-les depuis les exemples d’un caractère, une phrase d’exemple, une photo ou le lasso (Enregistrer), ou saisissez-en un avec + Mot.')
t('VOCAB_LIST_EMPTY', 'This list has no words yet. Add some with + Word, or tick this list on a word’s card.', 'Esta lista aún no tiene palabras. Añade alguna con + Palabra, o marca esta lista en la ficha de una palabra.', 'Esta lista ainda não tem palavras. Adicione com + Palavra, ou marque esta lista no cartão de uma palavra.', 'このリストにはまだ言葉がありません。「＋言葉」で追加するか、言葉のカードでこのリストを選びましょう。', 'Cette liste n’a pas encore de mots. Ajoutez-en avec + Mot, ou cochez cette liste sur la fiche d’un mot.')
t('VOCAB_SEARCH_NONE', 'No words match “{0}”.', 'Ninguna palabra coincide con «{0}».', 'Nenhuma palavra corresponde a “{0}”.', '「{0}」に合う単語はありません。', 'Aucun mot ne correspond à « {0} ».')
t('VOCAB_ADD_WORD', 'Word', 'Palabra', 'Palavra', '言葉', 'Mot')
t('VOCAB_REVIEW_N', 'Review {0}', 'Repasar {0}', 'Revisar {0}', '復習 {0}', 'Réviser {0}')
t('VOCAB_RENAME_LIST', 'Rename the list', 'Renombrar la lista', 'Renomear a lista', 'リスト名を変更', 'Renommer la liste')
t('VOCAB_DELETE_LIST', 'Delete list', 'Eliminar lista', 'Excluir lista', 'リストを削除', 'Supprimer la liste')
t('VOCAB_LIST_NAME_EMPTY', 'Give the list a name', 'Ponle un nombre a la lista', 'Dê um nome à lista', 'リスト名を入力してください', 'Donnez un nom à la liste')
t('VOCAB_LISTS_FULL', 'There are as many lists as there can be', 'Ya hay tantas listas como caben', 'Já há o máximo de listas', 'これ以上リストを作れません', 'Il y a déjà le nombre maximal de listes')
t('VOCAB_LIST_DELETED', '{0} deleted: its words stay in your vocabulary', '{0} eliminada: sus palabras siguen en tu vocabulario', '{0} excluída: as palavras continuam no seu vocabulário', '「{0}」を削除しました（言葉は単語帳に残ります）', '{0} supprimée : ses mots restent dans votre vocabulaire')
t('REVIEW_NEW', 'New', 'Nueva', 'Nova', '新規', 'Nouveau')
t('REVIEW_DUE', 'Due', 'Toca', 'Pendente', '今日', 'À revoir')
t('REVIEW_IN_N', P('in # day', 'in # days'), P('en # día', 'en # días'), P('em # dia', 'em # dias'), '{0}日後', P('dans # jour', 'dans # jours'))
t('WORDEXAM_TITLE_OF', 'Word exam · {0}', 'Examen de palabras · {0}', 'Prova de palavras · {0}', '単語テスト · {0}', 'Examen de mots · {0}')
t('WORDEXAM_INTRO', 'Each word written whole, from memory: a character a box', 'Cada palabra escrita entera, de memoria: un carácter por casilla', 'Cada palavra escrita inteira, de memória: um caractere por quadro', '言葉をまるごと記憶で書きます：1マスに1文字', 'Chaque mot écrit en entier, de mémoire : un caractère par case')
t('WORDEXAM_BY', 'Asked by', 'Preguntadas por', 'Perguntadas por', '出題のしかた', 'Demandés par')
t('WORDEXAM_BY_MEANING', 'Meaning and reading', 'Significado y lectura', 'Significado e leitura', '意味と読み', 'Sens et lecture')
t('WORDEXAM_BY_EAR', 'By ear', 'De oído', 'De ouvido', '聞いて', 'À l’oreille')
t('WORDEXAM_NONE', 'No words to ask here: save some first', 'Aquí no hay palabras que preguntar: guarda alguna primero', 'Não há palavras para perguntar aqui: salve algumas primeiro', 'ここには出題できる言葉がありません。まず保存しましょう', 'Aucun mot à demander ici : enregistrez-en d’abord')
t('WORDEXAM_PLAN', '{0} of the {1} words here, shuffled', '{0} de las {1} palabras de aquí, en orden aleatorio', '{0} das {1} palavras daqui, embaralhadas', 'ここの{1}語から{0}語をランダムに', '{0} des {1} mots d’ici, mélangés')
t('WORDEXAM_RULE', 'A word is right when every character of it reads right. The reviews follow.', 'Una palabra está bien cuando cada carácter se lee bien. Los repasos se ajustan.', 'Uma palavra está certa quando cada caractere é lido certo. As revisões acompanham.', 'すべての文字が正しく読めれば正解。復習の予定も更新されます。', 'Un mot est juste quand chaque caractère se lit juste. Les révisions suivent.')
t('WORDEXAM_HEAR_AGAIN', 'Tap to hear it again', 'Toca para oírla otra vez', 'Toque para ouvir de novo', 'タップでもう一度', 'Touchez pour l’entendre encore')
t('WORDEXAM_THEN_NEXT', 'A character a box, then Next', 'Un carácter por casilla, luego Siguiente', 'Um caractere por quadro, depois Próximo', '1マスに1文字、書けたら「次へ」', 'Un caractère par case, puis Suivant')
t('WORDEXAM_THEN_FINISH', 'A character a box, then Finish', 'Un carácter por casilla, luego Terminar', 'Um caractere por quadro, depois Concluir', '1マスに1文字、書けたら「終了」', 'Un caractère par case, puis Terminer')
t('SAVE_LIST', 'Save list', 'Guardar lista', 'Salvar lista', 'リストに保存', 'Enregistrer')
t('VOCAB_LIST_SAVED', P('Saved as {1}: # character, in your vocabulary', 'Saved as {1}: # characters, in your vocabulary'), P('Guardada como {1}: # carácter, en tu vocabulario', 'Guardada como {1}: # caracteres, en tu vocabulario'), P('Salva como {1}: # caractere, no seu vocabulário', 'Salva como {1}: # caracteres, no seu vocabulário'), '「{1}」として保存しました：{0}字（単語帳）', P('Enregistrée comme {1} : # caractère, dans votre vocabulaire', 'Enregistrée comme {1} : # caractères, dans votre vocabulaire'))
t('NOTE', 'Note', 'Nota', 'Nota', 'メモ', 'Note')
t('NOTE_TITLE', 'Your note on {0}', 'Tu nota sobre {0}', 'Sua nota sobre {0}', '「{0}」のメモ', 'Votre note sur {0}')
t('NOTE_PLACEHOLDER', 'A story or a trick to remember it, what it gets mixed up with…', 'Una historia o un truco para recordarlo, con qué se confunde…', 'Uma história ou um truque para lembrar, com o que se confunde…', '覚え方のストーリーやコツ、まぎらわしい字など', 'Une histoire ou une astuce pour le retenir, ce avec quoi on le confond…')
t('NOTE_DELETE', 'Delete note', 'Eliminar nota', 'Excluir nota', 'メモを削除', 'Supprimer la note')
t('WORD_FIELD_WRITTEN', 'Word', 'Palabra', 'Palavra', '言葉', 'Mot')
t('WORD_SAVE_TITLE', 'Save to your vocabulary', 'Guardar en tu vocabulario', 'Salvar no seu vocabulário', '単語帳に保存', 'Enregistrer dans votre vocabulaire')
t('WORD_SAVED_TITLE', 'In your vocabulary', 'En tu vocabulario', 'No seu vocabulário', '単語帳にあります', 'Dans votre vocabulaire')
t('WORD_FOUND', 'Words in it: tap one to save it', 'Palabras que contiene: toca una para guardarla', 'Palavras que contém: toque em uma para salvá-la', '含まれる言葉：タップして選ぶ', 'Mots qu’il contient : touchez-en un pour l’enregistrer')
t('WORD_LISTS', 'Lists', 'Listas', 'Listas', 'リスト', 'Listes')
t('WORD_NEW_LIST', 'New list', 'Nueva lista', 'Nova lista', '新しいリスト', 'Nouvelle liste')
t('WORD_LIST_NAME', 'List name (Lesson 3, Food…)', 'Nombre de la lista (Lección 3, Comida…)', 'Nome da lista (Lição 3, Comida…)', 'リスト名（第3課、食べ物…）', 'Nom de la liste (Leçon 3, Cuisine…)')
t('WORD_REMOVE', 'Remove', 'Quitar', 'Remover', '削除', 'Retirer')
t('WORD_ERR_EMPTY', 'Write the word first', 'Escribe primero la palabra', 'Escreva a palavra primeiro', 'まず言葉を入力してください', 'Écrivez d’abord le mot')
t('WORD_ERR_SAVED', 'That word is in your vocabulary already', 'Esa palabra ya está en tu vocabulario', 'Essa palavra já está no seu vocabulário', 'その言葉はもう単語帳にあります', 'Ce mot est déjà dans votre vocabulaire')
t('WORD_TRANSLATE_EMPTY', 'Type the meaning first, in your language', 'Escribe primero el significado, en tu idioma', 'Escreva primeiro o significado, no seu idioma', 'まず意味を英語で入力してください', 'Écrivez d’abord le sens, dans votre langue')
t('WORD_SENTENCE', 'From the sentence', 'De la frase', 'Da frase', '出てきた文', 'De la phrase')
t('VOCAB_SAVED', '{0} is in your vocabulary', '{0} está en tu vocabulario', '{0} está no seu vocabulário', '「{0}」を単語帳に保存しました', '{0} est dans votre vocabulaire')
t('VOCAB_SAVED_IN', '{0} is in your vocabulary, in {1}', '{0} está en tu vocabulario, en {1}', '{0} está no seu vocabulário, em {1}', '「{0}」を単語帳の「{1}」に保存しました', '{0} est dans votre vocabulaire, dans {1}')
t('VOCAB_REMOVED', '{0} left your vocabulary', '{0} salió de tu vocabulario', '{0} saiu do seu vocabulário', '「{0}」を単語帳から削除しました', '{0} a quitté votre vocabulaire')
t('VIEWER_ADD_WORDS', 'Add words', 'Añadir palabras', 'Adicionar palavras', '言葉を追加', 'Ajouter des mots')
t('VIEWER_YOURS_N', '{0} of yours', '{0} tuyas', '{0} suas', '自分の言葉：{0}', '{0} à vous')
t('VIEWER_ADD_HELP', 'Tap a word to add it to yours, or to take it off.', 'Toca una palabra para añadirla a las tuyas o quitarla.', 'Toque em uma palavra para adicioná-la às suas ou tirá-la.', '言葉をタップすると自分の言葉に追加・削除できます。', 'Touchez un mot pour l’ajouter aux vôtres, ou le retirer.')
t('VIEWER_ADD_OTHER', 'Something else? Type your own.', '¿Otra cosa? Escribe la tuya.', 'Outra coisa? Digite a sua.', 'ほかの言葉は「自分で入力」で。', 'Autre chose ? Saisissez le vôtre.')
t('VIEWER_NO_MORE_WORDS', 'No more dictionary words for this one: Type your own.', 'No hay más palabras del diccionario para este: escribe la tuya.', 'Não há mais palavras do dicionário para este: digite a sua.', 'この字の辞書の言葉はこれ以上ありません。「自分で入力」で追加できます。', 'Plus de mots du dictionnaire pour celui-ci : saisissez le vôtre.')
t('GRADE_N', 'Grade {0}', 'Curso {0}', '{0}º ano', '{0}年生', 'Niveau {0}')
t('GRADE_SECONDARY', 'Secondary school', 'Secundaria', 'Ensino médio', '中学校以降', 'Secondaire')
t('GRADE_NAMES', 'Jinmeiyō (names)', 'Jinmeiyō (nombres)', 'Jinmeiyō (nomes)', '人名用', 'Jinmeiyō (noms)')
t('WORDS', 'Words', 'Palabras', 'Palavras', '言葉', 'Mots')
t('VOCAB_LIST_N', 'List {0}', 'Lista {0}', 'Lista {0}', 'リスト{0}', 'Liste {0}')
t('SHEET', 'Sheet', 'Hoja', 'Folha', '練習シート', 'Feuille')
t('SHEET_TITLE', 'Writing practice', 'Práctica de escritura', 'Prática de escrita', '書き取り練習', 'Entraînement à l’écriture')
t('SHEET_FAILED', 'The practice sheet could not be made.', 'No se pudo crear la hoja de práctica.', 'Não foi possível criar a folha de prática.', '練習シートを作成できませんでした。', 'Impossible de créer la feuille d’entraînement.')
t('SHEET_SAVED', 'Practice sheet saved: {0}', 'Hoja de práctica guardada: {0}', 'Folha de prática salva: {0}', '練習シートを保存しました: {0}', 'Feuille d’entraînement enregistrée : {0}')
t('SHEET_FIRST_N', P('A sheet takes up to # character: the first went in.', 'A sheet takes up to # characters: the first # went in.'), P('Una hoja admite hasta # carácter: entró el primero.', 'Una hoja admite hasta # caracteres: entraron los primeros #.'), P('Uma folha aceita até # caractere: entrou o primeiro.', 'Uma folha aceita até # caracteres: entraram os primeiros #.'), '1枚のシートには{0}字まで入ります。最初の{0}字を入れました。', P('Une feuille prend jusqu’à # caractère : le premier y est.', 'Une feuille prend jusqu’à # caractères : les # premiers y sont.'))
t('EXAMPLE', 'Example', 'Ejemplo', 'Exemplo', '例文', 'Exemple')
t('WORDS_EXAMPLES', P('# example', '# examples'), P('# ejemplo', '# ejemplos'), P('# exemplo', '# exemplos'), '例 {0}', P('# exemple', '# exemples'))
t('WORDS_YOURS', '{0} yours', '{0} tuyas', '{0} suas', '自分の言葉 {0}', '{0} à vous')
t('NO_WORDS', 'No words yet: Add some.', 'Aún no hay palabras: añade algunas.', 'Ainda não há palavras: adicione algumas.', 'まだ言葉がありません。追加してみましょう。', 'Pas encore de mots : ajoutez-en.')

# --- Browse -------------------------------------------------------------------------------------
t('SEARCH_HINT', 'A meaning or a reading: tree, moku', 'Un significado o una lectura: árbol, moku', 'Um significado ou uma leitura: árvore, moku', '意味（英語）か読み：tree、moku', 'Un sens ou une lecture : arbre, moku')
t('BROWSE_DRAW', 'Draw', 'Dibujar', 'Desenhar', '手書き', 'Dessiner')
t('BROWSE_PARTS', 'Parts', 'Partes', 'Partes', '部品', 'Clés')
t('SORT_DEFAULT', 'Default', 'Por defecto', 'Padrão', '標準', 'Défaut')
t('SORT_STROKES', 'Strokes', 'Trazos', 'Traços', '画数', 'Traits')
t('SORT_MEANING', 'Meaning', 'Significado', 'Significado', '意味', 'Sens')
t('BROWSE_BEST', 'Best matches for your drawing: {0}', 'Lo más parecido a tu dibujo: {0}', 'O mais parecido com o seu desenho: {0}', '手書きに近い文字：{0}', 'Au plus proche de votre dessin : {0}')
t('BROWSE_PARTS_ONE', P('# character with the picked part', '# characters with the picked part'), P('# carácter con la parte elegida', '# caracteres con la parte elegida'), P('# caractere com a parte escolhida', '# caracteres com a parte escolhida'), '選んだ部品を含む字：{0}', P('# caractère avec la clé choisie', '# caractères avec la clé choisie'))
t('BROWSE_PARTS_MANY', P('# character with the picked parts', '# characters with the picked parts'), P('# carácter con las partes elegidas', '# caracteres con las partes elegidas'), P('# caractere com as partes escolhidas', '# caracteres com as partes escolhidas'), '選んだ部品を含む字：{0}', P('# caractère avec les clés choisies', '# caractères avec les clés choisies'))
t('BROWSE_PARTS_HINT', 'Tap parts: only characters that have all of them stay (dimmed parts: none left has them)', 'Toca partes: solo quedan los caracteres que las tienen todas (las atenuadas no están en ninguno de los que quedan)', 'Toque nas partes: só ficam os caracteres que têm todas (as esmaecidas não estão em nenhum dos que sobram)', '部品をタップ：すべてを含む字だけが残ります（薄い部品は残りの字にありません）', 'Touchez des clés : seuls restent les caractères qui les ont toutes (clés estompées : aucun restant ne les a)')
t('BROWSE_DRAW_HINT', 'Write a character in the box with the pen: every stroke re-ranks the list', 'Escribe un carácter en el recuadro con el lápiz: cada trazo reordena la lista', 'Escreva um caractere no quadro com a caneta: cada traço reordena a lista', 'ペンで枠に字を書くと、一画ごとに一覧が並び替わります', 'Écrivez un caractère dans le cadre avec le stylet : chaque trait réordonne la liste')


# --- the side panel and Settings ---------------------------------------------------------------
t('SIDE_STUDY', 'STUDY', 'ESTUDIO', 'ESTUDO', '学習', 'ÉTUDE')
t('ALBUM', 'Album', 'Álbum', 'Álbum', 'アルバム', 'Album')
t('EXAMS', 'Exams', 'Exámenes', 'Testes', 'テスト', 'Examens')
t('STATISTICS', 'Statistics', 'Estadísticas', 'Estatísticas', '統計', 'Statistiques')
t('SETTINGS_HANDWRITING', 'HANDWRITING', 'ESCRITURA', 'ESCRITA', '手書き認識', 'ÉCRITURE')
t('SETTINGS_MLKIT', 'Read with Google ML Kit', 'Leer con Google ML Kit', 'Ler com o Google ML Kit', 'Google ML Kitで読み取る', 'Lire avec Google ML Kit')
t('MLKIT_UNAVAILABLE', 'Not on this device: {APP} reads handwriting on its own.', 'No está en este dispositivo: {APP} lee la escritura por su cuenta.', 'Não está neste dispositivo: o {APP} lê a escrita por conta própria.', 'この端末では使えません。{APP}が自分で読み取ります。', 'Indisponible sur cet appareil : {APP} lit l’écriture seul.')
t('MLKIT_OFF', 'Off: {APP} reads handwriting on its own, and nothing is sent to Google.', 'Desactivado: {APP} lee la escritura por su cuenta y no se envía nada a Google.', 'Desligado: o {APP} lê a escrita por conta própria e nada é enviado ao Google.', 'オフ：{APP}が自分で読み取り、Googleには何も送信されません。', 'Désactivé : {APP} lit l’écriture seul et rien n’est envoyé à Google.')


# Reviews (review.h): spaced repetition of the characters being learnt.
t('REVIEWS', 'Reviews', 'Repasos', 'Revisões', '復習', 'Révisions')
t('REVIEWS_N', 'Reviews · {0}', 'Repasos · {0}', 'Revisões · {0}', '復習・{0}', 'Révisions · {0}')
t('REVIEWS_NONE', 'Nothing to review today: come back tomorrow, or mark more characters as Studying.', 'Nada que repasar hoy: vuelve mañana o marca más caracteres como Estudiando.', 'Nada para revisar hoje: volte amanhã ou marque mais caracteres como Estudando.', '今日の復習はありません。明日また来るか、学習中の文字を増やしましょう。', 'Rien à réviser aujourd’hui : revenez demain, ou marquez d’autres caractères En cours.')

# Licences: the study's documents (the core's are Fonts and Libraries).
t('LICENCE_DATA', 'Data', 'Datos', 'Dados', 'データ', 'Données')
t('LICENCE_MLKIT', 'ML Kit', 'ML Kit', 'ML Kit', 'ML Kit', 'ML Kit')

# Your data (the core's): what a study app keeps, and that ML Kit reads on the device too.
o('DATA_OFFLINE', '{APP} works offline. Your pages, marks, exams, words and practice stay on this device: {APP} sends them nowhere. (Google ML Kit, when it is on, downloads its models once, then reads and translates on the device too.)', '{APP} funciona sin conexión. Tus páginas, marcas, exámenes, palabras y prácticas se quedan en este dispositivo: {APP} no los envía a ninguna parte. (Google ML Kit, si está activado, descarga sus modelos una vez y después también lee y traduce en el dispositivo.)', 'O {APP} funciona offline. Suas páginas, marcas, provas, palavras e práticas ficam neste dispositivo: o {APP} não os envia para lugar nenhum. (O Google ML Kit, quando ativado, baixa seus modelos uma vez e depois também lê e traduz no dispositivo.)', '{APP}はオフラインで動作します。ページ、マーク、テスト、単語、練習の記録はこの端末に保存され、{APP}がどこかへ送ることはありません。（Google ML Kitがオンの場合は、モデルを一度だけダウンロードし、その後は読み取りも翻訳も端末内で行います。）', '{APP} fonctionne hors ligne. Vos pages, marques, examens, mots et entraînements restent sur cet appareil : {APP} ne les envoie nulle part. (Google ML Kit, s’il est activé, télécharge ses modèles une fois, puis lit et traduit lui aussi sur l’appareil.)')

# --- the exam ------------------------------------------------------------------------------------
t('EXAM_SELECTION', 'Selection', 'Selección', 'Seleção', '選択した字', 'Sélection')
t('EXAM_WHAT', 'WHAT', 'QUÉ', 'O QUÊ', '出題範囲', 'QUOI')
t('EXAM_HOW_MANY', 'HOW MANY', 'CUÁNTOS', 'QUANTOS', '問題数', 'COMBIEN')
t('EXAM_NOTHING_STUDYING', 'Nothing marked Studying yet', 'Aún no hay nada marcado como Estudiando', 'Ainda não há nada marcado como Estudando', '「学習中」の字はまだありません', 'Rien n’est encore marqué En cours')
t('EXAM_NOTHING', 'Nothing to ask here yet', 'Aún no hay nada que preguntar aquí', 'Ainda não há nada para perguntar aqui', 'ここにはまだ出題できる字がありません', 'Rien à demander ici pour l’instant')
t('EXAM_MARK_HINT', 'Mark characters with Study in the viewer, or in the character list’s Select mode.', 'Marca caracteres con Estudiar en el visor, o en el modo Seleccionar de la lista de caracteres.', 'Marque caracteres com Estudar no visualizador ou no modo Selecionar da lista de caracteres.', '字の表示画面の「学習する」か、文字一覧の選択モードで印を付けられます。', 'Marquez des caractères avec Étudier dans la fiche, ou dans le mode Sélectionner de la liste des caractères.')
t('EXAM_PLAN', '{0} of the {1} {2} characters, shuffled', '{0} de los {1} caracteres de {2}, al azar', '{0} dos {1} caracteres de {2}, embaralhados', '{2}の{1}字から{0}字、ランダムに出題', '{0} des {1} caractères {2}, mélangés')
t('EXAM_RULE', 'Right when it reads as the character (among its first three guesses); points for how well it is written.', 'Correcto si se lee como el carácter (entre sus tres primeras opciones); los puntos, por lo bien escrito que está.', 'Certo quando é lido como o caractere (entre os três primeiros palpites); os pontos, por quão bem está escrito.', '候補の上位3つに入れば正解。点数は字のきれいさです。', 'Juste s’il est lu comme le caractère (parmi ses trois premières propositions) ; les points, selon la qualité de l’écriture.')
t('EXAM_MAX', 'An exam asks {0} at most.', 'Un examen pregunta {0} como máximo.', 'Um teste pergunta no máximo {0}.', '1回のテストは最大{0}問です。', 'Un examen demande {0} caractères au plus.')
t('EXAM_TITLE_SOURCE', 'Exam · {0}', 'Examen · {0}', 'Teste · {0}', 'テスト・{0}', 'Examen · {0}')
t('EXAM_TAP_TO_LEAVE', 'Tap one to leave it out', 'Toca uno para dejarlo fuera', 'Toque em um para deixá-lo de fora', 'タップすると出題から外せます', 'Touchez-en un pour l’exclure')
t('EXAM_ONCE_EACH', 'Once each, from memory', 'Una vez cada uno, de memoria', 'Uma vez cada, de memória', '1回ずつ、何も見ずに', 'Une fois chacun, de mémoire')
t('EXAM_THEN_FINISH', 'Write it once, then Finish', 'Escríbelo una vez y pulsa Terminar', 'Escreva uma vez e toque em Concluir', '1回書いて「終了」', 'Écrivez-le une fois, puis Terminer')
t('EXAM_THEN_NEXT', 'Write it once, then Next', 'Escríbelo una vez y pulsa Siguiente', 'Escreva uma vez e toque em Próximo', '1回書いて「次へ」', 'Écrivez-le une fois, puis Suivant')
t('EXAM_READING_ANSWERS', 'Reading your answers... {0} of {1}', 'Leyendo tus respuestas... {0} de {1}', 'Lendo suas respostas... {0} de {1}', '答えを読み取り中… {0} / {1}', 'Lecture de vos réponses... {0} sur {1}')
t('EXAM_RESULT', '{0} of {1} right · {2} points', '{0} de {1} correctas · {2} puntos', '{0} de {1} certas · {2} pontos', '{1}問中{0}問正解・{2}点', '{0} sur {1} justes · {2} points')
t('EXAM_PASSED', 'Passed', 'Aprobado', 'Aprovado', '合格', 'Réussi')
t('EXAM_NOT_PASSED', 'Not passed yet', 'Aún no aprobado', 'Ainda não aprovado', 'まだ不合格', 'Pas encore réussi')
t('EXAM_READ_AS', 'read as', 'leído como', 'lido como', '読み取り', 'lu comme')

# --- statistics ---------------------------------------------------------------------------------
t('STATS_OVERVIEW', 'Overview', 'Resumen', 'Resumo', '概要', 'Vue d’ensemble')
t('STATS_ACTIVITY', 'Activity', 'Actividad', 'Atividade', '活動', 'Activité')
t('STATS_SCORES', 'Practice scores', 'Puntuaciones de práctica', 'Pontuações de prática', '練習の点数', 'Notes d’entraînement')
t('STATS_LEVELS', 'Levels', 'Niveles', 'Níveis', 'レベル', 'Niveaux')
t('STATS_MISTAKES', 'Mistakes', 'Errores', 'Erros', 'よくある間違い', 'Erreurs')
t('STATS_CHARACTERS', 'Characters', 'Caracteres', 'Caracteres', '文字', 'Caractères')
t('STATS_WHEN', 'When you practise', 'Cuándo practicas', 'Quando você pratica', '練習する時間帯', 'Quand vous pratiquez')
t('MISTAKE_ORDER', 'Stroke order', 'Orden de trazos', 'Ordem dos traços', '書き順', 'Ordre des traits')
t('MISTAKE_DIRECTION', 'Direction', 'Dirección', 'Direção', '方向', 'Sens du trait')
t('MISTAKE_MISSING', 'Missing strokes', 'Trazos que faltan', 'Traços faltando', '画の不足', 'Traits manquants')
t('MISTAKE_EXTRA', 'Extra strokes', 'Trazos de más', 'Traços a mais', '画の過多', 'Traits en trop')
t('MISTAKE_SHAPE', 'Shape', 'Forma', 'Forma', '形', 'Forme')
t('DURATION_HM', '{0} h {1} min', '{0} h {1} min', '{0} h {1} min', '{0}時間{1}分', '{0} h {1} min')
t('DURATION_M', '{0} min', '{0} min', '{0} min', '{0}分', '{0} min')
t('DURATION_S', '{0} s', '{0} s', '{0} s', '{0}秒', '{0} s')
t('TILE_SESSIONS', 'practice sessions', 'sesiones de práctica', 'sessões de prática', '練習回数', 'séances d’entraînement')
t('TILE_CHARACTERS', 'characters practised', 'caracteres practicados', 'caracteres praticados', '練習した字', 'caractères pratiqués')
t('TILE_SQUARES', 'squares written', 'cuadros escritos', 'quadrados escritos', '書いたマス', 'cases écrites')
t('TILE_TIME', 'writing time', 'tiempo escribiendo', 'tempo escrevendo', '書いた時間', 'temps d’écriture')
t('TILE_DAYS', 'days active', 'días activos', 'dias ativos', '練習した日数', 'jours actifs')
t('TILE_STREAK', 'day streak', 'días seguidos', 'dias seguidos', '連続日数', 'jours d’affilée')
t('TILE_BEST_STREAK', 'best streak', 'mejor racha', 'melhor sequência', '最長連続', 'meilleure série')
t('TILE_EXAMS', 'exams taken', 'exámenes hechos', 'testes feitos', '受けたテスト', 'examens passés')
t('TILE_PASSED', 'exams passed', 'exámenes aprobados', 'testes aprovados', '合格したテスト', 'examens réussis')
t('TILE_ACCURACY', 'exam accuracy', 'acierto en exámenes', 'acerto nos testes', 'テストの正答率', 'réussite aux examens')
t('TILE_STUDYING', 'studying', 'estudiando', 'estudando', '学習中', 'en cours')
t('TILE_KNOWN', 'known', 'dominados', 'dominados', '習得済み', 'acquis')
t('TILE_WORDS', 'words added', 'palabras añadidas', 'palavras adicionadas', '追加した言葉', 'mots ajoutés')
t('DAY_INITIAL_MON', 'M', 'L', 'S', '月', 'L')
t('DAY_INITIAL_WED', 'W', 'X', 'Q', '水', 'M')
t('DAY_INITIAL_FRI', 'F', 'V', 'S', '金', 'V')
t('DAY_INITIAL_SUN', 'S', 'D', 'D', '日', 'D')
t('STATS_ACTIVITY_CAPTION', 'The last {0} weeks: squares practised and exam answers, a day each', 'Las últimas {0} semanas: cuadros practicados y respuestas de examen, un día cada uno', 'As últimas {0} semanas: quadrados praticados e respostas de teste, um dia cada', '過去{0}週間：1日ごとの練習マス数とテストの解答数', 'Les {0} dernières semaines : cases pratiquées et réponses d’examen, un jour chacune')
t('STATS_NO_SCORES', 'No practice yet: scores show here week by week.', 'Aún no hay práctica: aquí se verán las puntuaciones semana a semana.', 'Ainda não há prática: as pontuações aparecem aqui semana a semana.', 'まだ練習がありません。点数が週ごとにここに表示されます。', 'Pas encore d’entraînement : les notes s’afficheront ici semaine par semaine.')
t('STATS_SCORES_TREND', 'Last {0} days {1} ({2} on the {3} before) · all time {4}', 'Últimos {0} días {1} ({2} respecto a los {3} anteriores) · total {4}', 'Últimos {0} dias {1} ({2} em relação aos {3} anteriores) · total {4}', '直近{0}日 {1}（前の{3}日から{2}）・全期間 {4}', '{0} derniers jours {1} ({2} par rapport aux {3} d’avant) · au total {4}')
t('STATS_SCORES_RECENT', 'Last {0} days {1} · all time {2}', 'Últimos {0} días {1} · total {2}', 'Últimos {0} dias {1} · total {2}', '直近{0}日 {1}・全期間 {2}', '{0} derniers jours {1} · au total {2}')
t('STATS_SCORES_ALL', 'All time {0}', 'Total {0}', 'Total {0}', '全期間 {0}', 'Au total {0}')
t('STATS_SCORES_CAPTION', 'Average score each week, the last {0} weeks', 'Puntuación media de cada semana, las últimas {0} semanas', 'Pontuação média de cada semana, as últimas {0} semanas', '過去{0}週間の週ごとの平均点', 'Note moyenne par semaine, les {0} dernières semaines')
t('STATS_NO_EXAMS', 'No exams yet: Exams, in the side panel.', 'Aún no hay exámenes: Exámenes, en el panel lateral.', 'Ainda não há testes: Testes, no painel lateral.', 'まだテストがありません。サイドパネルの「テスト」から。', 'Pas encore d’examen : Examens, dans le panneau latéral.')
t('STATS_EXAMS_LINE', '{0} taken, {1} passed · {2} of {3} answers right · {4} points', '{0} hechos, {1} aprobados · {2} de {3} respuestas correctas · {4} puntos', '{0} feitos, {1} aprovados · {2} de {3} respostas certas · {4} pontos', '受験{0}回・合格{1}回・{3}問中{2}問正解・{4}点', '{0} passés, {1} réussis · {2} réponses justes sur {3} · {4} points')
t('STATS_EXAMS_CAPTION', 'The last {0}: bars, the share right (passed at {1}%); dots, the points', 'Los últimos {0}: barras, el porcentaje de aciertos (aprobado desde el {1} %); puntos, la puntuación', 'Os últimos {0}: barras, a porcentagem de acertos (aprovado a partir de {1}%); pontos, a pontuação', '直近{0}回：棒は正答率（{1}%で合格）、点は点数', 'Les {0} derniers : barres, la part de réponses justes (réussi à {1} %) ; points, la note')
t('STATS_LEVEL_LINE', '{0} known, {1} practised / {2}', '{0} dominados, {1} practicados / {2}', '{0} dominados, {1} praticados / {2}', '習得{0}・練習{1} / {2}', '{0} acquis, {1} pratiqués / {2}')
t('STATS_LEGEND_KNOWN', 'known', 'dominados', 'dominados', '習得済み', 'acquis')
t('STATS_LEGEND_STUDYING', 'studying', 'estudiando', 'estudando', '学習中', 'en cours')
t('STATS_LEGEND_PRACTISED', 'practised', 'practicados', 'praticados', '練習済み', 'pratiqués')
t('STATS_NO_PRACTICE', 'No practice yet.', 'Aún no hay práctica.', 'Ainda não há prática.', 'まだ練習がありません。', 'Pas encore d’entraînement.')
t('STATS_MISTAKES_CAPTION', 'Squares with each: all time (light), the last {0} days (strong)', 'Cuadros con cada uno: en total (claro), los últimos {0} días (intenso)', 'Quadrados com cada um: no total (claro), os últimos {0} dias (forte)', '各間違いのあったマス：全期間（薄）、直近{0}日（濃）', 'Cases avec chacune : au total (clair), les {0} derniers jours (foncé)')
t('STATS_WEAKEST', 'Weakest (their latest session)', 'Más flojos (su última sesión)', 'Mais fracos (a última sessão)', '苦手な字（最新の練習）', 'Plus faibles (leur dernière séance)')
t('STATS_IMPROVED', 'Most improved (first session to latest)', 'Los que más mejoran (de la primera sesión a la última)', 'Os que mais melhoraram (da primeira sessão à última)', '伸びた字（最初から最新まで）', 'Plus grands progrès (de la première séance à la dernière)')
t('STATS_TWICE', 'Practise a character twice to see it here.', 'Practica un carácter dos veces para verlo aquí.', 'Pratique um caractere duas vezes para vê-lo aqui.', '2回練習した字がここに表示されます。', 'Entraînez-vous deux fois sur un caractère pour le voir ici.')
t('STATS_BY_HOUR', 'By hour of the day', 'Por hora del día', 'Por hora do dia', '時間帯別', 'Par heure de la journée')
t('STATS_BY_DAY', 'By day of the week', 'Por día de la semana', 'Por dia da semana', '曜日別', 'Par jour de la semaine')
t('STATS_SINCE', 'since {0}', 'desde el {0}', 'desde {0}', '{0}から', 'depuis le {0}')
t('STATS_MARKS', 'Known over time', 'Dominados con el tiempo', 'Dominados ao longo do tempo', '習得の推移', 'Acquis au fil du temps')
t('STATS_MARKS_NOW', '{0} known, {1} studying', '{0} dominados, {1} estudiando', '{0} dominados, {1} estudando', '習得済み{0}・学習中{1}', '{0} acquis, {1} en cours')
t('STATS_MARKS_RECENT', '{0} known in the last {1} days', '{0} dominados en los últimos {1} días', '{0} dominados nos últimos {1} dias', '直近{1}日の習得 {0}', '{0} acquis ces {1} derniers jours')
t('STATS_MARKS_CAPTION', 'At the end of each week, the last {0} weeks', 'Al final de cada semana, las últimas {0} semanas', 'No fim de cada semana, as últimas {0} semanas', '過去{0}週間の各週末の時点', 'À la fin de chaque semaine, les {0} dernières semaines')
t('STATS_NO_MARKS', 'Nothing marked yet.', 'Aún no hay nada marcado.', 'Ainda não há nada marcado.', 'まだ印がありません。', 'Rien de marqué pour l’instant.')
t('ALBUM_EXAMS_COUNTS', '{0,plural, one{# exam} other{# exams}}, {1} passed', '{0,plural, one{# examen} other{# exámenes}}, {1} aprobados', '{0,plural, one{# teste} other{# testes}}, {1} aprovados', 'テスト{0}回・合格{1}回', '{0,plural, one{# examen} other{# examens}}, {1} réussis')
t('EXAM_KEPT', '{0} · {1}', '{0} · {1}', '{0} · {1}', '{0}・{1}', '{0} · {1}')

# --- the album -------------------------------------------------------------------------------------
t('ALBUM_COUNTS', '{0} practised, {1}', '{0} practicados, {1}', '{0} praticados, {1}', '練習した字 {0}・{1}', '{0} pratiqués, {1}')
t('ALBUM_SINCE', '{0} since {1}', '{0} desde el {1}', '{0} desde {1}', '{1}から{0}', '{0} depuis le {1}')
t('ALBUM_FIRST_BEST_LAST', 'First {0}, best {1}, last {2}', 'Primera {0}, mejor {1}, última {2}', 'Primeira {0}, melhor {1}, última {2}', '最初 {0}・最高 {1}・最新 {2}', 'Première {0}, meilleure {1}, dernière {2}')
t('ALBUM_NO_SESSIONS', 'No sessions', 'Sin sesiones', 'Sem sessões', '練習なし', 'Aucune séance')
t('ALBUM_ATTEMPT', 'Attempt {0}: {1}. {2}', 'Intento {0}: {1}. {2}', 'Tentativa {0}: {1}. {2}', '{0}回目：{1}点。{2}', 'Essai {0} : {1}. {2}')

# --- practice -----------------------------------------------------------------------------------
t('PRACTICE_NOTHING', 'Nothing written yet: write in the squares with the pen', 'Aún no hay nada escrito: escribe en los cuadros con el lápiz', 'Ainda não há nada escrito: escreva nos quadrados com a caneta', 'まだ何も書かれていません。ペンでマスに書きましょう', 'Rien d’écrit pour l’instant : écrivez dans les cases avec le stylet')
t('PRACTICE_ALREADY_SAVED', 'Average {0}  (already saved)', 'Media {0}  (ya guardado)', 'Média {0}  (já salvo)', '平均 {0}（保存済み）', 'Moyenne {0}  (déjà enregistrée)')
t('PRACTICE_FROM_MEMORY', 'From memory: {0} · {1}', 'De memoria: {0} · {1}', 'De memória: {0} · {1}', '何も見ずに：{0}・{1}', 'De mémoire : {0} · {1}')
t('PRACTICE_AVERAGE', 'Average {0} over {1} · {2}', 'Media {0} en {1} · {2}', 'Média {0} em {1} · {2}', '{1}の平均 {0}・{2}', 'Moyenne {0} sur {1} · {2}')
t('SQUARES_N', P('# square', '# squares'), P('# cuadro', '# cuadros'), P('# quadrado', '# quadrados'), '{0}マス', P('# case', '# cases'))
t('SET_DONE', 'Set done', 'Serie terminada', 'Série concluída', 'セット完了', 'Série terminée')
t('SET_SUMMARY', '{0} of {1} practised, average {2}', '{0} de {1} practicados, media {2}', '{0} de {1} praticados, média {2}', '{1}字中{0}字を練習、平均 {2}', '{0} sur {1} pratiqués, moyenne {2}')
t('SET_NOTHING', 'Nothing was practised in this set', 'No se practicó nada en esta serie', 'Nada foi praticado nesta série', 'このセットでは何も練習しませんでした', 'Rien n’a été pratiqué dans cette série')
t('SET_WEAK', '{0} under {1}: “Weakest again” practises them, weakest first', '{0} por debajo de {1}: «Repetir los flojos» los practica, del más flojo al menos', '{0} abaixo de {1}: “Refazer os fracos” pratica esses, do mais fraco ao menos', '{1}点未満が{0}字：「苦手をもう一度」で苦手な順に練習できます', '{0} sous {1} : « Revoir les faibles » les reprend, du plus faible au moins faible')
t('SET_ALL_GOOD', 'All good this run', 'Todo bien esta vez', 'Tudo certo desta vez', '今回はすべて良好', 'Tout est bon cette fois')
t('PRACTICE_HEADER', '{0}   {1}', '{0}   {1}', '{0}   {1}', '{0}　{1}', '{0}   {1}')
t('PRACTICE_HEADER_LEVEL', '{0}   {1}   {2}', '{0}   {1}   {2}', '{0}   {1}   {2}', '{0}　{1}　{2}', '{0}   {1}   {2}')   # {2}: the level's long name (lang.h: "JLPT N5")
t('PRACTICE_HISTORY', '{0}   best {1}   last {2}   first {3}', '{0}   mejor {1}   última {2}   primera {3}', '{0}   melhor {1}   última {2}   primeira {3}', '{0}　最高 {1}　最新 {2}　最初 {3}', '{0}   meilleure {1}   dernière {2}   première {3}')
t('NOT_PRACTISED', 'Not practised yet', 'Aún sin practicar', 'Ainda não praticado', 'まだ練習していません', 'Pas encore pratiqué')
t('WRITE_AGAIN', '{0} · write again for another try', '{0} · vuelve a escribir para otro intento', '{0} · escreva de novo para outra tentativa', '{0}・もう一度書いて再挑戦', '{0} · réécrivez pour un nouvel essai')

# --- guided training ------------------------------------------------------------------------------
t('GUIDE_WRONG_STROKE', 'That is stroke {0}. Stroke {1} comes first.', 'Ese es el trazo {0}. Primero va el trazo {1}.', 'Esse é o traço {0}. Primeiro vem o traço {1}.', 'それは{0}画目です。先に{1}画目を書きます。', 'C’est le trait {0}. Le trait {1} vient d’abord.')
t('GUIDE_BACKWARDS', 'Backwards: stroke {0} starts at the dot.', 'Al revés: el trazo {0} empieza en el punto.', 'Ao contrário: o traço {0} começa no ponto.', '逆向きです。{0}画目は点から書き始めます。', 'À l’envers : le trait {0} commence au point.')
t('GUIDE_FOLLOW', 'Not quite: follow stroke {0} from the dot.', 'Casi: sigue el trazo {0} desde el punto.', 'Quase: siga o traço {0} a partir do ponto.', 'おしい！点から{0}画目をなぞりましょう。', 'Pas tout à fait : suivez le trait {0} depuis le point.')
t('GUIDE_WATCH', 'Not quite: watch stroke {0}, then write it from the dot.', 'Casi: mira el trazo {0} y escríbelo desde el punto.', 'Quase: observe o traço {0} e escreva-o a partir do ponto.', 'おしい！{0}画目を見てから、点から書きましょう。', 'Pas tout à fait : regardez le trait {0}, puis écrivez-le depuis le point.')
t('GUIDE_STEP1_DONE', 'Step 1 of 3 done. Next: only where each stroke starts', 'Paso 1 de 3 hecho. Ahora: solo dónde empieza cada trazo', 'Etapa 1 de 3 concluída. Agora: só onde cada traço começa', 'ステップ1/3完了。次は書き始めの位置だけ', 'Étape 1 sur 3 terminée. Ensuite : seulement le début de chaque trait')
t('GUIDE_STEP1', 'Step 1 of 3 · Trace stroke {0} of {1}: from the dot, the way the arrow points', 'Paso 1 de 3 · Repasa el trazo {0} de {1}: desde el punto, hacia donde indica la flecha', 'Etapa 1 de 3 · Contorne o traço {0} de {1}: do ponto, na direção da seta', 'ステップ1/3・{1}画中{0}画目をなぞる：点から矢印の方向へ', 'Étape 1 sur 3 · Suivez le trait {0} sur {1} : depuis le point, dans le sens de la flèche')
t('GUIDE_STEP2_DONE', 'Step 2 of 3 done. Next: from memory', 'Paso 2 de 3 hecho. Ahora: de memoria', 'Etapa 2 de 3 concluída. Agora: de memória', 'ステップ2/3完了。次は何も見ずに', 'Étape 2 sur 3 terminée. Ensuite : de mémoire')
t('GUIDE_STEP2', 'Step 2 of 3 · Stroke {0} of {1} starts at the dot', 'Paso 2 de 3 · El trazo {0} de {1} empieza en el punto', 'Etapa 2 de 3 · O traço {0} de {1} começa no ponto', 'ステップ2/3・{1}画中{0}画目は点から', 'Étape 2 sur 3 · Le trait {0} sur {1} commence au point')
t('GUIDE_STEP3', 'Step 3 of 3 · From memory: the whole character, {0}', 'Paso 3 de 3 · De memoria: el carácter entero, {0}', 'Etapa 3 de 3 · De memória: o caractere inteiro, {0}', 'ステップ3/3・何も見ずに字全体を（{0}）', 'Étape 3 sur 3 · De mémoire : le caractère entier, {0}')

# --- scoring feedback -------------------------------------------------------------------------------
t('SCORE_EMPTY', 'Empty', 'Vacío', 'Vazio', '空欄', 'Vide')
t('SCORE_NO_REFERENCE', 'No reference for this character', 'No hay referencia para este carácter', 'Não há referência para este caractere', 'この字の手本がありません', 'Pas de modèle pour ce caractère')
t('SCORE_COUNT', '{0}, should be {1}', '{0}, deberían ser {1}', '{0}, deveriam ser {1}', '{0}（正しくは{1}画）', '{0}, il en faut {1}')
t('SCORE_ORDER_SWAP', 'Order: stroke {0} before {1}', 'Orden: el trazo {0} antes que el {1}', 'Ordem: o traço {0} antes do {1}', '書き順：{0}画目は{1}画目より先', 'Ordre : le trait {0} avant le {1}')
t('SCORE_ORDER_MISPLACED', 'Order: {0} out of place', 'Orden: {0} fuera de lugar', 'Ordem: {0} fora do lugar', '書き順：{0}が違う順番', 'Ordre : {0} mal placé(s)')
t('SCORE_BACKWARDS', 'Stroke {0} drawn backwards', 'Trazo {0} al revés', 'Traço {0} ao contrário', '{0}画目が逆向き', 'Trait {0} à l’envers')
t('SCORE_BACKWARDS_MORE', 'Stroke {0} drawn backwards (and more)', 'Trazo {0} al revés (y más)', 'Traço {0} ao contrário (e outros)', '{0}画目などが逆向き', 'Trait {0} à l’envers (et d’autres)')
t('SCORE_SHAPE', 'Stroke {0}’s shape is off', 'La forma del trazo {0} no es correcta', 'A forma do traço {0} está errada', '{0}画目の形が違う', 'La forme du trait {0} n’est pas bonne')
t('SCORE_EXCELLENT', 'Excellent', 'Excelente', 'Excelente', 'たいへんよい', 'Excellent')
t('SCORE_GOOD', 'Good', 'Bien', 'Bom', 'よい', 'Bien')
t('SCORE_OK', 'OK, keep practising', 'Vale, sigue practicando', 'OK, continue praticando', 'まあまあ、練習を続けよう', 'Correct, continuez à vous entraîner')

# Why the app works offline (welcome.c): a must-read card (readcard.h), once, after the welcome. \n breaks a line.
t('OFFLINE_TITLE', 'Why {APP} works offline', 'Por qué {APP} funciona sin conexión', 'Por que o {APP} funciona offline', '{APP}がオフラインで動く理由', 'Pourquoi {APP} fonctionne hors ligne')
t('OFFLINE', '{APP} is made to work entirely on your device. There is no account to create and no server behind it: what you write, practise and save stays here, and the app works anywhere, with or without a connection.\\n\\nThis is a deliberate choice. Online features such as accounts, syncing between devices or cloud backups need servers, and servers cost money every month, for as long as the app exists. Paying for them would mean filling your study sessions with ads that break your concentration, and asking everyone for a monthly subscription on top of that.\\n\\n{APP} is built and maintained by a single independent developer, and it has to pay its own way. One purchase, with no ads and no subscription, is the fairest way to do that: you pay once, and the app is yours.\\n\\nTwo things to keep in mind:\\n• Handwriting recognition, text recognition and translation use Google’s models on your device. They download once and then work offline too.\\n• Your progress lives only on this device. Make a backup now and then in Settings › Your data, and keep it somewhere safe.\\n\\nThank you for supporting independent software.',
  '{APP} está hecho para funcionar por completo en tu dispositivo. No hace falta crear una cuenta ni hay ningún servidor detrás: lo que escribes, practicas y guardas se queda aquí, y la app funciona en cualquier lugar, con conexión o sin ella.\\n\\nEs una decisión meditada. Las funciones en línea, como las cuentas, la sincronización entre dispositivos o las copias en la nube, necesitan servidores, y los servidores cuestan dinero cada mes mientras la app exista. Pagarlos supondría llenar tus sesiones de estudio de anuncios que rompen la concentración y, además, pedir a todo el mundo una suscripción mensual.\\n\\n{APP} lo crea y lo mantiene un único desarrollador independiente, y tiene que sostenerse por sí mismo. Una sola compra, sin anuncios ni suscripciones, es la forma más justa de hacerlo: pagas una vez y la app es tuya.\\n\\nDos cosas a tener en cuenta:\\n• El reconocimiento de la escritura, el del texto y la traducción usan modelos de Google en tu dispositivo. Se descargan una vez y después también funcionan sin conexión.\\n• Tu progreso solo está en este dispositivo. Haz de vez en cuando una copia de seguridad en Ajustes › Tus datos y guárdala en un lugar seguro.\\n\\nGracias por apoyar el software independiente.',
  'O {APP} foi feito para funcionar inteiramente no seu dispositivo. Não é preciso criar uma conta e não há nenhum servidor por trás: o que você escreve, pratica e salva fica aqui, e o app funciona em qualquer lugar, com ou sem conexão.\\n\\nÉ uma escolha pensada. Recursos online, como contas, sincronização entre dispositivos ou backups na nuvem, precisam de servidores, e servidores custam dinheiro todo mês, enquanto o app existir. Pagar por eles significaria encher suas sessões de estudo de anúncios que quebram a concentração e, além disso, cobrar de todos uma assinatura mensal.\\n\\nO {APP} é criado e mantido por um único desenvolvedor independente, e precisa se sustentar sozinho. Uma única compra, sem anúncios e sem assinatura, é a forma mais justa de fazer isso: você paga uma vez e o app é seu.\\n\\nDuas coisas para ter em mente:\\n• O reconhecimento da escrita, o do texto e a tradução usam modelos do Google no seu dispositivo. Eles são baixados uma vez e depois também funcionam offline.\\n• Seu progresso fica só neste dispositivo. Faça um backup de vez em quando em Configurações › Seus dados e guarde-o em um lugar seguro.\\n\\nObrigado por apoiar o software independente.',
  '{APP}は、すべてこの端末の中で動くように作られています。アカウントの登録は不要で、裏で動くサーバーもありません。書いたもの、練習したもの、保存したものはこの端末に残り、ネット接続の有無にかかわらず、どこでも使えます。\\n\\nこれは意図した選択です。アカウントや端末間の同期、クラウドへのバックアップといったオンライン機能にはサーバーが必要で、サーバーにはアプリがある限り毎月費用がかかります。その費用をまかなうには、学習の集中を妨げる広告を並べ、さらに皆さんに月額のサブスクリプションをお願いすることになります。\\n\\n{APP}は、ひとりの個人開発者が作り、保守しています。アプリ自身で開発を続けていかなければなりません。広告もサブスクリプションもない一度きりの購入が、いちばん公正な方法だと考えました。一度お支払いいただければ、アプリはあなたのものです。\\n\\nご注意いただきたいこと：\\n• 手書き文字の認識、文字の読み取り、翻訳には、端末上で動くGoogleのモデルを使います。最初に一度ダウンロードすれば、その後はオフラインでも使えます。\\n• 学習の記録はこの端末にだけ保存されます。ときどき「設定 › データ」でバックアップを作り、安全な場所に保管してください。\\n\\n個人開発のソフトウェアを応援していただき、ありがとうございます。',
  '{APP} est conçu pour fonctionner entièrement sur votre appareil. Aucun compte à créer, aucun serveur derrière : ce que vous écrivez, pratiquez et enregistrez reste ici, et l’app fonctionne partout, avec ou sans connexion.\\n\\nC’est un choix délibéré. Les fonctions en ligne, comme les comptes, la synchronisation entre appareils ou les sauvegardes dans le cloud, ont besoin de serveurs, et les serveurs coûtent de l’argent chaque mois, tant que l’app existe. Les payer reviendrait à remplir vos séances d’étude de publicités qui brisent la concentration, et à demander en plus un abonnement mensuel à tout le monde.\\n\\n{APP} est créé et maintenu par un seul développeur indépendant, et doit couvrir ses propres coûts. Un achat unique, sans publicité ni abonnement, est la façon la plus juste d’y parvenir : vous payez une fois, et l’app est à vous.\\n\\nDeux choses à garder en tête :\\n• La reconnaissance de l’écriture, celle du texte et la traduction utilisent des modèles de Google sur votre appareil. Ils se téléchargent une fois, puis fonctionnent aussi hors ligne.\\n• Votre progression n’existe que sur cet appareil. Faites de temps en temps une sauvegarde dans Réglages › Vos données, et gardez-la en lieu sûr.\\n\\nMerci de soutenir les logiciels indépendants.')

# The voice missing (speech.h): the side panel's button, its card's title and Android's way to the settings.
t('VOICE_BUTTON', 'Set up the voice', 'Configurar la voz', 'Configurar a voz', '音声を設定', 'Configurer la voix')
t('VOICE_TITLE', 'No voice to read aloud yet', 'Aún no hay voz para leer en voz alta', 'Ainda não há voz para ler em voz alta', '読み上げの音声がまだありません', 'Pas encore de voix pour lire à voix haute')
t('VOICE_OPEN', 'Open settings', 'Abrir ajustes', 'Abrir configurações', '設定を開く', 'Ouvrir les réglages')
