// Copyright (c) 2026 Borja Vazquez Cuesta. All rights reserved.

#include "sim/sim.h"
#include <string.h>

// ===========================================================================
// THE CHIPS: logic chips as custom parts made of the primitives (logic.c),
// each a part's text as one is saved (fude_sim_def_read), its ports in its
// pins' order (pin 1 first: what a breadboard and a board's footprint go by;
// the first half down its left, the rest up its right), VCC and GND electric
// pins joined to nothing inside. "~" before a name: active when low.
// ===========================================================================

RDE_INTERNAL const c8* const FSC_CHIPS[] = {
    // 74HC00
    "fude-part 1\n"
    "id 74HC00\n"
    "name Quad NAND (74HC00)\n"
    "version 1\n"
    "desc Four 2-input NAND gates.\n"
    "port 1A logic in 1 left\n"
    "port 1B logic in 1 left\n"
    "port 1Y logic out 1 left\n"
    "port 2A logic in 1 left\n"
    "port 2B logic in 1 left\n"
    "port 2Y logic out 1 left\n"
    "port GND electric passive 1 left\n"
    "port 3Y logic out 1 right\n"
    "port 3A logic in 1 right\n"
    "port 3B logic in 1 right\n"
    "port 4Y logic out 1 right\n"
    "port 4A logic in 1 right\n"
    "port 4B logic in 1 right\n"
    "port VCC electric passive 1 right\n"
    "inst nand G1 \"\" 1A 1B 1Y\n"
    "inst nand G2 \"\" 2A 2B 2Y\n"
    "inst nand G3 \"\" 3A 3B 3Y\n"
    "inst nand G4 \"\" 4A 4B 4Y\n"
    "end\n"
    ,
    // 74HC02
    "fude-part 1\n"
    "id 74HC02\n"
    "name Quad NOR (74HC02)\n"
    "version 1\n"
    "desc Four 2-input NOR gates.\n"
    "port 1Y logic out 1 left\n"
    "port 1A logic in 1 left\n"
    "port 1B logic in 1 left\n"
    "port 2Y logic out 1 left\n"
    "port 2A logic in 1 left\n"
    "port 2B logic in 1 left\n"
    "port GND electric passive 1 left\n"
    "port 3A logic in 1 right\n"
    "port 3B logic in 1 right\n"
    "port 3Y logic out 1 right\n"
    "port 4A logic in 1 right\n"
    "port 4B logic in 1 right\n"
    "port 4Y logic out 1 right\n"
    "port VCC electric passive 1 right\n"
    "inst nor G1 \"\" 1A 1B 1Y\n"
    "inst nor G2 \"\" 2A 2B 2Y\n"
    "inst nor G3 \"\" 3A 3B 3Y\n"
    "inst nor G4 \"\" 4A 4B 4Y\n"
    "end\n"
    ,
    // 74HC04
    "fude-part 1\n"
    "id 74HC04\n"
    "name Hex inverter (74HC04)\n"
    "version 1\n"
    "desc Six NOT gates.\n"
    "port 1A logic in 1 left\n"
    "port 1Y logic out 1 left\n"
    "port 2A logic in 1 left\n"
    "port 2Y logic out 1 left\n"
    "port 3A logic in 1 left\n"
    "port 3Y logic out 1 left\n"
    "port GND electric passive 1 left\n"
    "port 4Y logic out 1 right\n"
    "port 4A logic in 1 right\n"
    "port 5Y logic out 1 right\n"
    "port 5A logic in 1 right\n"
    "port 6Y logic out 1 right\n"
    "port 6A logic in 1 right\n"
    "port VCC electric passive 1 right\n"
    "inst not G1 \"\" 1A 1Y\n"
    "inst not G2 \"\" 2A 2Y\n"
    "inst not G3 \"\" 3A 3Y\n"
    "inst not G4 \"\" 4A 4Y\n"
    "inst not G5 \"\" 5A 5Y\n"
    "inst not G6 \"\" 6A 6Y\n"
    "end\n"
    ,
    // 74HC08
    "fude-part 1\n"
    "id 74HC08\n"
    "name Quad AND (74HC08)\n"
    "version 1\n"
    "desc Four 2-input AND gates.\n"
    "port 1A logic in 1 left\n"
    "port 1B logic in 1 left\n"
    "port 1Y logic out 1 left\n"
    "port 2A logic in 1 left\n"
    "port 2B logic in 1 left\n"
    "port 2Y logic out 1 left\n"
    "port GND electric passive 1 left\n"
    "port 3Y logic out 1 right\n"
    "port 3A logic in 1 right\n"
    "port 3B logic in 1 right\n"
    "port 4Y logic out 1 right\n"
    "port 4A logic in 1 right\n"
    "port 4B logic in 1 right\n"
    "port VCC electric passive 1 right\n"
    "inst and G1 \"\" 1A 1B 1Y\n"
    "inst and G2 \"\" 2A 2B 2Y\n"
    "inst and G3 \"\" 3A 3B 3Y\n"
    "inst and G4 \"\" 4A 4B 4Y\n"
    "end\n"
    ,
    // 74HC32
    "fude-part 1\n"
    "id 74HC32\n"
    "name Quad OR (74HC32)\n"
    "version 1\n"
    "desc Four 2-input OR gates.\n"
    "port 1A logic in 1 left\n"
    "port 1B logic in 1 left\n"
    "port 1Y logic out 1 left\n"
    "port 2A logic in 1 left\n"
    "port 2B logic in 1 left\n"
    "port 2Y logic out 1 left\n"
    "port GND electric passive 1 left\n"
    "port 3Y logic out 1 right\n"
    "port 3A logic in 1 right\n"
    "port 3B logic in 1 right\n"
    "port 4Y logic out 1 right\n"
    "port 4A logic in 1 right\n"
    "port 4B logic in 1 right\n"
    "port VCC electric passive 1 right\n"
    "inst or G1 \"\" 1A 1B 1Y\n"
    "inst or G2 \"\" 2A 2B 2Y\n"
    "inst or G3 \"\" 3A 3B 3Y\n"
    "inst or G4 \"\" 4A 4B 4Y\n"
    "end\n"
    ,
    // 74HC86
    "fude-part 1\n"
    "id 74HC86\n"
    "name Quad XOR (74HC86)\n"
    "version 1\n"
    "desc Four 2-input XOR gates.\n"
    "port 1A logic in 1 left\n"
    "port 1B logic in 1 left\n"
    "port 1Y logic out 1 left\n"
    "port 2A logic in 1 left\n"
    "port 2B logic in 1 left\n"
    "port 2Y logic out 1 left\n"
    "port GND electric passive 1 left\n"
    "port 3Y logic out 1 right\n"
    "port 3A logic in 1 right\n"
    "port 3B logic in 1 right\n"
    "port 4Y logic out 1 right\n"
    "port 4A logic in 1 right\n"
    "port 4B logic in 1 right\n"
    "port VCC electric passive 1 right\n"
    "inst xor G1 \"\" 1A 1B 1Y\n"
    "inst xor G2 \"\" 2A 2B 2Y\n"
    "inst xor G3 \"\" 3A 3B 3Y\n"
    "inst xor G4 \"\" 4A 4B 4Y\n"
    "end\n"
    ,
    // 74HC74
    "fude-part 1\n"
    "id 74HC74\n"
    "name Dual D flip-flop (74HC74)\n"
    "version 1\n"
    "desc Two D flip-flops, each with its preset and clear (low: at once).\n"
    "port ~1CLR logic in 1 left\n"
    "port 1D logic in 1 left\n"
    "port 1CLK logic in 1 left\n"
    "port ~1PRE logic in 1 left\n"
    "port 1Q logic out 1 left\n"
    "port ~1Q logic out 1 left\n"
    "port GND electric passive 1 left\n"
    "port ~2Q logic out 1 right\n"
    "port 2Q logic out 1 right\n"
    "port ~2PRE logic in 1 right\n"
    "port 2CLK logic in 1 right\n"
    "port 2D logic in 1 right\n"
    "port ~2CLR logic in 1 right\n"
    "port VCC electric passive 1 right\n"
    "inst not C1 \"\" ~1CLR clr1\n"
    "inst not P1 \"\" ~1PRE pre1\n"
    "inst dffsr F1 \"\" 1D 1CLK pre1 clr1 1Q ~1Q\n"
    "inst not C2 \"\" ~2CLR clr2\n"
    "inst not P2 \"\" ~2PRE pre2\n"
    "inst dffsr F2 \"\" 2D 2CLK pre2 clr2 2Q ~2Q\n"
    "end\n"
    ,
    // 74HC138
    "fude-part 1\n"
    "id 74HC138\n"
    "name 3-to-8 decoder (74HC138)\n"
    "version 1\n"
    "desc One output of eight low, as A B C say, while G1 is high and G2A, G2B low.\n"
    "port A logic in 1 left\n"
    "port B logic in 1 left\n"
    "port C logic in 1 left\n"
    "port ~G2A logic in 1 left\n"
    "port ~G2B logic in 1 left\n"
    "port G1 logic in 1 left\n"
    "port ~Y7 logic out 1 left\n"
    "port GND electric passive 1 left\n"
    "port ~Y6 logic out 1 right\n"
    "port ~Y5 logic out 1 right\n"
    "port ~Y4 logic out 1 right\n"
    "port ~Y3 logic out 1 right\n"
    "port ~Y2 logic out 1 right\n"
    "port ~Y1 logic out 1 right\n"
    "port ~Y0 logic out 1 right\n"
    "port VCC electric passive 1 right\n"
    "inst not N1 \"\" ~G2A g2a\n"
    "inst not N2 \"\" ~G2B g2b\n"
    "inst and E \"inputs=3\" G1 g2a g2b en\n"
    "inst not NA \"\" A na\n"
    "inst not NB \"\" B nb\n"
    "inst not NC \"\" C nc\n"
    "inst nand Y0 \"inputs=4\" en na nb nc ~Y0\n"
    "inst nand Y1 \"inputs=4\" en A nb nc ~Y1\n"
    "inst nand Y2 \"inputs=4\" en na B nc ~Y2\n"
    "inst nand Y3 \"inputs=4\" en A B nc ~Y3\n"
    "inst nand Y4 \"inputs=4\" en na nb C ~Y4\n"
    "inst nand Y5 \"inputs=4\" en A nb C ~Y5\n"
    "inst nand Y6 \"inputs=4\" en na B C ~Y6\n"
    "inst nand Y7 \"inputs=4\" en A B C ~Y7\n"
    "end\n"
    ,
    // 74HC157
    "fude-part 1\n"
    "id 74HC157\n"
    "name Quad 2-to-1 multiplexer (74HC157)\n"
    "version 1\n"
    "desc Each Y is its A while S is low, its B while S is high; all low while E is high.\n"
    "port S logic in 1 left\n"
    "port 1A logic in 1 left\n"
    "port 1B logic in 1 left\n"
    "port 1Y logic out 1 left\n"
    "port 2A logic in 1 left\n"
    "port 2B logic in 1 left\n"
    "port 2Y logic out 1 left\n"
    "port GND electric passive 1 left\n"
    "port 3Y logic out 1 right\n"
    "port 3B logic in 1 right\n"
    "port 3A logic in 1 right\n"
    "port 4Y logic out 1 right\n"
    "port 4B logic in 1 right\n"
    "port 4A logic in 1 right\n"
    "port ~E logic in 1 right\n"
    "port VCC electric passive 1 right\n"
    "inst not NE \"\" ~E en\n"
    "inst not NS \"\" S ns\n"
    "inst and A1 \"inputs=3\" 1A ns en a1\n"
    "inst and B1 \"inputs=3\" 1B S en b1\n"
    "inst or O1 \"\" a1 b1 1Y\n"
    "inst and A2 \"inputs=3\" 2A ns en a2\n"
    "inst and B2 \"inputs=3\" 2B S en b2\n"
    "inst or O2 \"\" a2 b2 2Y\n"
    "inst and A3 \"inputs=3\" 3A ns en a3\n"
    "inst and B3 \"inputs=3\" 3B S en b3\n"
    "inst or O3 \"\" a3 b3 3Y\n"
    "inst and A4 \"inputs=3\" 4A ns en a4\n"
    "inst and B4 \"inputs=3\" 4B S en b4\n"
    "inst or O4 \"\" a4 b4 4Y\n"
    "end\n"
    ,
    // 74HC161
    "fude-part 1\n"
    "id 74HC161\n"
    "name 4-bit counter (74HC161)\n"
    "version 1\n"
    "desc Counts up on each clock while ENP and ENT are high; LOAD low takes A to D on the clock; CLR low clears it at once; RCO high at 15 while ENT is.\n"
    "port ~CLR logic in 1 left\n"
    "port CLK logic in 1 left\n"
    "port A logic in 1 left\n"
    "port B logic in 1 left\n"
    "port C logic in 1 left\n"
    "port D logic in 1 left\n"
    "port ENP logic in 1 left\n"
    "port GND electric passive 1 left\n"
    "port ~LOAD logic in 1 right\n"
    "port ENT logic in 1 right\n"
    "port QD logic out 1 right\n"
    "port QC logic out 1 right\n"
    "port QB logic out 1 right\n"
    "port QA logic out 1 right\n"
    "port RCO logic out 1 right\n"
    "port VCC electric passive 1 right\n"
    "inst const Z \"0\" zero\n"
    "inst not NC \"\" ~CLR clr\n"
    "inst not NL \"\" ~LOAD ld\n"
    "inst and EN \"\" ENP ENT t0\n"
    "inst and T1 \"\" t0 QA t1\n"
    "inst and T2 \"\" t1 QB t2\n"
    "inst and T3 \"\" t2 QC t3\n"
    "inst xor X0 \"\" QA t0 inc0\n"
    "inst and L0 \"\" A ld li0\n"
    "inst and K0 \"\" inc0 ~LOAD ki0\n"
    "inst or M0 \"\" li0 ki0 n0\n"
    "inst dffsr F0 \"\" n0 CLK zero clr QA -\n"
    "inst xor X1 \"\" QB t1 inc1\n"
    "inst and L1 \"\" B ld li1\n"
    "inst and K1 \"\" inc1 ~LOAD ki1\n"
    "inst or M1 \"\" li1 ki1 n1\n"
    "inst dffsr F1 \"\" n1 CLK zero clr QB -\n"
    "inst xor X2 \"\" QC t2 inc2\n"
    "inst and L2 \"\" C ld li2\n"
    "inst and K2 \"\" inc2 ~LOAD ki2\n"
    "inst or M2 \"\" li2 ki2 n2\n"
    "inst dffsr F2 \"\" n2 CLK zero clr QC -\n"
    "inst xor X3 \"\" QD t3 inc3\n"
    "inst and L3 \"\" D ld li3\n"
    "inst and K3 \"\" inc3 ~LOAD ki3\n"
    "inst or M3 \"\" li3 ki3 n3\n"
    "inst dffsr F3 \"\" n3 CLK zero clr QD -\n"
    "inst and R \"inputs=5\" ENT QA QB QC QD RCO\n"
    "end\n"
    ,
    // 74HC173
    "fude-part 1\n"
    "id 74HC173\n"
    "name 4-bit register (74HC173)\n"
    "version 1\n"
    "desc Takes 1D to 4D on the clock while G1 and G2 are low; its outputs released while M or N is high; CLR high clears it at once.\n"
    "port M logic in 1 left\n"
    "port N logic in 1 left\n"
    "port 1Q logic out 1 left\n"
    "port 2Q logic out 1 left\n"
    "port 3Q logic out 1 left\n"
    "port 4Q logic out 1 left\n"
    "port CLK logic in 1 left\n"
    "port GND electric passive 1 left\n"
    "port ~G1 logic in 1 right\n"
    "port ~G2 logic in 1 right\n"
    "port 4D logic in 1 right\n"
    "port 3D logic in 1 right\n"
    "port 2D logic in 1 right\n"
    "port 1D logic in 1 right\n"
    "port CLR logic in 1 right\n"
    "port VCC electric passive 1 right\n"
    "inst const Z \"0\" zero\n"
    "inst nor LD \"\" ~G1 ~G2 load\n"
    "inst not NL \"\" load hold\n"
    "inst nor OE \"\" M N oe\n"
    "inst and L1 \"\" 1D load li1\n"
    "inst and H1 \"\" q1 hold hi1\n"
    "inst or M1 \"\" li1 hi1 n1\n"
    "inst dffsr F1 \"\" n1 CLK zero CLR q1 -\n"
    "inst tribuf T1 \"\" q1 oe 1Q\n"
    "inst and L2 \"\" 2D load li2\n"
    "inst and H2 \"\" q2 hold hi2\n"
    "inst or M2 \"\" li2 hi2 n2\n"
    "inst dffsr F2 \"\" n2 CLK zero CLR q2 -\n"
    "inst tribuf T2 \"\" q2 oe 2Q\n"
    "inst and L3 \"\" 3D load li3\n"
    "inst and H3 \"\" q3 hold hi3\n"
    "inst or M3 \"\" li3 hi3 n3\n"
    "inst dffsr F3 \"\" n3 CLK zero CLR q3 -\n"
    "inst tribuf T3 \"\" q3 oe 3Q\n"
    "inst and L4 \"\" 4D load li4\n"
    "inst and H4 \"\" q4 hold hi4\n"
    "inst or M4 \"\" li4 hi4 n4\n"
    "inst dffsr F4 \"\" n4 CLK zero CLR q4 -\n"
    "inst tribuf T4 \"\" q4 oe 4Q\n"
    "end\n"
    ,
    // 74HC245
    "fude-part 1\n"
    "id 74HC245\n"
    "name Bus transceiver (74HC245)\n"
    "version 1\n"
    "desc A to B while DIR is high, B to A while it is low; neither while OE is high.\n"
    "port DIR logic in 1 left\n"
    "port A1 logic inout 1 left\n"
    "port A2 logic inout 1 left\n"
    "port A3 logic inout 1 left\n"
    "port A4 logic inout 1 left\n"
    "port A5 logic inout 1 left\n"
    "port A6 logic inout 1 left\n"
    "port A7 logic inout 1 left\n"
    "port A8 logic inout 1 left\n"
    "port GND electric passive 1 left\n"
    "port B8 logic inout 1 right\n"
    "port B7 logic inout 1 right\n"
    "port B6 logic inout 1 right\n"
    "port B5 logic inout 1 right\n"
    "port B4 logic inout 1 right\n"
    "port B3 logic inout 1 right\n"
    "port B2 logic inout 1 right\n"
    "port B1 logic inout 1 right\n"
    "port ~OE logic in 1 right\n"
    "port VCC electric passive 1 right\n"
    "inst not NO \"\" ~OE en\n"
    "inst not ND \"\" DIR nd\n"
    "inst and AB \"\" DIR en ab\n"
    "inst and BA \"\" nd en ba\n"
    "inst tribuf TA1 \"\" A1 ab B1\n"
    "inst tribuf TB1 \"\" B1 ba A1\n"
    "inst tribuf TA2 \"\" A2 ab B2\n"
    "inst tribuf TB2 \"\" B2 ba A2\n"
    "inst tribuf TA3 \"\" A3 ab B3\n"
    "inst tribuf TB3 \"\" B3 ba A3\n"
    "inst tribuf TA4 \"\" A4 ab B4\n"
    "inst tribuf TB4 \"\" B4 ba A4\n"
    "inst tribuf TA5 \"\" A5 ab B5\n"
    "inst tribuf TB5 \"\" B5 ba A5\n"
    "inst tribuf TA6 \"\" A6 ab B6\n"
    "inst tribuf TB6 \"\" B6 ba A6\n"
    "inst tribuf TA7 \"\" A7 ab B7\n"
    "inst tribuf TB7 \"\" B7 ba A7\n"
    "inst tribuf TA8 \"\" A8 ab B8\n"
    "inst tribuf TB8 \"\" B8 ba A8\n"
    "end\n"
    ,
    // 74HC283
    "fude-part 1\n"
    "id 74HC283\n"
    "name 4-bit adder (74HC283)\n"
    "version 1\n"
    "desc A1-A4 plus B1-B4 plus C0: S1-S4 and its carry C4.\n"
    "port S2 logic out 1 left\n"
    "port B2 logic in 1 left\n"
    "port A2 logic in 1 left\n"
    "port S1 logic out 1 left\n"
    "port A1 logic in 1 left\n"
    "port B1 logic in 1 left\n"
    "port C0 logic in 1 left\n"
    "port GND electric passive 1 left\n"
    "port C4 logic out 1 right\n"
    "port S4 logic out 1 right\n"
    "port B4 logic in 1 right\n"
    "port A4 logic in 1 right\n"
    "port S3 logic out 1 right\n"
    "port A3 logic in 1 right\n"
    "port B3 logic in 1 right\n"
    "port VCC electric passive 1 right\n"
    "inst xor P1 \"\" A1 B1 p1\n"
    "inst xor S1 \"\" p1 C0 S1\n"
    "inst and G1 \"\" A1 B1 g1\n"
    "inst and Q1 \"\" p1 C0 q1\n"
    "inst or C1 \"\" g1 q1 c1\n"
    "inst xor P2 \"\" A2 B2 p2\n"
    "inst xor S2 \"\" p2 c1 S2\n"
    "inst and G2 \"\" A2 B2 g2\n"
    "inst and Q2 \"\" p2 c1 q2\n"
    "inst or C2 \"\" g2 q2 c2\n"
    "inst xor P3 \"\" A3 B3 p3\n"
    "inst xor S3 \"\" p3 c2 S3\n"
    "inst and G3 \"\" A3 B3 g3\n"
    "inst and Q3 \"\" p3 c2 q3\n"
    "inst or C3 \"\" g3 q3 c3\n"
    "inst xor P4 \"\" A4 B4 p4\n"
    "inst xor S4 \"\" p4 c3 S4\n"
    "inst and G4 \"\" A4 B4 g4\n"
    "inst and Q4 \"\" p4 c3 q4\n"
    "inst or C4 \"\" g4 q4 C4\n"
    "end\n"
    ,
    // 74HC189
    "fude-part 1\n"
    "id 74HC189\n"
    "name 16 x 4 memory (74HC189)\n"
    "version 1\n"
    "desc Sixteen words of four bits: written while CS and WE are low; read (turned over) while CS is low and WE high; released otherwise.\n"
    "port A0 logic in 1 left\n"
    "port ~CS logic in 1 left\n"
    "port ~WE logic in 1 left\n"
    "port D1 logic in 1 left\n"
    "port ~Q1 logic out 1 left\n"
    "port D2 logic in 1 left\n"
    "port ~Q2 logic out 1 left\n"
    "port GND electric passive 1 left\n"
    "port ~Q3 logic out 1 right\n"
    "port D3 logic in 1 right\n"
    "port ~Q4 logic out 1 right\n"
    "port D4 logic in 1 right\n"
    "port A3 logic in 1 right\n"
    "port A2 logic in 1 right\n"
    "port A1 logic in 1 right\n"
    "port VCC electric passive 1 right\n"
    "inst const Z \"0\" zero\n"
    "inst nor WE \"\" ~CS ~WE we\n"
    "inst not NS \"\" ~CS cs\n"
    "inst and OE \"\" cs ~WE oe\n"
    "inst ram M \"address=4 data=4 clocked=0\" A0 A1 A2 A3 D1 D2 D3 D4 we zero q1 q2 q3 q4\n"
    "inst not I1 \"\" q1 nq1\n"
    "inst tribuf T1 \"\" nq1 oe ~Q1\n"
    "inst not I2 \"\" q2 nq2\n"
    "inst tribuf T2 \"\" nq2 oe ~Q2\n"
    "inst not I3 \"\" q3 nq3\n"
    "inst tribuf T3 \"\" nq3 oe ~Q3\n"
    "inst not I4 \"\" q4 nq4\n"
    "inst tribuf T4 \"\" nq4 oe ~Q4\n"
    "end\n"
    ,
    // CD4511
    "fude-part 1\n"
    "id CD4511\n"
    "name BCD to 7-segment decoder (CD4511)\n"
    "version 1\n"
    "desc A digit's segments from four bits (A the lowest): latched while LE is high; all lit while LT is low, none while BI is low; 10 to 15 blank.\n"
    "port B logic in 1 left\n"
    "port C logic in 1 left\n"
    "port ~LT logic in 1 left\n"
    "port ~BI logic in 1 left\n"
    "port LE logic in 1 left\n"
    "port D logic in 1 left\n"
    "port A logic in 1 left\n"
    "port VSS electric passive 1 left\n"
    "port e logic out 1 right\n"
    "port d logic out 1 right\n"
    "port c logic out 1 right\n"
    "port b logic out 1 right\n"
    "port a logic out 1 right\n"
    "port g logic out 1 right\n"
    "port f logic out 1 right\n"
    "port VDD electric passive 1 right\n"
    "inst not NLE \"\" LE nle\n"
    "inst not NLT \"\" ~LT lt\n"
    "inst and LA1 \"\" A nle ta1\n"
    "inst and LA2 \"\" qa LE ta2\n"
    "inst and LA3 \"\" A qa ta3\n"
    "inst or LA \"inputs=3\" ta1 ta2 ta3 qa\n"
    "inst not NA \"\" qa na\n"
    "inst and LB1 \"\" B nle tb1\n"
    "inst and LB2 \"\" qb LE tb2\n"
    "inst and LB3 \"\" B qb tb3\n"
    "inst or LB \"inputs=3\" tb1 tb2 tb3 qb\n"
    "inst not NB \"\" qb nb\n"
    "inst and LC1 \"\" C nle tc1\n"
    "inst and LC2 \"\" qc LE tc2\n"
    "inst and LC3 \"\" C qc tc3\n"
    "inst or LC \"inputs=3\" tc1 tc2 tc3 qc\n"
    "inst not NC \"\" qc nc\n"
    "inst and LD1 \"\" D nle td1\n"
    "inst and LD2 \"\" qd LE td2\n"
    "inst and LD3 \"\" D qd td3\n"
    "inst or LD \"inputs=3\" td1 td2 td3 qd\n"
    "inst not ND \"\" qd nd\n"
    "inst and D0 \"inputs=4\" na nb nc nd dg0\n"
    "inst and D1 \"inputs=4\" qa nb nc nd dg1\n"
    "inst and D2 \"inputs=4\" na qb nc nd dg2\n"
    "inst and D3 \"inputs=4\" qa qb nc nd dg3\n"
    "inst and D4 \"inputs=4\" na nb qc nd dg4\n"
    "inst and D5 \"inputs=4\" qa nb qc nd dg5\n"
    "inst and D6 \"inputs=4\" na qb qc nd dg6\n"
    "inst and D7 \"inputs=4\" qa qb qc nd dg7\n"
    "inst and D8 \"inputs=4\" na nb nc qd dg8\n"
    "inst and D9 \"inputs=4\" qa nb nc qd dg9\n"
    "inst or Sa \"inputs=7\" dg0 dg2 dg3 dg5 dg7 dg8 dg9 ra\n"
    "inst and Ba \"\" ~BI ra sa\n"
    "inst or Oa \"\" lt sa a\n"
    "inst or Sb \"inputs=8\" dg0 dg1 dg2 dg3 dg4 dg7 dg8 dg9 rb\n"
    "inst and Bb \"\" ~BI rb sb\n"
    "inst or Ob \"\" lt sb b\n"
    "inst or Sc \"inputs=9\" dg0 dg1 dg3 dg4 dg5 dg6 dg7 dg8 dg9 rc\n"
    "inst and Bc \"\" ~BI rc sc\n"
    "inst or Oc \"\" lt sc c\n"
    "inst or Sd \"inputs=6\" dg0 dg2 dg3 dg5 dg6 dg8 rd\n"
    "inst and Bd \"\" ~BI rd sd\n"
    "inst or Od \"\" lt sd d\n"
    "inst or Se \"inputs=4\" dg0 dg2 dg6 dg8 re\n"
    "inst and Be \"\" ~BI re se\n"
    "inst or Oe \"\" lt se e\n"
    "inst or Sf \"inputs=6\" dg0 dg4 dg5 dg6 dg8 dg9 rf\n"
    "inst and Bf \"\" ~BI rf sf\n"
    "inst or Of \"\" lt sf f\n"
    "inst or Sg \"inputs=7\" dg2 dg3 dg4 dg5 dg6 dg8 dg9 rg\n"
    "inst and Bg \"\" ~BI rg sg\n"
    "inst or Og \"\" lt sg g\n"
    "end\n"
    ,
};

#define FSC_N ((u32)(sizeof(FSC_CHIPS) / sizeof(FSC_CHIPS[0])))

u32 fude_sim_chip_count(void) {
    return FSC_N;
}

const c8* fude_sim_chip_text(u32 _i) {
    return _i < FSC_N ? FSC_CHIPS[_i] : NULL;
}

u32 fude_sim_chips_add(fude_sim_lib* _lib) {
    u32 _failed = 0;
    for(u32 _i = 0; _i < FSC_N; _i++) {
        c8 _error[160];
        fude_sim_def* _def = fude_sim_def_read(FSC_CHIPS[_i], strlen(FSC_CHIPS[_i]), _error, sizeof(_error));
        if(_def == NULL) {
            _failed++;
            continue;
        }
        fude_sim_lib_add(_lib, _def);
    }
    return _failed;
}
